/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * FROM ../alpha-emulator/ifunpred.as. ANY CHANGES MADE TO THIS FILE WILL BE LOST
 ************************************************************************/

  /* Predicates. */
/* start DoEql */

  /* Halfword operand from stack instruction - DoEql */
  /* arg2 has the preloaded 8 bit operand. */

doeql:
  if (_trace) printf("doeql:\n");
#ifdef TRACING
#endif

DoEqlSP:
  if (_trace) printf("DoEqlSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdoeql;
#endif

DoEqlLP:
  if (_trace) printf("DoEqlLP:\n");
#ifdef TRACING
  goto headdoeql;
#endif

DoEqlFP:
  if (_trace) printf("DoEqlFP:\n");

headdoeql:
  if (_trace) printf("headdoeql:\n");
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindoeql:
  if (_trace) printf("begindoeql:\n");
  /* arg1 has the operand, not sign extended if immediate. */
  arg6 = arg3 >> 12;
  /* Load arg1 into t3 */
  t3 = *(u64 *)iSP;
  /* Low part of EQ-NOT-EQL mask */
  t4 = zero + -2048;
  t11 = *(u64 *)&(processor->niladdress);
  /* High part of EQ-NOT-EQL mask */
  t4 = t4 + ((1) << 16);
  /* Assume result will be T */
  t12 = *(u64 *)&(processor->taddress);
  t5 = arg1 ^ t3;
  /* Shift left to lose CDRCODE. */
  t5 = t5 << 26;
  /* 1 if no-pop, 0 if pop */
  arg6 = arg6 & 1;
  if (t5 == 0)
    goto eqldone;
  /* They are not EQ, if types different or not numeric return nil */
  /* Get the tag alone */
  t5 = t5 >> 58;
  /* Now assume result will be NIL */
  t12 = t11;
  /* Return NIL if tags different */
  if (t5 != 0)
    goto eqldone;
  /* Get tag, check for numeric */
  t3 = t3 >> 32;
  /* TagType. */
  t3 = t3 & 63;
  /* Type is now a bit mask */
  t4 = t4 >> (t3 & 63);
  /* If funny numeric type, exception */
  if (t4 & 1)
    goto eqlexc;

eqldone:
  if (_trace) printf("eqldone:\n");
  /* Either a stack-push or a stack-write */
  iSP = (arg6 * 8) + iSP;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  *(u64 *)iSP = t12;
  goto cachevalid;
#ifdef TRACING
  goto DoEqlIM;
#endif

DoEqlIM:
  if (_trace) printf("DoEqlIM:\n");
  arg2 = arg2 << 56;
  /* t4=tag t3=data */
  t4 = *(s32 *)(iSP + 4);
  t3 = *(s32 *)iSP;
  arg6 = arg3 >> 12;
  /* Sign extension of arg2 is complete */
  arg2 = (s64)arg2 >> 56;
  t3 = (u32)t3;
  t11 = *(u64 *)&(processor->niladdress);
  /* TagType. */
  t4 = t4 & 63;
  t12 = *(u64 *)&(processor->taddress);
  arg2 = (s32)t3 - (s32)arg2;
  t4 = t4 ^ Type_Fixnum;
  /* 1 if no-pop, 0 if pop */
  arg6 = arg6 & 1;
  t4 = arg2 | t4;
  /* Either a stack-push or a stack-write */
  iSP = (arg6 * 8) + iSP;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  if (t4 == 0)
    t11 = t12;
  /* Yes Virginia, this does dual issue with above */
  *(u64 *)iSP = t11;
  goto cachevalid;

eqlexc:
  if (_trace) printf("eqlexc:\n");
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto exception;

/* end DoEql */
  /* End of Halfword operand from stack instruction - DoEql */
/* start DoGreaterp */

  /* Halfword operand from stack instruction - DoGreaterp */
  /* arg2 has the preloaded 8 bit operand. */

dogreaterp:
  if (_trace) printf("dogreaterp:\n");
#ifdef TRACING
#endif

DoGreaterpSP:
  if (_trace) printf("DoGreaterpSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindogreaterp;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindogreaterp;
#endif

DoGreaterpLP:
  if (_trace) printf("DoGreaterpLP:\n");
#ifdef TRACING
  goto begindogreaterp;
#endif

DoGreaterpFP:
  if (_trace) printf("DoGreaterpFP:\n");

begindogreaterp:
  if (_trace) printf("begindogreaterp:\n");
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  t11 = *(u64 *)&(processor->niladdress);
  t7 = arg3 >> 12;
  t12 = *(u64 *)&(processor->taddress);
  /* Get ARG1 tag */
  arg3 = (u32)(arg6 >> ((4&7)*8));
  /* t1 is tag of arg2 */
  t1 = *(s32 *)(arg1 + 4);
  LDS(1, f1, *(u32 *)iSP );
  t7 = t7 & 1;
  arg2 = *(s32 *)arg1;
  arg4 = (s32)arg6;
  LDS(2, f2, *(u32 *)arg1 );
  /* Strip off any CDR code bits. */
  t5 = arg3 & 63;
  /* Strip off any CDR code bits. */
  t4 = t1 & 63;
  t6 = (t5 == Type_Fixnum) ? 1 : 0;

g8001:
  if (_trace) printf("g8001:\n");
  if (t6 == 0)
    goto g7989;
  /* Here if argument TypeFixnum */
  t3 = (t4 == Type_Fixnum) ? 1 : 0;

g7993:
  if (_trace) printf("g7993:\n");
  if (t3 == 0)
    goto g7984;
  /* Here if argument TypeFixnum */
  t2 = arg4 - arg2;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  /* Pop/No-pop */
  iSP = (t7 * 8) + iSP;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* T if the test succeeds */
  if ((s64)t2 > 0)
    t11 = t12;
  *(u64 *)iSP = t11;
  goto cachevalid;

g7990:
  if (_trace) printf("g7990:\n");

g7989:
  if (_trace) printf("g7989:\n");
  t6 = (t5 == Type_SingleFloat) ? 1 : 0;

g8002:
  if (_trace) printf("g8002:\n");
  if (t6 == 0)
    goto g7994;
  /* Here if argument TypeSingleFloat */
  t3 = (t4 == Type_SingleFloat) ? 1 : 0;

g7998:
  if (_trace) printf("g7998:\n");
  if (t3 == 0)
    goto g7984;
  /* Here if argument TypeSingleFloat */

greaterpmmexcfltflt:
  if (_trace) printf("greaterpmmexcfltflt:\n");
  SETFLTT(3,f3, FLTU64(1,f1) <= FLTU64(2,f2) ? 2.0:0);
  /* Force the trap to occur here */
  /* trapb force the trap to occur here */
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iSP = (t7 * 8) + iSP;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  *(u64 *)iSP = t12;
  if (FLTU64(3, f3) == 0.0)
    goto cachevalid;
  /* Didn't branch, answer is NIL */
  *(u64 *)iSP = t11;
  goto cachevalid;

g7995:
  if (_trace) printf("g7995:\n");

g7994:
  if (_trace) printf("g7994:\n");
  /* Here for all other cases */

g7984:
  if (_trace) printf("g7984:\n");
  goto greaterpmmexc;

g7988:
  if (_trace) printf("g7988:\n");
#ifdef TRACING
  goto DoGreaterpIM;
#endif

DoGreaterpIM:
  if (_trace) printf("DoGreaterpIM:\n");
  t11 = *(u64 *)&(processor->niladdress);
  /* First half of sign extension */
  arg2 = arg2 << 56;
  t12 = *(u64 *)&(processor->taddress);
  t7 = arg3 >> 12;
  arg3 = (u32)(arg6 >> ((4&7)*8));
  arg4 = (s32)arg6;
  /* Second half of sign extension */
  arg2 = (s64)arg2 >> 56;
  t7 = t7 & 1;
  /* Strip off any CDR code bits. */
  t3 = arg3 & 63;
  t4 = (t3 == Type_Fixnum) ? 1 : 0;

g8007:
  if (_trace) printf("g8007:\n");
  if (t4 == 0)
    goto g8004;
  /* Here if argument TypeFixnum */
  t2 = arg4 - arg2;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iSP = (t7 * 8) + iSP;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* T if the test succeeds */
  if ((s64)t2 > 0)
    t11 = t12;
  *(u64 *)iSP = t11;
  goto cachevalid;

g8004:
  if (_trace) printf("g8004:\n");
  /* Here for all other cases */
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;

g8003:
  if (_trace) printf("g8003:\n");

/* end DoGreaterp */
  /* End of Halfword operand from stack instruction - DoGreaterp */
/* start DoLogtest */

  /* Halfword operand from stack instruction - DoLogtest */
  /* arg2 has the preloaded 8 bit operand. */

dologtest:
  if (_trace) printf("dologtest:\n");
#ifdef TRACING
#endif

DoLogtestSP:
  if (_trace) printf("DoLogtestSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  if (arg2 != 0)
    goto begindologtest;
  /* SP-pop, Reload TOS */
  arg6 = *(u64 *)arg4;
  /* SP-pop mode */
  arg1 = iSP;
  /* Adjust SP */
  iSP = arg4;
#ifdef TRACING
  goto begindologtest;
#endif

DoLogtestLP:
  if (_trace) printf("DoLogtestLP:\n");
#ifdef TRACING
  goto begindologtest;
#endif

DoLogtestFP:
  if (_trace) printf("DoLogtestFP:\n");

begindologtest:
  if (_trace) printf("begindologtest:\n");
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  t11 = *(u64 *)&(processor->niladdress);
  t7 = arg3 >> 12;
  t12 = *(u64 *)&(processor->taddress);
  /* Get ARG1 tag */
  arg3 = (u32)(arg6 >> ((4&7)*8));
  arg2 = *(s32 *)arg1;
  LDS(1, f1, *(u32 *)iSP );
  t7 = t7 & 1;
  /* t1 is tag of arg2 */
  t1 = *(s32 *)(arg1 + 4);
  arg4 = (u32)arg6;
  arg2 = (u32)arg2;
  LDS(2, f2, *(u32 *)arg1 );
  /* Strip off any CDR code bits. */
  t5 = arg3 & 63;
  /* Strip off any CDR code bits. */
  t4 = t1 & 63;
  t6 = (t5 == Type_Fixnum) ? 1 : 0;

g8020:
  if (_trace) printf("g8020:\n");
  if (t6 == 0)
    goto g8013;
  /* Here if argument TypeFixnum */
  t3 = (t4 == Type_Fixnum) ? 1 : 0;

g8017:
  if (_trace) printf("g8017:\n");
  if (t3 == 0)
    goto g8010;
  /* Here if argument TypeFixnum */
  t2 = arg4 & arg2;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  /* Pop/No-pop */
  iSP = (t7 * 8) + iSP;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* T if the test succeeds */
  if (t2)
    t11 = t12;
  *(u64 *)iSP = t11;
  goto cachevalid;

g8014:
  if (_trace) printf("g8014:\n");

g8013:
  if (_trace) printf("g8013:\n");
  /* Here for all other cases */

g8009:
  if (_trace) printf("g8009:\n");
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g8011;

g8010:
  if (_trace) printf("g8010:\n");
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;

g8011:
  if (_trace) printf("g8011:\n");

g8012:
  if (_trace) printf("g8012:\n");
#ifdef TRACING
  goto DoLogtestIM;
#endif

DoLogtestIM:
  if (_trace) printf("DoLogtestIM:\n");
  t11 = *(u64 *)&(processor->niladdress);
  /* First half of sign extension */
  arg2 = arg2 << 56;
  t12 = *(u64 *)&(processor->taddress);
  t7 = arg3 >> 12;
  arg3 = (u32)(arg6 >> ((4&7)*8));
  arg4 = (s32)arg6;
  /* Second half of sign extension */
  arg2 = (s64)arg2 >> 56;
  t7 = t7 & 1;
  /* Strip off any CDR code bits. */
  t3 = arg3 & 63;
  t4 = (t3 == Type_Fixnum) ? 1 : 0;

g8025:
  if (_trace) printf("g8025:\n");
  if (t4 == 0)
    goto g8022;
  /* Here if argument TypeFixnum */
  t2 = arg4 & arg2;
  iPC = *(u64 *)&(((CACHELINEP)iCP)->nextpcdata);
  iSP = (t7 * 8) + iSP;
  iCP = *(u64 *)&(((CACHELINEP)iCP)->nextcp);
  /* T if the test succeeds */
  if (t2)
    t11 = t12;
  *(u64 *)iSP = t11;
  goto cachevalid;

g8022:
  if (_trace) printf("g8022:\n");
  /* Here for all other cases */
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;

g8021:
  if (_trace) printf("g8021:\n");

/* end DoLogtest */
  /* End of Halfword operand from stack instruction - DoLogtest */
/* start EqualNumberMMExc */


equalnumbermmexc:
  if (_trace) printf("equalnumbermmexc:\n");
  /* Strip off any CDR code bits. */
  t5 = arg3 & 63;
  /* Strip off any CDR code bits. */
  t4 = t1 & 63;
  t6 = (t5 == Type_Fixnum) ? 1 : 0;

g8043:
  if (_trace) printf("g8043:\n");
  if (t6 == 0)
    goto g8031;
  /* Here if argument TypeFixnum */
  t3 = (t4 == Type_SingleFloat) ? 1 : 0;

g8035:
  if (_trace) printf("g8035:\n");
  if (t3 == 0)
    goto g8028;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQS(1, f1, f31, 1, f1);
  goto equalnumbermmexcfltflt;

g8032:
  if (_trace) printf("g8032:\n");

g8031:
  if (_trace) printf("g8031:\n");
  t6 = (t5 == Type_SingleFloat) ? 1 : 0;

g8044:
  if (_trace) printf("g8044:\n");
  if (t6 == 0)
    goto g8036;
  /* Here if argument TypeSingleFloat */
  t3 = (t4 == Type_Fixnum) ? 1 : 0;

g8040:
  if (_trace) printf("g8040:\n");
  if (t3 == 0)
    goto g8028;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQS(2, f2, f31, 2, f2);
  goto equalnumbermmexcfltflt;

g8037:
  if (_trace) printf("g8037:\n");

g8036:
  if (_trace) printf("g8036:\n");
  /* Here for all other cases */

g8027:
  if (_trace) printf("g8027:\n");
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g8029;

g8028:
  if (_trace) printf("g8028:\n");
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;

g8029:
  if (_trace) printf("g8029:\n");

g8030:
  if (_trace) printf("g8030:\n");

/* end EqualNumberMMExc */
/* start LesspMMExc */


lesspmmexc:
  if (_trace) printf("lesspmmexc:\n");
  /* Strip off any CDR code bits. */
  t5 = arg3 & 63;
  /* Strip off any CDR code bits. */
  t4 = t1 & 63;
  t6 = (t5 == Type_Fixnum) ? 1 : 0;

g8062:
  if (_trace) printf("g8062:\n");
  if (t6 == 0)
    goto g8050;
  /* Here if argument TypeFixnum */
  t3 = (t4 == Type_SingleFloat) ? 1 : 0;

g8054:
  if (_trace) printf("g8054:\n");
  if (t3 == 0)
    goto g8047;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQS(1, f1, f31, 1, f1);
  goto lesspmmexcfltflt;

g8051:
  if (_trace) printf("g8051:\n");

g8050:
  if (_trace) printf("g8050:\n");
  t6 = (t5 == Type_SingleFloat) ? 1 : 0;

g8063:
  if (_trace) printf("g8063:\n");
  if (t6 == 0)
    goto g8055;
  /* Here if argument TypeSingleFloat */
  t3 = (t4 == Type_Fixnum) ? 1 : 0;

g8059:
  if (_trace) printf("g8059:\n");
  if (t3 == 0)
    goto g8047;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQS(2, f2, f31, 2, f2);
  goto lesspmmexcfltflt;

g8056:
  if (_trace) printf("g8056:\n");

g8055:
  if (_trace) printf("g8055:\n");
  /* Here for all other cases */

g8046:
  if (_trace) printf("g8046:\n");
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g8048;

g8047:
  if (_trace) printf("g8047:\n");
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;

g8048:
  if (_trace) printf("g8048:\n");

g8049:
  if (_trace) printf("g8049:\n");

/* end LesspMMExc */
/* start GreaterpMMExc */


greaterpmmexc:
  if (_trace) printf("greaterpmmexc:\n");
  /* Strip off any CDR code bits. */
  t5 = arg3 & 63;
  /* Strip off any CDR code bits. */
  t4 = t1 & 63;
  t6 = (t5 == Type_Fixnum) ? 1 : 0;

g8081:
  if (_trace) printf("g8081:\n");
  if (t6 == 0)
    goto g8069;
  /* Here if argument TypeFixnum */
  t3 = (t4 == Type_SingleFloat) ? 1 : 0;

g8073:
  if (_trace) printf("g8073:\n");
  if (t3 == 0)
    goto g8066;
  /* Here if argument TypeSingleFloat */
  CVTLQ(1, f1, f31, 1, f1);
  CVTQS(1, f1, f31, 1, f1);
  goto greaterpmmexcfltflt;

g8070:
  if (_trace) printf("g8070:\n");

g8069:
  if (_trace) printf("g8069:\n");
  t6 = (t5 == Type_SingleFloat) ? 1 : 0;

g8082:
  if (_trace) printf("g8082:\n");
  if (t6 == 0)
    goto g8074;
  /* Here if argument TypeSingleFloat */
  t3 = (t4 == Type_Fixnum) ? 1 : 0;

g8078:
  if (_trace) printf("g8078:\n");
  if (t3 == 0)
    goto g8066;
  /* Here if argument TypeFixnum */
  CVTLQ(2, f2, f31, 2, f2);
  CVTQS(2, f2, f31, 2, f2);
  goto greaterpmmexcfltflt;

g8075:
  if (_trace) printf("g8075:\n");

g8074:
  if (_trace) printf("g8074:\n");
  /* Here for all other cases */

g8065:
  if (_trace) printf("g8065:\n");
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;
  goto g8067;

g8066:
  if (_trace) printf("g8066:\n");
  /* arg6 = tag to dispatch on */
  arg6 = t1;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 1;
  goto numericexception;

g8067:
  if (_trace) printf("g8067:\n");

g8068:
  if (_trace) printf("g8068:\n");

/* end GreaterpMMExc */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifunpred.as */
