/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * FROM ../alpha-emulator/ifunfull.as. ANY CHANGES MADE TO THIS FILE WILL BE LOST
 ************************************************************************/

  /* The full word instructions */
/* start DoIStageError */

  /* Fullword instruction - DoIStageError */
#ifdef TRACING
#endif

doistageerror:
  if (_trace) printf("doistageerror:\n");
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

/* end DoIStageError */
  /* End of Fullword instruction - DoIStageError */
/* start nullfw */

  /* Fullword instruction - nullfw */
#ifdef TRACING
#endif

nullfw:
  if (_trace) printf("nullfw:\n");
  arg5 = 0;
  arg2 = 47;
  goto illegaloperand;

/* end nullfw */
  /* End of Fullword instruction - nullfw */
/* start monitorforwardfw */

  /* Fullword instruction - monitorforwardfw */
#ifdef TRACING
#endif

monitorforwardfw:
  if (_trace) printf("monitorforwardfw:\n");
  arg5 = 0;
  arg2 = 46;
  goto illegaloperand;

/* end monitorforwardfw */
  /* End of Fullword instruction - monitorforwardfw */
/* start headerpfw */

  /* Fullword instruction - headerpfw */
#ifdef TRACING
#endif

headerpfw:
  if (_trace) printf("headerpfw:\n");
  arg5 = 0;
  arg2 = 44;
  goto illegaloperand;

/* end headerpfw */
  /* End of Fullword instruction - headerpfw */
/* start headerifw */

  /* Fullword instruction - headerifw */
#ifdef TRACING
#endif

headerifw:
  if (_trace) printf("headerifw:\n");
  arg5 = 0;
  arg2 = 43;
  goto illegaloperand;

/* end headerifw */
  /* End of Fullword instruction - headerifw */
/* start oneqforwardfw */

  /* Fullword instruction - oneqforwardfw */
#ifdef TRACING
#endif

oneqforwardfw:
  if (_trace) printf("oneqforwardfw:\n");
  arg5 = 0;
  arg2 = 48;
  goto illegaloperand;

/* end oneqforwardfw */
  /* End of Fullword instruction - oneqforwardfw */
/* start headerforwardfw */

  /* Fullword instruction - headerforwardfw */
#ifdef TRACING
#endif

headerforwardfw:
  if (_trace) printf("headerforwardfw:\n");
  arg5 = 0;
  arg2 = 42;
  goto illegaloperand;

/* end headerforwardfw */
  /* End of Fullword instruction - headerforwardfw */
/* start elementforwardfw */

  /* Fullword instruction - elementforwardfw */
#ifdef TRACING
#endif

elementforwardfw:
  if (_trace) printf("elementforwardfw:\n");
  arg5 = 0;
  arg2 = 40;
  goto illegaloperand;

/* end elementforwardfw */
  /* End of Fullword instruction - elementforwardfw */
/* start gcforwardfw */

  /* Fullword instruction - gcforwardfw */
#ifdef TRACING
#endif

gcforwardfw:
  if (_trace) printf("gcforwardfw:\n");
  arg5 = 0;
  arg2 = 41;
  goto illegaloperand;

/* end gcforwardfw */
  /* End of Fullword instruction - gcforwardfw */
/* start boundlocationfw */

  /* Fullword instruction - boundlocationfw */
#ifdef TRACING
#endif

boundlocationfw:
  if (_trace) printf("boundlocationfw:\n");
  arg5 = 0;
  arg2 = 39;
  goto illegaloperand;

/* end boundlocationfw */
  /* End of Fullword instruction - boundlocationfw */
/* start logicvariablefw */

  /* Fullword instruction - logicvariablefw */
#ifdef TRACING
#endif

logicvariablefw:
  if (_trace) printf("logicvariablefw:\n");
  arg5 = 0;
  arg2 = 45;
  goto illegaloperand;

/* end logicvariablefw */
  /* End of Fullword instruction - logicvariablefw */
/* start pushsparepointer3 */

  /* Fullword instruction - pushsparepointer3 */
#ifdef TRACING
#endif

pushsparepointer3:
  if (_trace) printf("pushsparepointer3:\n");
  /* Get operand */
  arg1 = *(u64 *)&(((CACHELINEP)iCP)->instruction);
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

/* end pushsparepointer3 */
  /* End of Fullword instruction - pushsparepointer3 */
/* start pushsparepointer4 */

  /* Fullword instruction - pushsparepointer4 */
#ifdef TRACING
#endif

pushsparepointer4:
  if (_trace) printf("pushsparepointer4:\n");
  /* Get operand */
  arg1 = *(u64 *)&(((CACHELINEP)iCP)->instruction);
  /* This instruction has not been written yet. */
  arg5 = 0;
  arg2 = 38;
  goto illegaloperand;

/* end pushsparepointer4 */
  /* End of Fullword instruction - pushsparepointer4 */
/* start callcompiledodd */

  /* Fullword instruction - callcompiledodd */
#ifdef TRACING
#endif

callcompiledodd:
  if (_trace) printf("callcompiledodd:\n");

callcompiledoddprefetch:
  if (_trace) printf("callcompiledoddprefetch:\n");
  /* Get operand */
  arg6 = arg3;
  arg5 = Type_OddPC;
  /* No extra arg */
  arg3 = zero;
  goto startcallcompiledmerge;

/* end callcompiledodd */
  /* End of Fullword instruction - callcompiledodd */
/* start nativeinstruction */

  /* Fullword instruction - nativeinstruction */
#ifdef TRACING
#endif

nativeinstruction:
  if (_trace) printf("nativeinstruction:\n");
  /* arg1 is instruction address*2 here */
  arg1 = iPC & ~1L;
  /* Select the DATA address */
  arg1 = arg1 + arg1;
  /* Add in the memory base */
  arg1 = (ivory * 4) + arg1;
  /* Jump into the Ivory code */
    r0 = (*( u64 (*)(u64, u64) )arg1)(arg1, arg2); /* jsr */

/* end nativeinstruction */
  /* End of Fullword instruction - nativeinstruction */
/* start resumeemulated */


resumeemulated:
  if (_trace) printf("resumeemulated:\n");
  arg2 = *(u64 *)&(((CACHELINEP)iCP)->annotation);
  iPC = (ivory * 4) - arg1;
  iPC = zero - iPC;
  iPC = iPC >> 1;
  if (arg2 != 0)
    goto interpretinstructionpredicted;
  goto interpretinstructionforbranch;

/* end resumeemulated */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifunfull.as */
