/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * FROM ../alpha-emulator/ifuntran.as. ANY CHANGES MADE TO THIS FILE WILL BE LOST
 ************************************************************************/

/* start NativeException */


nativeexception:
  if (_trace) printf("nativeexception:\n");
  /* Load linkage to escape block */
  t1 = *(u64 *)&(processor->linkage);
  /* Re-load resumemulator */
  r0 = *(u64 *)&(processor->resumeema);
  /* Restore SP (Just in case?) */
  iSP = *(u64 *)&(processor->restartsp);
  *(u64 *)&processor->linkage = zero;
  goto *t1; /* ret */

/* end NativeException */
/* start PadPastAref1 */


padpastaref1:
  if (_trace) printf("padpastaref1:\n");
  /* Load linkage to escape block */
  t1 = *(u64 *)&(processor->linkage);
  /* Re-load resumemulator */
  r0 = *(u64 *)&(processor->resumeema);
  /* Restore SP (Just in case?) */
  iSP = *(u64 *)&(processor->restartsp);
  *(u64 *)&processor->linkage = zero;
  /* Load linkage to escape block */
  t1 = *(u64 *)&(processor->linkage);
  /* Re-load resumemulator */
  r0 = *(u64 *)&(processor->resumeema);
  /* Restore SP (Just in case?) */
  iSP = *(u64 *)&(processor->restartsp);
  *(u64 *)&processor->linkage = zero;
  goto *t1; /* ret */

/* end PadPastAref1 */
/* start CarSubroutine */


carsubroutine:
  if (_trace) printf("carsubroutine:\n");
  sp = sp + -8;
  *(u64 *)&processor->linkage = r0;
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  r0 = r0 + 4;
  *(u64 *)&processor->restartsp = iSP;
  *(u64 *)sp = r0;
  r0 = (u64)&&return0093;
  goto carinternal;
return0093:
  r0 = *(u64 *)sp;
  *(u64 *)&processor->linkage = zero;
  sp = sp + 8;
  goto *r0; /* ret */

/* end CarSubroutine */
/* start CdrSubroutine */


cdrsubroutine:
  if (_trace) printf("cdrsubroutine:\n");
  sp = sp + -8;
  *(u64 *)&processor->linkage = r0;
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  r0 = r0 + 4;
  *(u64 *)&processor->restartsp = iSP;
  *(u64 *)sp = r0;
  r0 = (u64)&&return0094;
  goto cdrinternal;
return0094:
  r0 = *(u64 *)sp;
  *(u64 *)&processor->linkage = zero;
  sp = sp + 8;
  goto *r0; /* ret */

/* end CdrSubroutine */
/* start CarCdrSubroutine */


carcdrsubroutine:
  if (_trace) printf("carcdrsubroutine:\n");
  sp = sp + -8;
  *(u64 *)&processor->linkage = r0;
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  r0 = r0 + 4;
  *(u64 *)&processor->restartsp = iSP;
  *(u64 *)sp = r0;
  r0 = (u64)&&return0095;
  goto carcdrinternal;
return0095:
  r0 = *(u64 *)sp;
  *(u64 *)&processor->linkage = zero;
  sp = sp + 8;
  goto *r0; /* ret */

/* end CarCdrSubroutine */



/* End of file automatically generated from ../alpha-emulator/ifuntran.as */
