/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * FROM ../alpha-emulator/ifunhead.as. ANY CHANGES MADE TO THIS FILE WILL BE LOST
 ************************************************************************/

  /* Entry points into the interpretation loop. */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifunhead.as */
