/************************************************************************
 * WARNING: DO NOT EDIT THIS FILE.  THIS FILE WAS AUTOMATICALLY GENERATED
 * FROM ../alpha-emulator/ifunarra.as. ANY CHANGES MADE TO THIS FILE WILL BE LOST
 ************************************************************************/

  /* Array operations. */
/* start Aref1Regset */


aref1regset:
  if (_trace) printf("aref1regset:\n");
  t12 = arg4;
  /* Memory Read Internal */

g7682:
  /* Base of stack cache */
  t1 = *(u64 *)&(processor->stackcachebasevma);
  t3 = arg4 + ivory;
  t2 = *(s32 *)&processor->scovlimit;
  arg6 = (t3 * 4);
  arg5 = LDQ_U(t3);
  /* Stack cache offset */
  t1 = arg4 - t1;
  t4 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t1 < (u64)t2) ? 1 : 0;
  arg6 = *(s32 *)arg6;
  arg5 = (u8)(arg5 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7684;

g7683:
  t3 = zero + 64;
  t4 = t4 >> (arg5 & 63);
  t3 = t3 >> (arg5 & 63);
  arg6 = (u32)arg6;
  if (t4 & 1)
    goto g7686;

g7691:
  /* TagType. */
  t1 = arg5 & 63;
  t2 = arg6 >> (Array_LongPrefixBitPos & 63);
  t1 = t1 - Type_HeaderI;
  if (t1 != 0)
    goto aref1illegal;
  if (t2 & 1)
    goto aref1exception;
  /* store the array */
  *(u32 *)&((ARRAYCACHEP)t7)->array = t12;
  t2 = zero + Array_LengthMask;
  t1 = arg6 & t2;
  t2 = ((u64)arg2 < (u64)t1) ? 1 : 0;
  if (t2 == 0)
    goto aref1bounds;
  /* store the array length [implicit fixnum] */
  *(u64 *)&((ARRAYCACHEP)t7)->length = t1;
  t10 = arg6 >> (Array_RegisterBytePackingPos & 63);
  t8 = *(u64 *)&(processor->areventcount);
  t10 = t10 << (Array_RegisterBytePackingPos & 63);
  t9 = arg4 + 1;
  /* Construct the array register word */
  t10 = t10 + t8;
  /* store the array register word [implicit fixnum] */
  *(u32 *)&((ARRAYCACHEP)t7)->arword = t10;
  /* store the storage [implicit locative] */
  *(u64 *)&((ARRAYCACHEP)t7)->locat = t9;
  /* get BP into arg5 */
  arg5 = arg6 >> (Array_BytePackingPos & 63);
  /* get element type into arg6 */
  arg6 = arg6 >> (Array_ElementTypePos & 63);
  arg5 = arg5 & Array_BytePackingMask;
  arg4 = zero;
  arg6 = arg6 & Array_ElementTypeMask;
  goto aref1restart;

g7684:
  if (_trace) printf("g7684:\n");
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t1 = (t1 * 8) + t2;
  arg6 = *(s32 *)t1;
  /* Read from stack cache */
  arg5 = *(s32 *)(t1 + 4);
  goto g7683;

g7686:
  if (_trace) printf("g7686:\n");
  if ((t3 & 1) == 0)
    goto g7685;
  /* Do the indirect thing */
  arg4 = (u32)arg6;
  goto g7682;

g7685:
  if (_trace) printf("g7685:\n");
  /* Load the memory action table for cycle */
  t4 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = arg5 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg4;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t4;
  /* Get the memory action */
  t4 = *(s32 *)t3;

g7688:
  /* Perform memory action */
  arg1 = t4;
  arg2 = 6;
  goto performmemoryaction;

/* end Aref1Regset */
/* start Aref1RecomputeArrayRegister */


aref1recomputearrayregister:
  if (_trace) printf("aref1recomputearrayregister:\n");
  t5 = *(s32 *)(arg1 + -8);
  t4 = *(s32 *)(arg1 + -4);
  t5 = (u32)t5;
  t6 = t4 - Type_Array;
  /* Strip CDR code, low bits */
  t6 = t6 & 62;
  if (t6 != 0)
    goto g7693;
  /* Memory Read Internal */

g7695:
  /* Base of stack cache */
  t8 = *(u64 *)&(processor->stackcachebasevma);
  t3 = t5 + ivory;
  t2 = *(s32 *)&processor->scovlimit;
  t6 = (t3 * 4);
  t7 = LDQ_U(t3);
  /* Stack cache offset */
  t8 = t5 - t8;
  t1 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t8 < (u64)t2) ? 1 : 0;
  t6 = *(s32 *)t6;
  t7 = (u8)(t7 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7697;

g7696:
  t3 = zero + 64;
  t1 = t1 >> (t7 & 63);
  t3 = t3 >> (t7 & 63);
  t6 = (u32)t6;
  if (t1 & 1)
    goto g7699;

g7704:
  /* TagType. */
  t8 = t7 & 63;
  t2 = t6 >> (Array_LongPrefixBitPos & 63);
  t8 = t8 - Type_HeaderI;
  if (t8 != 0)
    goto g7692;
  if (t2 & 1)
    goto g7694;
  t1 = t6 >> (Array_BytePackingPos & 63);
  t4 = *(u64 *)&(processor->areventcount);
  t1 = t1 << (Array_RegisterBytePackingPos & 63);
  t2 = t5 + 1;
  /* Construct the array register word */
  t1 = t1 + t4;
  *(u32 *)(arg1 + 8) = t2;
  t3 = zero + Array_LengthMask;
  t3 = t6 & t3;
  *(u32 *)arg1 = t1;
  *(u32 *)(arg1 + 16) = t3;
  goto fastaref1retry;

g7694:
  if (_trace) printf("g7694:\n");
  /* Just a place to save these values */
  *(u64 *)&processor->asrf5 = arg1;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf4 = t10;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf3 = t11;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf6 = arg1;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf7 = arg2;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf8 = arg3;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf9 = arg4;
  t9 = *(s32 *)(arg1 + -8);
  arg2 = *(s32 *)(arg1 + -4);
  t9 = (u32)t9;
  arg1 = t5;
  t4 = t7;
  t3 = t6;
  t2 = 1;
  iSP = iSP + 24;
  r0 = (u64)&&return0068;
  goto setup1dlongarray;
return0068:
  t4 = (t2 == ReturnValue_Exception) ? 1 : 0;
  if (t4 != 0)
    goto g7693;
  /* Just a place to save these values */
  arg1 = *(u64 *)&(processor->asrf5);
  /* Just a place to save these values */
  t10 = *(u64 *)&(processor->asrf4);
  /* Just a place to save these values */
  t11 = *(u64 *)&(processor->asrf3);
  /* Just a place to save these values */
  arg1 = *(u64 *)&(processor->asrf6);
  /* Just a place to save these values */
  arg2 = *(u64 *)&(processor->asrf7);
  /* Just a place to save these values */
  arg3 = *(u64 *)&(processor->asrf8);
  /* Just a place to save these values */
  arg4 = *(u64 *)&(processor->asrf9);
  t3 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  t2 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  t1 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  t4 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  iSP = iSP - 24;
  *(u32 *)arg1 = t1;
  *(u32 *)(arg1 + 8) = t2;
  *(u32 *)(arg1 + 16) = t3;
  goto fastaref1retry;

g7693:
  if (_trace) printf("g7693:\n");
  /* arg6 = tag to dispatch on */
  arg6 = t4;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 12;
  goto arrayexception;

g7692:
  if (_trace) printf("g7692:\n");
  arg5 = 0;
  arg2 = 12;
  goto illegaloperand;

g7697:
  if (_trace) printf("g7697:\n");
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t8 = (t8 * 8) + t2;
  t6 = *(s32 *)t8;
  /* Read from stack cache */
  t7 = *(s32 *)(t8 + 4);
  goto g7696;

g7699:
  if (_trace) printf("g7699:\n");
  if ((t3 & 1) == 0)
    goto g7698;
  /* Do the indirect thing */
  t5 = (u32)t6;
  goto g7695;

g7698:
  if (_trace) printf("g7698:\n");
  /* Load the memory action table for cycle */
  t1 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = t7 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t5;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t1;
  /* Get the memory action */
  t1 = *(s32 *)t3;

g7701:
  /* Perform memory action */
  arg1 = t1;
  arg2 = 6;
  goto performmemoryaction;

/* end Aref1RecomputeArrayRegister */
/* start Aref1Exception */


aref1exception:
  if (_trace) printf("aref1exception:\n");
  /* Just a place to save these values */
  *(u64 *)&processor->asrf4 = arg2;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf5 = t7;
  t9 = t12;
  arg2 = arg3;
  arg1 = arg4;
  t4 = arg5;
  t3 = arg6;
  t2 = zero;
  iSP = iSP + 24;
  r0 = (u64)&&return0069;
  goto setup1dlongarray;
return0069:
  /* Just a place to save these values */
  arg2 = *(s32 *)&processor->asrf4;
  /* Just a place to save these values */
  t7 = *(u64 *)&(processor->asrf5);
  /* Length */
  t1 = *(s32 *)iSP;
  /* Length */
  t5 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t1 = (u32)t1;
  /* base */
  t5 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  /* control */
  t3 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  /* The original array */
  t9 = *(s32 *)iSP;
  /* The original array */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t9 = (u32)t9;
  iSP = iSP - 24;
  *(u64 *)&((ARRAYCACHEP)t7)->length = t1;
  *(u32 *)&((ARRAYCACHEP)t7)->arword = t3;
  *(u32 *)&((ARRAYCACHEP)t7)->locat = t5;
  /* store the array */
  *(u32 *)&((ARRAYCACHEP)t7)->array = t9;
  t9 = (u32)t5;
  t2 = (t2 == ReturnValue_Exception) ? 1 : 0;
  if (t2 != 0)
    goto reallyaref1exc;
  t5 = ((u64)arg2 < (u64)t1) ? 1 : 0;
  if (t5 == 0)
    goto aref1bounds;
  /* get BP into arg5 */
  arg5 = t3 >> (Array_BytePackingPos & 63);
  /* get element type into arg6 */
  arg6 = t3 >> (Array_ElementTypePos & 63);
  arg4 = t3 >> (Array_RegisterByteOffsetPos & 63);
  arg5 = arg5 & Array_BytePackingMask;
  arg4 = arg4 & Array_RegisterByteOffsetMask;
  arg6 = arg6 & Array_ElementTypeMask;
  goto aref1restart;

reallyaref1exc:
  if (_trace) printf("reallyaref1exc:\n");
  arg1 = Type_Fixnum;
  /* SetTag. */
  t1 = arg1 << 32;
  t1 = arg2 | t1;
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 8;
  goto arrayexception;

aref1illegal:
  if (_trace) printf("aref1illegal:\n");
  arg5 = 0;
  arg2 = 8;
  goto illegaloperand;

aref1bounds:
  if (_trace) printf("aref1bounds:\n");
  *(u64 *)&((ARRAYCACHEP)t7)->array = zero;
  arg5 = 0;
  arg2 = 74;
  goto illegaloperand;

/* end Aref1Exception */
/* start Aset1Regset */


aset1regset:
  if (_trace) printf("aset1regset:\n");
  t12 = arg4;
  /* Memory Read Internal */

g7705:
  /* Base of stack cache */
  t1 = *(u64 *)&(processor->stackcachebasevma);
  t3 = arg4 + ivory;
  t2 = *(s32 *)&processor->scovlimit;
  arg6 = (t3 * 4);
  arg5 = LDQ_U(t3);
  /* Stack cache offset */
  t1 = arg4 - t1;
  t4 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t1 < (u64)t2) ? 1 : 0;
  arg6 = *(s32 *)arg6;
  arg5 = (u8)(arg5 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7707;

g7706:
  t3 = zero + 64;
  t4 = t4 >> (arg5 & 63);
  t3 = t3 >> (arg5 & 63);
  arg6 = (u32)arg6;
  if (t4 & 1)
    goto g7709;

g7714:
  /* TagType. */
  t1 = arg5 & 63;
  t2 = arg6 >> (Array_LongPrefixBitPos & 63);
  t1 = t1 - Type_HeaderI;
  if (t1 != 0)
    goto aset1illegal;
  if (t2 & 1)
    goto aset1exception;
  /* store the array */
  *(u32 *)&((ARRAYCACHEP)t7)->array = t12;
  t2 = zero + Array_LengthMask;
  t1 = arg6 & t2;
  t2 = ((u64)arg2 < (u64)t1) ? 1 : 0;
  if (t2 == 0)
    goto aset1bounds;
  /* store the array length [implicit fixnum] */
  *(u64 *)&((ARRAYCACHEP)t7)->length = t1;
  t10 = arg6 >> (Array_RegisterBytePackingPos & 63);
  t8 = *(u64 *)&(processor->areventcount);
  t10 = t10 << (Array_RegisterBytePackingPos & 63);
  t9 = arg4 + 1;
  /* Construct the array register word */
  t10 = t10 + t8;
  /* store the array register word [implicit fixnum] */
  *(u32 *)&((ARRAYCACHEP)t7)->arword = t10;
  /* store the storage [implicit locative] */
  *(u64 *)&((ARRAYCACHEP)t7)->locat = t9;
  /* get BP into arg5 */
  arg5 = arg6 >> (Array_BytePackingPos & 63);
  /* get element type into arg6 */
  arg6 = arg6 >> (Array_ElementTypePos & 63);
  arg5 = arg5 & Array_BytePackingMask;
  arg4 = zero;
  arg6 = arg6 & Array_ElementTypeMask;
  goto aset1restart;

g7707:
  if (_trace) printf("g7707:\n");
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t1 = (t1 * 8) + t2;
  arg6 = *(s32 *)t1;
  /* Read from stack cache */
  arg5 = *(s32 *)(t1 + 4);
  goto g7706;

g7709:
  if (_trace) printf("g7709:\n");
  if ((t3 & 1) == 0)
    goto g7708;
  /* Do the indirect thing */
  arg4 = (u32)arg6;
  goto g7705;

g7708:
  if (_trace) printf("g7708:\n");
  /* Load the memory action table for cycle */
  t4 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = arg5 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg4;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t4;
  /* Get the memory action */
  t4 = *(s32 *)t3;

g7711:
  /* Perform memory action */
  arg1 = t4;
  arg2 = 6;
  goto performmemoryaction;

/* end Aset1Regset */
/* start Aset1RecomputeArrayRegister */


aset1recomputearrayregister:
  if (_trace) printf("aset1recomputearrayregister:\n");
  t5 = *(s32 *)(arg1 + -8);
  t4 = *(s32 *)(arg1 + -4);
  t5 = (u32)t5;
  t6 = t4 - Type_Array;
  /* Strip CDR code, low bits */
  t6 = t6 & 62;
  if (t6 != 0)
    goto g7716;
  /* Memory Read Internal */

g7718:
  /* Base of stack cache */
  t8 = *(u64 *)&(processor->stackcachebasevma);
  t3 = t5 + ivory;
  t2 = *(s32 *)&processor->scovlimit;
  t6 = (t3 * 4);
  t7 = LDQ_U(t3);
  /* Stack cache offset */
  t8 = t5 - t8;
  t1 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t8 < (u64)t2) ? 1 : 0;
  t6 = *(s32 *)t6;
  t7 = (u8)(t7 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7720;

g7719:
  t3 = zero + 64;
  t1 = t1 >> (t7 & 63);
  t3 = t3 >> (t7 & 63);
  t6 = (u32)t6;
  if (t1 & 1)
    goto g7722;

g7727:
  /* TagType. */
  t8 = t7 & 63;
  t2 = t6 >> (Array_LongPrefixBitPos & 63);
  t8 = t8 - Type_HeaderI;
  if (t8 != 0)
    goto g7715;
  if (t2 & 1)
    goto g7717;
  t1 = t6 >> (Array_BytePackingPos & 63);
  t4 = *(u64 *)&(processor->areventcount);
  t1 = t1 << (Array_RegisterBytePackingPos & 63);
  t2 = t5 + 1;
  /* Construct the array register word */
  t1 = t1 + t4;
  *(u32 *)(arg1 + 8) = t2;
  t3 = zero + Array_LengthMask;
  t3 = t6 & t3;
  *(u32 *)arg1 = t1;
  *(u32 *)(arg1 + 16) = t3;
  goto fastaset1retry;

g7717:
  if (_trace) printf("g7717:\n");
  /* Just a place to save these values */
  *(u64 *)&processor->asrf5 = arg1;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf4 = t10;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf3 = t11;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf6 = arg1;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf7 = arg2;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf8 = arg3;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf9 = arg4;
  t9 = *(s32 *)(arg1 + -8);
  arg2 = *(s32 *)(arg1 + -4);
  t9 = (u32)t9;
  arg1 = t5;
  t4 = t7;
  t3 = t6;
  t2 = 1;
  iSP = iSP + 24;
  r0 = (u64)&&return0070;
  goto setup1dlongarray;
return0070:
  t4 = (t2 == ReturnValue_Exception) ? 1 : 0;
  if (t4 != 0)
    goto g7716;
  /* Just a place to save these values */
  arg1 = *(u64 *)&(processor->asrf5);
  /* Just a place to save these values */
  t10 = *(u64 *)&(processor->asrf4);
  /* Just a place to save these values */
  t11 = *(u64 *)&(processor->asrf3);
  /* Just a place to save these values */
  arg1 = *(u64 *)&(processor->asrf6);
  /* Just a place to save these values */
  arg2 = *(u64 *)&(processor->asrf7);
  /* Just a place to save these values */
  arg3 = *(u64 *)&(processor->asrf8);
  /* Just a place to save these values */
  arg4 = *(u64 *)&(processor->asrf9);
  t3 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  t2 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  t1 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  t4 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  iSP = iSP - 24;
  *(u32 *)arg1 = t1;
  *(u32 *)(arg1 + 8) = t2;
  *(u32 *)(arg1 + 16) = t3;
  goto fastaset1retry;

g7716:
  if (_trace) printf("g7716:\n");
  /* arg6 = tag to dispatch on */
  arg6 = t4;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 3;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 12;
  goto arrayexception;

g7715:
  if (_trace) printf("g7715:\n");
  arg5 = 0;
  arg2 = 12;
  goto illegaloperand;

g7720:
  if (_trace) printf("g7720:\n");
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t8 = (t8 * 8) + t2;
  t6 = *(s32 *)t8;
  /* Read from stack cache */
  t7 = *(s32 *)(t8 + 4);
  goto g7719;

g7722:
  if (_trace) printf("g7722:\n");
  if ((t3 & 1) == 0)
    goto g7721;
  /* Do the indirect thing */
  t5 = (u32)t6;
  goto g7718;

g7721:
  if (_trace) printf("g7721:\n");
  /* Load the memory action table for cycle */
  t1 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = t7 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t5;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t1;
  /* Get the memory action */
  t1 = *(s32 *)t3;

g7724:
  /* Perform memory action */
  arg1 = t1;
  arg2 = 6;
  goto performmemoryaction;

/* end Aset1RecomputeArrayRegister */
/* start Aset1Exception */


aset1exception:
  if (_trace) printf("aset1exception:\n");
  /* Just a place to save these values */
  *(u64 *)&processor->asrf4 = arg2;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf3 = t5;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf6 = t6;
  /* Just a place to save these values */
  *(u64 *)&processor->asrf5 = t7;
  t9 = t12;
  arg2 = arg3;
  arg1 = arg4;
  t4 = arg5;
  t3 = arg6;
  t2 = zero;
  iSP = iSP + 24;
  r0 = (u64)&&return0071;
  goto setup1dlongarray;
return0071:
  t1 = (t2 == ReturnValue_Exception) ? 1 : 0;
  if (t1 != 0)
    goto reallyaset1exc;
  /* Just a place to save these values */
  arg2 = *(s32 *)&processor->asrf4;
  /* Just a place to save these values */
  t5 = *(u64 *)&(processor->asrf3);
  /* Just a place to save these values */
  t6 = *(u64 *)&(processor->asrf6);
  /* Just a place to save these values */
  t7 = *(u64 *)&(processor->asrf5);
  /* Length */
  t1 = *(s32 *)iSP;
  /* Length */
  t2 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t1 = (u32)t1;
  /* base */
  t2 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  /* control */
  t3 = *(u64 *)iSP;
  /* Pop Stack. */
  iSP = iSP - 8;
  /* The original array */
  t9 = *(s32 *)iSP;
  /* The original array */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t9 = (u32)t9;
  iSP = iSP - 24;
  *(u64 *)&((ARRAYCACHEP)t7)->length = t1;
  *(u32 *)&((ARRAYCACHEP)t7)->arword = t3;
  *(u32 *)&((ARRAYCACHEP)t7)->locat = t2;
  /* store the array */
  *(u32 *)&((ARRAYCACHEP)t7)->array = t9;
  t9 = (u32)t2;
  t2 = ((u64)arg2 < (u64)t1) ? 1 : 0;
  if (t2 == 0)
    goto aset1bounds;
  /* get BP into arg5 */
  arg5 = t3 >> (Array_BytePackingPos & 63);
  /* get element type into arg6 */
  arg6 = t3 >> (Array_ElementTypePos & 63);
  arg4 = t3 >> (Array_RegisterByteOffsetPos & 63);
  arg5 = arg5 & Array_BytePackingMask;
  arg4 = arg4 & Array_RegisterByteOffsetMask;
  arg6 = arg6 & Array_ElementTypeMask;
  goto aset1restart;

reallyaset1exc:
  if (_trace) printf("reallyaset1exc:\n");
  arg1 = Type_Fixnum;
  /* SetTag. */
  t1 = arg1 << 32;
  t1 = arg2 | t1;
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 3;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 9;
  goto arrayexception;

aset1illegal:
  if (_trace) printf("aset1illegal:\n");
  arg5 = 0;
  arg2 = 9;
  goto illegaloperand;

aset1bounds:
  if (_trace) printf("aset1bounds:\n");
  *(u64 *)&((ARRAYCACHEP)t7)->array = zero;
  arg5 = 0;
  arg2 = 74;
  goto illegaloperand;

/* end Aset1Exception */
/* start DoAloc1 */

  /* Halfword operand from stack instruction - DoAloc1 */
  /* arg2 has the preloaded 8 bit operand. */

doaloc1:
  if (_trace) printf("doaloc1:\n");
#ifdef TRACING
#endif

DoAloc1SP:
  if (_trace) printf("DoAloc1SP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdoaloc1;
#endif

DoAloc1LP:
  if (_trace) printf("DoAloc1LP:\n");
#ifdef TRACING
  goto headdoaloc1;
#endif

DoAloc1FP:
  if (_trace) printf("DoAloc1FP:\n");

headdoaloc1:
  if (_trace) printf("headdoaloc1:\n");
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindoaloc1:
  if (_trace) printf("begindoaloc1:\n");
  /* arg1 has the operand, not sign extended if immediate. */
  /* Get the array tag/data */
  arg4 = *(s32 *)iSP;
  /* Get the array tag/data */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  /* Index Data */
  arg2 = (u32)arg1;
  /* Index Tag */
  arg1 = arg1 >> 32;
  t1 = arg1 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto aloc1illegal;

aloc1merge:
  if (_trace) printf("aloc1merge:\n");
  t1 = arg3 - Type_Array;
  /* Strip CDR code, low bits */
  t1 = t1 & 62;
  if (t1 != 0)
    goto aloc1exception;
  /* Memory Read Internal */

g7728:
  /* Base of stack cache */
  t1 = *(u64 *)&(processor->stackcachebasevma);
  t3 = arg4 + ivory;
  t2 = *(s32 *)&processor->scovlimit;
  arg6 = (t3 * 4);
  arg5 = LDQ_U(t3);
  /* Stack cache offset */
  t1 = arg4 - t1;
  t4 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t1 < (u64)t2) ? 1 : 0;
  arg6 = *(s32 *)arg6;
  arg5 = (u8)(arg5 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7730;

g7729:
  t3 = zero + 64;
  t4 = t4 >> (arg5 & 63);
  t3 = t3 >> (arg5 & 63);
  if (t4 & 1)
    goto g7732;

g7737:
  /* TagType. */
  t1 = arg5 & 63;
  t2 = arg6 >> (Array_LongPrefixBitPos & 63);
  t1 = t1 - Type_HeaderI;
  if (t1 != 0)
    goto aloc1illegal;
  if (t2 & 1)
    goto aloc1exception;
  t2 = zero + Array_LengthMask;
  t1 = arg6 & t2;
  t3 = ((u64)arg2 < (u64)t1) ? 1 : 0;
  if (t3 == 0)
    goto aloc1illegal;
  /* get element type into arg6 */
  arg6 = arg6 >> (Array_ElementTypePos & 63);
  arg4 = arg4 + 1;
  arg4 = arg4 + arg2;
  arg6 = arg6 & Array_ElementTypeMask;
  arg6 = arg6 - Array_ElementTypeObject;
  if (arg6 != 0)
    goto aloc1notobject;
  t1 = Type_Locative;
  *(u32 *)(iSP + 8) = arg4;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t1;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

aloc1exception:
  if (_trace) printf("aloc1exception:\n");
  arg1 = Type_Fixnum;
  /* SetTag. */
  t1 = arg1 << 32;
  t1 = arg2 | t1;
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 8;
  goto arrayexception;

aloc1illegal:
  if (_trace) printf("aloc1illegal:\n");
  arg5 = 0;
  arg2 = 8;
  goto illegaloperand;

aloc1bounds:
  if (_trace) printf("aloc1bounds:\n");
  arg5 = 0;
  arg2 = 74;
  goto illegaloperand;

aloc1notobject:
  if (_trace) printf("aloc1notobject:\n");
  arg5 = 0;
  arg2 = 7;
  goto illegaloperand;
#ifdef TRACING
  goto DoAloc1IM;
#endif

DoAloc1IM:
  if (_trace) printf("DoAloc1IM:\n");
  /* Get the array tag/data */
  arg4 = *(s32 *)iSP;
  /* Get the array tag/data */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  goto aloc1merge;

g7730:
  if (_trace) printf("g7730:\n");
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t1 = (t1 * 8) + t2;
  arg6 = *(s32 *)t1;
  /* Read from stack cache */
  arg5 = *(s32 *)(t1 + 4);
  goto g7729;

g7732:
  if (_trace) printf("g7732:\n");
  if ((t3 & 1) == 0)
    goto g7731;
  /* Do the indirect thing */
  arg4 = (u32)arg6;
  goto g7728;

g7731:
  if (_trace) printf("g7731:\n");
  /* Load the memory action table for cycle */
  t4 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = arg5 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg4;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t4;
  /* Get the memory action */
  t4 = *(s32 *)t3;

g7734:
  /* Perform memory action */
  arg1 = t4;
  arg2 = 6;
  goto performmemoryaction;

/* end DoAloc1 */
  /* End of Halfword operand from stack instruction - DoAloc1 */
  /* Array register operations. */
/* start DoSetup1DArray */

  /* Halfword operand from stack instruction - DoSetup1DArray */

dosetup1darray:
  if (_trace) printf("dosetup1darray:\n");
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoSetup1DArrayIM:
  if (_trace) printf("DoSetup1DArrayIM:\n");
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg2 = arg2 << 56;

g7751:
  if (_trace) printf("g7751:\n");
  /* Rest of sign extension */
  arg2 = (s64)arg2 >> 56;
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);
  goto begindosetup1darray;
#ifdef TRACING
#endif

DoSetup1DArraySP:
  if (_trace) printf("DoSetup1DArraySP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdosetup1darray;
#endif

DoSetup1DArrayLP:
  if (_trace) printf("DoSetup1DArrayLP:\n");
#ifdef TRACING
  goto headdosetup1darray;
#endif

DoSetup1DArrayFP:
  if (_trace) printf("DoSetup1DArrayFP:\n");

headdosetup1darray:
  if (_trace) printf("headdosetup1darray:\n");
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindosetup1darray:
  if (_trace) printf("begindosetup1darray:\n");
  /* arg1 has the operand, sign extended if immediate. */
  /* Get the tag */
  arg2 = arg1 >> 32;
  /* and the data */
  arg1 = (u32)arg1;
  /* Indicate not forcing 1d */
  t2 = 0;
  t9 = arg1;
  t3 = arg2 - Type_Array;
  /* Strip CDR code, low bits */
  t3 = t3 & 62;
  if (t3 != 0)
    goto g7739;
  /* Memory Read Internal */

g7741:
  /* Base of stack cache */
  t5 = *(u64 *)&(processor->stackcachebasevma);
  t7 = arg1 + ivory;
  t6 = *(s32 *)&processor->scovlimit;
  t3 = (t7 * 4);
  t4 = LDQ_U(t7);
  /* Stack cache offset */
  t5 = arg1 - t5;
  t8 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t6 = ((u64)t5 < (u64)t6) ? 1 : 0;
  t3 = *(s32 *)t3;
  t4 = (u8)(t4 >> ((t7&7)*8));
  if (t6 != 0)
    goto g7743;

g7742:
  t7 = zero + 64;
  t8 = t8 >> (t4 & 63);
  t7 = t7 >> (t4 & 63);
  t3 = (u32)t3;
  if (t8 & 1)
    goto g7745;

g7750:
  /* TagType. */
  t5 = t4 & 63;
  t6 = t3 >> (Array_LongPrefixBitPos & 63);
  t5 = t5 - Type_HeaderI;
  if (t5 != 0)
    goto g7738;
  if (t6 & 1)
    goto g7740;
  /* set CDR-NEXT */
  t5 = arg2 & 63;
  *(u32 *)(iSP + 8) = t9;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t5;
  iSP = iSP + 8;
  t8 = t3 >> (Array_RegisterBytePackingPos & 63);
  t7 = Type_Fixnum;
  t1 = *(u64 *)&(processor->areventcount);
  t8 = t8 << (Array_RegisterBytePackingPos & 63);
  t5 = arg1 + 1;
  /* Construct the array register word */
  t8 = t8 + t1;
  /* set CDR-NEXT */
  t6 = t7 & 63;
  *(u32 *)(iSP + 8) = t8;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t6;
  iSP = iSP + 8;
  t8 = Type_Locative;
  *(u32 *)(iSP + 8) = t5;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  t6 = zero + Array_LengthMask;
  t6 = t3 & t6;
  /* set CDR-NEXT */
  t8 = t7 & 63;
  *(u32 *)(iSP + 8) = t6;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

g7739:
  if (_trace) printf("g7739:\n");
  /* SetTag. */
  t6 = arg2 << 32;
  t6 = t9 | t6;
  /* arg6 = tag to dispatch on */
  arg6 = arg2;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 1;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 71;
  goto arrayexception;

g7738:
  if (_trace) printf("g7738:\n");
  arg5 = 0;
  arg2 = 71;
  goto illegaloperand;

g7740:
  if (_trace) printf("g7740:\n");
  r0 = (u64)&&return0072;
  goto setup1dlongarray;
return0072:
  t1 = (t2 == ReturnValue_Normal) ? 1 : 0;
  if (t1 != 0)
    goto NEXTINSTRUCTION;
  t1 = (t2 == ReturnValue_Exception) ? 1 : 0;
  if (t1 != 0)
    goto g7739;
  t1 = (t2 == ReturnValue_IllegalOperand) ? 1 : 0;
  if (t1 != 0)
    goto g7738;
  goto NEXTINSTRUCTION;

g7743:
  if (_trace) printf("g7743:\n");
  t6 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t5 = (t5 * 8) + t6;
  t3 = *(s32 *)t5;
  /* Read from stack cache */
  t4 = *(s32 *)(t5 + 4);
  goto g7742;

g7745:
  if (_trace) printf("g7745:\n");
  if ((t7 & 1) == 0)
    goto g7744;
  /* Do the indirect thing */
  arg1 = (u32)t3;
  goto g7741;

g7744:
  if (_trace) printf("g7744:\n");
  /* Load the memory action table for cycle */
  t8 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t7 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t7 = (t7 * 4) + t8;
  /* Get the memory action */
  t8 = *(s32 *)t7;

g7747:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 6;
  goto performmemoryaction;

/* end DoSetup1DArray */
  /* End of Halfword operand from stack instruction - DoSetup1DArray */
/* start DoSetupForce1DArray */

  /* Halfword operand from stack instruction - DoSetupForce1DArray */

dosetupforce1darray:
  if (_trace) printf("dosetupforce1darray:\n");
  /* arg2 has the preloaded 8 bit operand. */
#ifdef TRACING
#endif

DoSetupForce1DArrayIM:
  if (_trace) printf("DoSetupForce1DArrayIM:\n");
  /* This sequence only sucks a moderate amount */
  /* sign extend the byte argument. */
  arg2 = arg2 << 56;

g7765:
  if (_trace) printf("g7765:\n");
  /* Rest of sign extension */
  arg2 = (s64)arg2 >> 56;
  *(u32 *)&processor->immediate_arg = arg2;
  arg1 = *(u64 *)&(processor->immediate_arg);
  goto begindosetupforce1darray;
#ifdef TRACING
#endif

DoSetupForce1DArraySP:
  if (_trace) printf("DoSetupForce1DArraySP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdosetupforce1darray;
#endif

DoSetupForce1DArrayLP:
  if (_trace) printf("DoSetupForce1DArrayLP:\n");
#ifdef TRACING
  goto headdosetupforce1darray;
#endif

DoSetupForce1DArrayFP:
  if (_trace) printf("DoSetupForce1DArrayFP:\n");

headdosetupforce1darray:
  if (_trace) printf("headdosetupforce1darray:\n");
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindosetupforce1darray:
  if (_trace) printf("begindosetupforce1darray:\n");
  /* arg1 has the operand, sign extended if immediate. */
  /* Get the tag */
  arg2 = arg1 >> 32;
  /* and the data */
  arg1 = (u32)arg1;
  /* Indicate forcing 1d */
  t2 = 1;
  t9 = arg1;
  t3 = arg2 - Type_Array;
  /* Strip CDR code, low bits */
  t3 = t3 & 62;
  if (t3 != 0)
    goto g7753;
  /* Memory Read Internal */

g7755:
  /* Base of stack cache */
  t5 = *(u64 *)&(processor->stackcachebasevma);
  t7 = arg1 + ivory;
  t6 = *(s32 *)&processor->scovlimit;
  t3 = (t7 * 4);
  t4 = LDQ_U(t7);
  /* Stack cache offset */
  t5 = arg1 - t5;
  t8 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t6 = ((u64)t5 < (u64)t6) ? 1 : 0;
  t3 = *(s32 *)t3;
  t4 = (u8)(t4 >> ((t7&7)*8));
  if (t6 != 0)
    goto g7757;

g7756:
  t7 = zero + 64;
  t8 = t8 >> (t4 & 63);
  t7 = t7 >> (t4 & 63);
  t3 = (u32)t3;
  if (t8 & 1)
    goto g7759;

g7764:
  /* TagType. */
  t5 = t4 & 63;
  t6 = t3 >> (Array_LongPrefixBitPos & 63);
  t5 = t5 - Type_HeaderI;
  if (t5 != 0)
    goto g7752;
  if (t6 & 1)
    goto g7754;
  /* set CDR-NEXT */
  t5 = arg2 & 63;
  *(u32 *)(iSP + 8) = t9;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t5;
  iSP = iSP + 8;
  t8 = t3 >> (Array_RegisterBytePackingPos & 63);
  t7 = Type_Fixnum;
  t1 = *(u64 *)&(processor->areventcount);
  t8 = t8 << (Array_RegisterBytePackingPos & 63);
  t5 = arg1 + 1;
  /* Construct the array register word */
  t8 = t8 + t1;
  /* set CDR-NEXT */
  t6 = t7 & 63;
  *(u32 *)(iSP + 8) = t8;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t6;
  iSP = iSP + 8;
  t8 = Type_Locative;
  *(u32 *)(iSP + 8) = t5;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  t6 = zero + Array_LengthMask;
  t6 = t3 & t6;
  /* set CDR-NEXT */
  t8 = t7 & 63;
  *(u32 *)(iSP + 8) = t6;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

g7753:
  if (_trace) printf("g7753:\n");
  /* SetTag. */
  t6 = arg2 << 32;
  t6 = t9 | t6;
  /* arg6 = tag to dispatch on */
  arg6 = arg2;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 1;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 71;
  goto arrayexception;

g7752:
  if (_trace) printf("g7752:\n");
  arg5 = 0;
  arg2 = 71;
  goto illegaloperand;

g7754:
  if (_trace) printf("g7754:\n");
  r0 = (u64)&&return0073;
  goto setup1dlongarray;
return0073:
  t1 = (t2 == ReturnValue_Normal) ? 1 : 0;
  if (t1 != 0)
    goto NEXTINSTRUCTION;
  t1 = (t2 == ReturnValue_Exception) ? 1 : 0;
  if (t1 != 0)
    goto g7753;
  t1 = (t2 == ReturnValue_IllegalOperand) ? 1 : 0;
  if (t1 != 0)
    goto g7752;
  goto NEXTINSTRUCTION;

g7757:
  if (_trace) printf("g7757:\n");
  t6 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t5 = (t5 * 8) + t6;
  t3 = *(s32 *)t5;
  /* Read from stack cache */
  t4 = *(s32 *)(t5 + 4);
  goto g7756;

g7759:
  if (_trace) printf("g7759:\n");
  if ((t7 & 1) == 0)
    goto g7758;
  /* Do the indirect thing */
  arg1 = (u32)t3;
  goto g7755;

g7758:
  if (_trace) printf("g7758:\n");
  /* Load the memory action table for cycle */
  t8 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t7 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg1;
  /* Adjust for a longword load */
  t7 = (t7 * 4) + t8;
  /* Get the memory action */
  t8 = *(s32 *)t7;

g7761:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 6;
  goto performmemoryaction;

/* end DoSetupForce1DArray */
  /* End of Halfword operand from stack instruction - DoSetupForce1DArray */
/* start Setup1DLongArray */


setup1dlongarray:
  if (_trace) printf("setup1dlongarray:\n");
  /* Read data from the header: alength offset indirect lengths&mults */
  /* length=array+1 */
  t1 = arg1 + 1;
  /* Memory Read Internal */

g7775:
  /* Base of stack cache */
  t7 = *(u64 *)&(processor->stackcachebasevma);
  t10 = t1 + ivory;
  t8 = *(s32 *)&processor->scovlimit;
  arg4 = (t10 * 4);
  t6 = LDQ_U(t10);
  /* Stack cache offset */
  t7 = t1 - t7;
  t11 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)t8) ? 1 : 0;
  arg4 = *(s32 *)arg4;
  t6 = (u8)(t6 >> ((t10&7)*8));
  if (t8 != 0)
    goto g7777;

g7776:
  t10 = zero + 240;
  t11 = t11 >> (t6 & 63);
  t10 = t10 >> (t6 & 63);
  arg4 = (u32)arg4;
  if (t11 & 1)
    goto g7779;

g7786:
  t8 = t6 - Type_Fixnum;
  /* Strip CDR code */
  t8 = t8 & 63;
  if (t8 != 0)
    goto g7766;
  /* Offset is adata+2 */
  t1 = t1 + 1;
  /* Memory Read Internal */

g7787:
  /* Base of stack cache */
  t7 = *(u64 *)&(processor->stackcachebasevma);
  t10 = t1 + ivory;
  t8 = *(s32 *)&processor->scovlimit;
  arg3 = (t10 * 4);
  t6 = LDQ_U(t10);
  /* Stack cache offset */
  t7 = t1 - t7;
  t11 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)t8) ? 1 : 0;
  arg3 = *(s32 *)arg3;
  t6 = (u8)(t6 >> ((t10&7)*8));
  if (t8 != 0)
    goto g7789;

g7788:
  t10 = zero + 240;
  t11 = t11 >> (t6 & 63);
  t10 = t10 >> (t6 & 63);
  arg3 = (u32)arg3;
  if (t11 & 1)
    goto g7791;

g7798:
  t8 = t6 - Type_Fixnum;
  /* Strip CDR code */
  t8 = t8 & 63;
  if (t8 != 0)
    goto g7766;
  /* Indirect is adata+3 */
  t1 = t1 + 1;
  /* Memory Read Internal */

g7799:
  /* Base of stack cache */
  t7 = *(u64 *)&(processor->stackcachebasevma);
  t10 = t1 + ivory;
  t8 = *(s32 *)&processor->scovlimit;
  t5 = (t10 * 4);
  t6 = LDQ_U(t10);
  /* Stack cache offset */
  t7 = t1 - t7;
  t11 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)t8) ? 1 : 0;
  t5 = *(s32 *)t5;
  t6 = (u8)(t6 >> ((t10&7)*8));
  if (t8 != 0)
    goto g7801;

g7800:
  t10 = zero + 240;
  t11 = t11 >> (t6 & 63);
  t10 = t10 >> (t6 & 63);
  t5 = (u32)t5;
  if (t11 & 1)
    goto g7803;

g7810:
  /* Strip off any CDR code bits. */
  t10 = t6 & 63;
  t11 = (t10 == Type_Locative) ? 1 : 0;

g7875:
  if (_trace) printf("g7875:\n");
  if (t11 == 0)
    goto g7812;
  /* Here if argument TypeLocative */

g7769:
  if (_trace) printf("g7769:\n");
  /* set CDR-NEXT */
  t10 = arg2 & 63;
  *(u32 *)(iSP + 8) = t9;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t10;
  iSP = iSP + 8;
  t8 = t3 >> (Array_BytePackingPos & 63);
  t7 = Type_Fixnum;
  t1 = *(u64 *)&(processor->areventcount);
  t8 = t8 << (Array_RegisterBytePackingPos & 63);
  /* Construct the array register word */
  t8 = t8 + t1;
  /* set CDR-NEXT */
  t6 = t7 & 63;
  *(u32 *)(iSP + 8) = t8;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t6;
  iSP = iSP + 8;
  t8 = Type_Locative;
  *(u32 *)(iSP + 8) = t5;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  /* set CDR-NEXT */
  t8 = t7 & 63;
  *(u32 *)(iSP + 8) = arg4;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto g7774;

g7812:
  if (_trace) printf("g7812:\n");
  t11 = (t10 == Type_Fixnum) ? 1 : 0;

g7876:
  if (_trace) printf("g7876:\n");
  if (t11 == 0)
    goto g7813;
  /* Here if argument TypeFixnum */
  goto g7769;

g7813:
  if (_trace) printf("g7813:\n");
  t11 = (t10 == Type_Array) ? 1 : 0;

g7877:
  if (_trace) printf("g7877:\n");
  if (t11 == 0)
    goto g7814;
  /* Here if argument TypeArray */

g7773:
  if (_trace) printf("g7773:\n");
  t1 = t3 & 7;
  t1 = (t1 == 1) ? 1 : 0;
  /* Force true if FORCE */
  t1 = t1 | t2;
  if (t1 == 0)
    goto g7766;
  t12 = t3 >> (Array_BytePackingPos & 63);
  t12 = t12 & Array_BytePackingMask;
  t2 = arg3;

g7768:
  if (_trace) printf("g7768:\n");
  /* Memory Read Internal */

g7815:
  /* Base of stack cache */
  t7 = *(u64 *)&(processor->stackcachebasevma);
  t10 = t5 + ivory;
  t8 = *(s32 *)&processor->scovlimit;
  t4 = (t10 * 4);
  t6 = LDQ_U(t10);
  /* Stack cache offset */
  t7 = t5 - t7;
  t11 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)t8) ? 1 : 0;
  t4 = *(s32 *)t4;
  t6 = (u8)(t6 >> ((t10&7)*8));
  if (t8 != 0)
    goto g7817;

g7816:
  t10 = zero + 64;
  t11 = t11 >> (t6 & 63);
  t10 = t10 >> (t6 & 63);
  t4 = (u32)t4;
  if (t11 & 1)
    goto g7819;

g7824:
  t10 = t4 >> (Array_BytePackingPos & 63);
  t10 = t10 & Array_BytePackingMask;
  arg1 = t12 - t10;
  t7 = t4 >> (Array_LongPrefixBitPos & 63);
  if (t7 & 1)
    goto g7770;
  /* increment beyond header */
  t5 = t5 + 1;
  t8 = zero + 32767;
  t8 = t4 & t8;
  t10 = zero - arg1;
  t10 = t8 >> (t10 & 63);
  t8 = t8 << (arg1 & 63);
  if ((s64)arg1 <= 0)
    t8 = t10;
  t10 = arg4 + arg3;
  t7 = t10 - t8;
  if ((s64)t7 <= 0)
    t8 = t10;
  arg4 = t8;

g7767:
  if (_trace) printf("g7767:\n");
  arg4 = arg4 - t2;
  /* set CDR-NEXT */
  t10 = arg2 & 63;
  *(u32 *)(iSP + 8) = t9;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t10;
  iSP = iSP + 8;
  t7 = Type_Fixnum;
  t8 = t3 >> (Array_RegisterBytePackingPos & 63);
  t1 = *(u64 *)&(processor->areventcount);
  t8 = t8 << (Array_RegisterBytePackingPos & 63);
  /* -1 */
  t11 = zero - 1;
  /* (LSH -1 byte-packing) */
  t11 = t11 << (t12 & 63);
  t11 = t2 & ~t11;
  t11 = t11 << (Array_RegisterByteOffsetPos & 63);
  /* Construct the array register word */
  t8 = t8 + t1;
  /* Add in the byte offset */
  t8 = t11 + t8;
  /* set CDR-NEXT */
  t6 = t7 & 63;
  *(u32 *)(iSP + 8) = t8;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t6;
  iSP = iSP + 8;
  if ((s64)arg4 <= 0)
    arg4 = zero;
  if (arg4 == 0)
    goto g7771;
  t1 = zero - t12;
  t1 = t2 << (t1 & 63);
  t2 = t2 >> (t12 & 63);
  if ((s64)t12 <= 0)
    t2 = t1;
  t5 = t2 + t5;

g7771:
  if (_trace) printf("g7771:\n");
  t8 = Type_Locative;
  *(u32 *)(iSP + 8) = t5;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  /* set CDR-NEXT */
  t8 = t7 & 63;
  *(u32 *)(iSP + 8) = arg4;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t8;
  iSP = iSP + 8;
  goto g7774;

g7770:
  if (_trace) printf("g7770:\n");
  /* length=array+1 */
  t1 = t5 + 1;
  /* Memory Read Internal */

g7825:
  /* Base of stack cache */
  t7 = *(u64 *)&(processor->stackcachebasevma);
  t10 = t1 + ivory;
  t8 = *(s32 *)&processor->scovlimit;
  arg6 = (t10 * 4);
  t4 = LDQ_U(t10);
  /* Stack cache offset */
  t7 = t1 - t7;
  t11 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)t8) ? 1 : 0;
  arg6 = *(s32 *)arg6;
  t4 = (u8)(t4 >> ((t10&7)*8));
  if (t8 != 0)
    goto g7827;

g7826:
  t10 = zero + 240;
  t11 = t11 >> (t4 & 63);
  t10 = t10 >> (t4 & 63);
  arg6 = (u32)arg6;
  if (t11 & 1)
    goto g7829;

g7836:
  t1 = t4 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto g7766;
  /* offset=array+2 */
  t1 = t5 + 2;
  /* Memory Read Internal */

g7837:
  /* Base of stack cache */
  t7 = *(u64 *)&(processor->stackcachebasevma);
  t10 = t1 + ivory;
  t8 = *(s32 *)&processor->scovlimit;
  arg5 = (t10 * 4);
  t4 = LDQ_U(t10);
  /* Stack cache offset */
  t7 = t1 - t7;
  t11 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)t8) ? 1 : 0;
  arg5 = *(s32 *)arg5;
  t4 = (u8)(t4 >> ((t10&7)*8));
  if (t8 != 0)
    goto g7839;

g7838:
  t10 = zero + 240;
  t11 = t11 >> (t4 & 63);
  t10 = t10 >> (t4 & 63);
  arg5 = (u32)arg5;
  if (t11 & 1)
    goto g7841;

g7848:
  t1 = t4 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto g7766;
  /* next=array+3 */
  t1 = t5 + 3;
  /* Memory Read Internal */

g7849:
  /* Base of stack cache */
  t7 = *(u64 *)&(processor->stackcachebasevma);
  t10 = t1 + ivory;
  t8 = *(s32 *)&processor->scovlimit;
  t5 = (t10 * 4);
  t4 = LDQ_U(t10);
  /* Stack cache offset */
  t7 = t1 - t7;
  t11 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t8 = ((u64)t7 < (u64)t8) ? 1 : 0;
  t5 = *(s32 *)t5;
  t4 = (u8)(t4 >> ((t10&7)*8));
  if (t8 != 0)
    goto g7851;

g7850:
  t10 = zero + 240;
  t11 = t11 >> (t4 & 63);
  t10 = t10 >> (t4 & 63);
  t5 = (u32)t5;
  if (t11 & 1)
    goto g7853;

g7860:
  t8 = zero - arg1;
  t8 = arg6 >> (t8 & 63);
  t10 = arg6 << (arg1 & 63);
  if ((s64)arg1 <= 0)
    t10 = t8;
  t8 = arg4 + arg3;
  if ((s64)t10 <= 0)
    t10 = t8;
  t7 = t10 - t8;
  if ((s64)t7 <= 0)
    t8 = t10;
  arg4 = t8;
  /* Strip off any CDR code bits. */
  t8 = t4 & 63;
  t10 = (t8 == Type_Locative) ? 1 : 0;

g7868:
  if (_trace) printf("g7868:\n");
  if (t10 == 0)
    goto g7862;
  /* Here if argument TypeLocative */
  goto g7767;

g7862:
  if (_trace) printf("g7862:\n");
  t10 = (t8 == Type_Fixnum) ? 1 : 0;

g7869:
  if (_trace) printf("g7869:\n");
  if (t10 == 0)
    goto g7863;
  /* Here if argument TypeFixnum */
  goto g7767;

g7863:
  if (_trace) printf("g7863:\n");
  t10 = (t8 == Type_Array) ? 1 : 0;

g7870:
  if (_trace) printf("g7870:\n");
  if (t10 == 0)
    goto g7864;
  /* Here if argument TypeArray */

g7772:
  if (_trace) printf("g7772:\n");
  t7 = zero - arg1;
  t7 = arg5 >> (t7 & 63);
  arg3 = arg5 << (arg1 & 63);
  if ((s64)arg1 <= 0)
    arg3 = t7;
  t2 = t2 + arg3;
  goto g7768;

g7864:
  if (_trace) printf("g7864:\n");
  t10 = (t8 == Type_String) ? 1 : 0;

g7871:
  if (_trace) printf("g7871:\n");
  if (t10 == 0)
    goto g7865;
  /* Here if argument TypeString */
  goto g7772;

g7865:
  if (_trace) printf("g7865:\n");
  /* Here for all other cases */
  goto g7766;

g7861:
  if (_trace) printf("g7861:\n");

g7814:
  if (_trace) printf("g7814:\n");
  t11 = (t10 == Type_String) ? 1 : 0;

g7878:
  if (_trace) printf("g7878:\n");
  if (t11 == 0)
    goto g7872;
  /* Here if argument TypeString */
  goto g7773;

g7872:
  if (_trace) printf("g7872:\n");
  /* Here for all other cases */
  goto g7766;

g7811:
  if (_trace) printf("g7811:\n");

g7766:
  if (_trace) printf("g7766:\n");
  t2 = ReturnValue_Exception;
  goto *r0; /* ret */

g7774:
  if (_trace) printf("g7774:\n");
  t2 = ReturnValue_Normal;
  goto *r0; /* ret */

g7851:
  if (_trace) printf("g7851:\n");
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  t5 = *(s32 *)t7;
  /* Read from stack cache */
  t4 = *(s32 *)(t7 + 4);
  goto g7850;

g7853:
  if (_trace) printf("g7853:\n");
  if ((t10 & 1) == 0)
    goto g7852;
  /* Do the indirect thing */
  t1 = (u32)t5;
  goto g7849;

g7852:
  if (_trace) printf("g7852:\n");
  /* Load the memory action table for cycle */
  t11 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t10 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t10 = (t10 * 4) + t11;
  /* Get the memory action */
  t11 = *(s32 *)t10;

g7857:
  if (_trace) printf("g7857:\n");
  t10 = t11 & MemoryActionTransform;
  if (t10 == 0)
    goto g7856;
  t4 = t4 & ~63L;
  t4 = t4 | Type_ExternalValueCellPointer;
  goto g7860;
#ifndef MINIMA

g7856:
#endif
#ifdef MINIMA

g7856:
  if (_trace) printf("g7856:\n");
  t10 = t11 & MemoryActionBinding;
  t8 = *(u64 *)&(processor->dbcmask);
  if (t10 == 0)
    goto g7855;
  t7 = t1 << 1;
  t10 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t7 = t7 & t8;
  t8 = 1;
  t8 = t8 << (ivorymemorydata & 63);
  t7 = (s32)t7 + (s32)t10;
  /* Clear sign-extension */
  t7 = (u32)t7;
  t8 = (t7 * 4) + t8;
  /* Fetch the key */
  t7 = *(s32 *)t8;
  /* Fetch value */
  t5 = *(s32 *)(t8 + 4);
  /* Compare */
  t10 = (s32)t1 - (s32)t7;
  /* Trap on miss */
  if (t10 != 0)
    goto g7859;
  /* Extract the pointer, and indirect */
  t1 = (u32)t5;
  goto g7849;

g7859:
  if (_trace) printf("g7859:\n");
  goto dbcachemisstrap;
#endif

g7855:
  /* Perform memory action */
  arg1 = t11;
  arg2 = 0;
  goto performmemoryaction;

g7839:
  if (_trace) printf("g7839:\n");
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  arg5 = *(s32 *)t7;
  /* Read from stack cache */
  t4 = *(s32 *)(t7 + 4);
  goto g7838;

g7841:
  if (_trace) printf("g7841:\n");
  if ((t10 & 1) == 0)
    goto g7840;
  /* Do the indirect thing */
  t1 = (u32)arg5;
  goto g7837;

g7840:
  if (_trace) printf("g7840:\n");
  /* Load the memory action table for cycle */
  t11 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t10 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t10 = (t10 * 4) + t11;
  /* Get the memory action */
  t11 = *(s32 *)t10;

g7845:
  if (_trace) printf("g7845:\n");
  t10 = t11 & MemoryActionTransform;
  if (t10 == 0)
    goto g7844;
  t4 = t4 & ~63L;
  t4 = t4 | Type_ExternalValueCellPointer;
  goto g7848;
#ifndef MINIMA

g7844:
#endif
#ifdef MINIMA

g7844:
  if (_trace) printf("g7844:\n");
  t10 = t11 & MemoryActionBinding;
  t8 = *(u64 *)&(processor->dbcmask);
  if (t10 == 0)
    goto g7843;
  t7 = t1 << 1;
  t10 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t7 = t7 & t8;
  t8 = 1;
  t8 = t8 << (ivorymemorydata & 63);
  t7 = (s32)t7 + (s32)t10;
  /* Clear sign-extension */
  t7 = (u32)t7;
  t8 = (t7 * 4) + t8;
  /* Fetch the key */
  t7 = *(s32 *)t8;
  /* Fetch value */
  arg5 = *(s32 *)(t8 + 4);
  /* Compare */
  t10 = (s32)t1 - (s32)t7;
  /* Trap on miss */
  if (t10 != 0)
    goto g7847;
  /* Extract the pointer, and indirect */
  t1 = (u32)arg5;
  goto g7837;

g7847:
  if (_trace) printf("g7847:\n");
  goto dbcachemisstrap;
#endif

g7843:
  /* Perform memory action */
  arg1 = t11;
  arg2 = 0;
  goto performmemoryaction;

g7827:
  if (_trace) printf("g7827:\n");
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  arg6 = *(s32 *)t7;
  /* Read from stack cache */
  t4 = *(s32 *)(t7 + 4);
  goto g7826;

g7829:
  if (_trace) printf("g7829:\n");
  if ((t10 & 1) == 0)
    goto g7828;
  /* Do the indirect thing */
  t1 = (u32)arg6;
  goto g7825;

g7828:
  if (_trace) printf("g7828:\n");
  /* Load the memory action table for cycle */
  t11 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t10 = t4 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t10 = (t10 * 4) + t11;
  /* Get the memory action */
  t11 = *(s32 *)t10;

g7833:
  if (_trace) printf("g7833:\n");
  t10 = t11 & MemoryActionTransform;
  if (t10 == 0)
    goto g7832;
  t4 = t4 & ~63L;
  t4 = t4 | Type_ExternalValueCellPointer;
  goto g7836;
#ifndef MINIMA

g7832:
#endif
#ifdef MINIMA

g7832:
  if (_trace) printf("g7832:\n");
  t10 = t11 & MemoryActionBinding;
  t8 = *(u64 *)&(processor->dbcmask);
  if (t10 == 0)
    goto g7831;
  t7 = t1 << 1;
  t10 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t7 = t7 & t8;
  t8 = 1;
  t8 = t8 << (ivorymemorydata & 63);
  t7 = (s32)t7 + (s32)t10;
  /* Clear sign-extension */
  t7 = (u32)t7;
  t8 = (t7 * 4) + t8;
  /* Fetch the key */
  t7 = *(s32 *)t8;
  /* Fetch value */
  arg6 = *(s32 *)(t8 + 4);
  /* Compare */
  t10 = (s32)t1 - (s32)t7;
  /* Trap on miss */
  if (t10 != 0)
    goto g7835;
  /* Extract the pointer, and indirect */
  t1 = (u32)arg6;
  goto g7825;

g7835:
  if (_trace) printf("g7835:\n");
  goto dbcachemisstrap;
#endif

g7831:
  /* Perform memory action */
  arg1 = t11;
  arg2 = 0;
  goto performmemoryaction;

g7817:
  if (_trace) printf("g7817:\n");
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  t4 = *(s32 *)t7;
  /* Read from stack cache */
  t6 = *(s32 *)(t7 + 4);
  goto g7816;

g7819:
  if (_trace) printf("g7819:\n");
  if ((t10 & 1) == 0)
    goto g7818;
  /* Do the indirect thing */
  t5 = (u32)t4;
  goto g7815;

g7818:
  if (_trace) printf("g7818:\n");
  /* Load the memory action table for cycle */
  t11 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t10 = t6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t5;
  /* Adjust for a longword load */
  t10 = (t10 * 4) + t11;
  /* Get the memory action */
  t11 = *(s32 *)t10;

g7821:
  /* Perform memory action */
  arg1 = t11;
  arg2 = 6;
  goto performmemoryaction;

g7801:
  if (_trace) printf("g7801:\n");
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  t5 = *(s32 *)t7;
  /* Read from stack cache */
  t6 = *(s32 *)(t7 + 4);
  goto g7800;

g7803:
  if (_trace) printf("g7803:\n");
  if ((t10 & 1) == 0)
    goto g7802;
  /* Do the indirect thing */
  t1 = (u32)t5;
  goto g7799;

g7802:
  if (_trace) printf("g7802:\n");
  /* Load the memory action table for cycle */
  t11 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t10 = t6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t10 = (t10 * 4) + t11;
  /* Get the memory action */
  t11 = *(s32 *)t10;

g7807:
  if (_trace) printf("g7807:\n");
  t10 = t11 & MemoryActionTransform;
  if (t10 == 0)
    goto g7806;
  t6 = t6 & ~63L;
  t6 = t6 | Type_ExternalValueCellPointer;
  goto g7810;
#ifndef MINIMA

g7806:
#endif
#ifdef MINIMA

g7806:
  if (_trace) printf("g7806:\n");
  t10 = t11 & MemoryActionBinding;
  t8 = *(u64 *)&(processor->dbcmask);
  if (t10 == 0)
    goto g7805;
  t7 = t1 << 1;
  t10 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t7 = t7 & t8;
  t8 = 1;
  t8 = t8 << (ivorymemorydata & 63);
  t7 = (s32)t7 + (s32)t10;
  /* Clear sign-extension */
  t7 = (u32)t7;
  t8 = (t7 * 4) + t8;
  /* Fetch the key */
  t7 = *(s32 *)t8;
  /* Fetch value */
  t5 = *(s32 *)(t8 + 4);
  /* Compare */
  t10 = (s32)t1 - (s32)t7;
  /* Trap on miss */
  if (t10 != 0)
    goto g7809;
  /* Extract the pointer, and indirect */
  t1 = (u32)t5;
  goto g7799;

g7809:
  if (_trace) printf("g7809:\n");
  goto dbcachemisstrap;
#endif

g7805:
  /* Perform memory action */
  arg1 = t11;
  arg2 = 0;
  goto performmemoryaction;

g7789:
  if (_trace) printf("g7789:\n");
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  arg3 = *(s32 *)t7;
  /* Read from stack cache */
  t6 = *(s32 *)(t7 + 4);
  goto g7788;

g7791:
  if (_trace) printf("g7791:\n");
  if ((t10 & 1) == 0)
    goto g7790;
  /* Do the indirect thing */
  t1 = (u32)arg3;
  goto g7787;

g7790:
  if (_trace) printf("g7790:\n");
  /* Load the memory action table for cycle */
  t11 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t10 = t6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t10 = (t10 * 4) + t11;
  /* Get the memory action */
  t11 = *(s32 *)t10;

g7795:
  if (_trace) printf("g7795:\n");
  t10 = t11 & MemoryActionTransform;
  if (t10 == 0)
    goto g7794;
  t6 = t6 & ~63L;
  t6 = t6 | Type_ExternalValueCellPointer;
  goto g7798;
#ifndef MINIMA

g7794:
#endif
#ifdef MINIMA

g7794:
  if (_trace) printf("g7794:\n");
  t10 = t11 & MemoryActionBinding;
  t8 = *(u64 *)&(processor->dbcmask);
  if (t10 == 0)
    goto g7793;
  t7 = t1 << 1;
  t10 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t7 = t7 & t8;
  t8 = 1;
  t8 = t8 << (ivorymemorydata & 63);
  t7 = (s32)t7 + (s32)t10;
  /* Clear sign-extension */
  t7 = (u32)t7;
  t8 = (t7 * 4) + t8;
  /* Fetch the key */
  t7 = *(s32 *)t8;
  /* Fetch value */
  arg3 = *(s32 *)(t8 + 4);
  /* Compare */
  t10 = (s32)t1 - (s32)t7;
  /* Trap on miss */
  if (t10 != 0)
    goto g7797;
  /* Extract the pointer, and indirect */
  t1 = (u32)arg3;
  goto g7787;

g7797:
  if (_trace) printf("g7797:\n");
  goto dbcachemisstrap;
#endif

g7793:
  /* Perform memory action */
  arg1 = t11;
  arg2 = 0;
  goto performmemoryaction;

g7777:
  if (_trace) printf("g7777:\n");
  t8 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t7 = (t7 * 8) + t8;
  arg4 = *(s32 *)t7;
  /* Read from stack cache */
  t6 = *(s32 *)(t7 + 4);
  goto g7776;

g7779:
  if (_trace) printf("g7779:\n");
  if ((t10 & 1) == 0)
    goto g7778;
  /* Do the indirect thing */
  t1 = (u32)arg4;
  goto g7775;

g7778:
  if (_trace) printf("g7778:\n");
  /* Load the memory action table for cycle */
  t11 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t10 = t6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t10 = (t10 * 4) + t11;
  /* Get the memory action */
  t11 = *(s32 *)t10;

g7783:
  if (_trace) printf("g7783:\n");
  t10 = t11 & MemoryActionTransform;
  if (t10 == 0)
    goto g7782;
  t6 = t6 & ~63L;
  t6 = t6 | Type_ExternalValueCellPointer;
  goto g7786;
#ifndef MINIMA

g7782:
#endif
#ifdef MINIMA

g7782:
  if (_trace) printf("g7782:\n");
  t10 = t11 & MemoryActionBinding;
  t8 = *(u64 *)&(processor->dbcmask);
  if (t10 == 0)
    goto g7781;
  t7 = t1 << 1;
  t10 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t7 = t7 & t8;
  t8 = 1;
  t8 = t8 << (ivorymemorydata & 63);
  t7 = (s32)t7 + (s32)t10;
  /* Clear sign-extension */
  t7 = (u32)t7;
  t8 = (t7 * 4) + t8;
  /* Fetch the key */
  t7 = *(s32 *)t8;
  /* Fetch value */
  arg4 = *(s32 *)(t8 + 4);
  /* Compare */
  t10 = (s32)t1 - (s32)t7;
  /* Trap on miss */
  if (t10 != 0)
    goto g7785;
  /* Extract the pointer, and indirect */
  t1 = (u32)arg4;
  goto g7775;

g7785:
  if (_trace) printf("g7785:\n");
  goto dbcachemisstrap;
#endif

g7781:
  /* Perform memory action */
  arg1 = t11;
  arg2 = 0;
  goto performmemoryaction;

/* end Setup1DLongArray */
/* start DoFastAset1 */

  /* Halfword operand from stack instruction - DoFastAset1 */
  /* arg2 has the preloaded 8 bit operand. */

dofastaset1:
  if (_trace) printf("dofastaset1:\n");
#ifdef TRACING
#endif

DoFastAset1SP:
  if (_trace) printf("DoFastAset1SP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto begindofastaset1;
#endif

DoFastAset1LP:
  if (_trace) printf("DoFastAset1LP:\n");
#ifdef TRACING
  goto begindofastaset1;
#endif

DoFastAset1FP:
  if (_trace) printf("DoFastAset1FP:\n");

begindofastaset1:
  if (_trace) printf("begindofastaset1:\n");
  /* arg1 has the operand address. */
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Index */
  arg4 = *(s32 *)iSP;
  /* Index */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  /* value */
  t11 = *(s32 *)iSP;
  /* value */
  t10 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t11 = (u32)t11;
  t1 = arg3 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto fastaset1iop;

fastaset1retry:
  if (_trace) printf("fastaset1retry:\n");
  arg6 = *(s32 *)arg1;
  t9 = *(s32 *)(arg1 + 8);
  t3 = *(s32 *)(arg1 + 16);
  arg6 = (u32)arg6;
  t9 = (u32)t9;
  t5 = arg6 << 42;
  t3 = (u32)t3;
  t4 = *(u64 *)&(processor->areventcount);
  t5 = t5 >> 42;
  t2 = ((u64)arg4 < (u64)t3) ? 1 : 0;
  if (t2 == 0)
    goto fastaset1bounds;
  t6 = t4 - t5;
  if (t6 != 0)
    goto aset1recomputearrayregister;
  t6 = arg6 >> (Array_RegisterBytePackingPos & 63);
  t7 = arg6 >> (Array_RegisterByteOffsetPos & 63);
  t8 = arg6 >> (Array_RegisterElementTypePos & 63);
  t6 = t6 & Array_RegisterBytePackingMask;
  t7 = t7 & Array_RegisterByteOffsetMask;
  t8 = t8 & Array_RegisterElementTypeMask;
  /* Element checking and foreplay. */
  /* TagType. */
  t1 = t10 & 63;
  t12 = (t8 == Array_ElementTypeCharacter) ? 1 : 0;

g7889:
  if (_trace) printf("g7889:\n");
  if (t12 == 0)
    goto g7885;
  /* Here if argument ArrayElementTypeCharacter */
  t2 = t1 - Type_Character;
  if (t2 == 0)
    goto g7880;
  arg5 = 0;
  arg2 = 29;
  goto illegaloperand;

g7880:
  if (_trace) printf("g7880:\n");
  /* Certainly will fit if not packed! */
  if (t6 == 0)
    goto g7879;
  t2 = 32;
  /* Compute size of byte */
  t2 = t2 >> (t6 & 63);
  t1 = ~zero;
  t1 = t1 << (t2 & 63);
  /* Compute mask for byte */
  t1 = ~t1;
  t1 = t11 & t1;
  t1 = t11 - t1;
  /* J. if character fits. */
  if (t1 == 0)
    goto g7879;
  arg5 = 0;
  arg2 = 62;
  goto illegaloperand;

g7885:
  if (_trace) printf("g7885:\n");
  t12 = (t8 == Array_ElementTypeFixnum) ? 1 : 0;

g7890:
  if (_trace) printf("g7890:\n");
  if (t12 == 0)
    goto g7886;
  /* Here if argument ArrayElementTypeFixnum */
  t2 = t1 - Type_Fixnum;
  if (t2 == 0)
    goto g7879;
  arg5 = 0;
  arg2 = 33;
  goto illegaloperand;

g7886:
  if (_trace) printf("g7886:\n");
  t12 = (t8 == Array_ElementTypeBoolean) ? 1 : 0;

g7891:
  if (_trace) printf("g7891:\n");
  if (t12 == 0)
    goto g7884;
  /* Here if argument ArrayElementTypeBoolean */
  t11 = 1;
  t1 = t1 - Type_NIL;
  /* J. if True */
  if (t1 != 0)
    goto g7879;
  t11 = zero;
  goto g7879;

g7884:
  if (_trace) printf("g7884:\n");
  /* Shove it in. */

g7879:
  if (_trace) printf("g7879:\n");
  /* J. if packed */
  if (t6 != 0)
    goto g7881;
  t1 = t8 - Array_ElementTypeObject;
  if (t1 != 0)
    goto g7881;
  /* Here for the simple non packed case */
  t1 = t9 + arg4;
  /* Memory Read Internal */

g7892:
  /* Base of stack cache */
  t4 = *(u64 *)&(processor->stackcachebasevma);
  t12 = t1 + ivory;
  t5 = *(s32 *)&processor->scovlimit;
  t3 = (t12 * 4);
  t2 = LDQ_U(t12);
  /* Stack cache offset */
  t4 = t1 - t4;
  arg3 = *(u64 *)&(processor->datawrite_mask);
  /* In range? */
  t5 = ((u64)t4 < (u64)t5) ? 1 : 0;
  t3 = *(s32 *)t3;
  t2 = (u8)(t2 >> ((t12&7)*8));
  if (t5 != 0)
    goto g7894;

g7893:
  t12 = zero + 240;
  arg3 = arg3 >> (t2 & 63);
  t12 = t12 >> (t2 & 63);
  if (arg3 & 1)
    goto g7896;

g7902:
  /* Merge cdr-code */
  t3 = t10 & 63;
  t2 = t2 & 192;
  t2 = t2 | t3;
  t5 = *(u64 *)&(processor->stackcachebasevma);
  t4 = t1 + ivory;
  arg3 = *(s32 *)&processor->scovlimit;
  t3 = (t4 * 4);
  t12 = LDQ_U(t4);
  /* Stack cache offset */
  t5 = t1 - t5;
  /* In range? */
  arg3 = ((u64)t5 < (u64)arg3) ? 1 : 0;
  t5 = (t2 & 0xff) << ((t4&7)*8);
  t12 = t12 & ~(0xffL << (t4&7)*8);

g7904:
  if (_trace) printf("g7904:\n");
  t12 = t12 | t5;
  STQ_U(t4, t12);
  *(u32 *)t3 = t11;
  /* J. if in cache */
  if (arg3 != 0)
    goto g7903;
  goto NEXTINSTRUCTION;
  goto NEXTINSTRUCTION;
  /* Here for the slow packed version */

g7881:
  if (_trace) printf("g7881:\n");
  arg4 = t7 + arg4;
  /* Convert byte index to word index */
  t1 = arg4 >> (t6 & 63);
  /* Address of word containing byte */
  t1 = t1 + t9;
  /* Memory Read Internal */

g7905:
  /* Base of stack cache */
  t2 = *(u64 *)&(processor->stackcachebasevma);
  t4 = t1 + ivory;
  t3 = *(s32 *)&processor->scovlimit;
  t9 = (t4 * 4);
  arg5 = LDQ_U(t4);
  /* Stack cache offset */
  t2 = t1 - t2;
  t5 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t3 = ((u64)t2 < (u64)t3) ? 1 : 0;
  t9 = *(s32 *)t9;
  arg5 = (u8)(arg5 >> ((t4&7)*8));
  if (t3 != 0)
    goto g7907;

g7906:
  t4 = zero + 240;
  t5 = t5 >> (arg5 & 63);
  t4 = t4 >> (arg5 & 63);
  t9 = (u32)t9;
  if (t5 & 1)
    goto g7909;

g7916:
  /* Check fixnum element type */
  /* TagType. */
  t2 = arg5 & 63;
  t2 = t2 - Type_Fixnum;
  /* J. if element type not fixnum. */
  if (t2 != 0)
    goto g7882;
  /* J. if unpacked fixnum element type. */
  if (t6 == 0)
    goto g7883;
  t12 = ~zero;
  t12 = t12 << (t6 & 63);
  t2 = zero - t6;
  /* Compute subword index */
  t12 = arg4 & ~t12;
  t2 = t2 + 5;
  /* Compute shift to get byte */
  t2 = t12 << (t2 & 63);
  t12 = 32;
  /* Compute size of byte */
  t12 = t12 >> (t6 & 63);
  t3 = ~zero;
  t3 = t3 << (t12 & 63);
  /* Compute mask for byte */
  t4 = ~t3;
  /* inserting into the low byte is easy */
  if (t2 == 0)
    goto g7917;
  /* Inserting the byte into any byte other than the low byte */
  t5 = 64;
  /* = the left shift rotate amount */
  t12 = t5 - t2;
  /* shift selected byte into low end of word. */
  t5 = t9 >> (t2 & 63);
  /* rotate low bits into high end of word. */
  t9 = t9 << (t12 & 63);
  /* Remove unwanted bits */
  t5 = t3 & t5;
  /* rotate low bits back into place. */
  t9 = t9 >> (t12 & 63);
  /* Strip any extra bits from element */
  t12 = t11 & t4;
  /* Insert new bits. */
  t5 = t12 | t5;
  /* reposition bits */
  t5 = t5 << (t2 & 63);
  /* Replace low order bits */
  t9 = t9 | t5;
  goto g7918;

g7917:
  if (_trace) printf("g7917:\n");
  /* Inserting the byte into the low byte */
  /* Remove the old low byte */
  t9 = t9 & t3;
  /* Remove unwanted bits from the new byte */
  t12 = t11 & t4;
  /* Insert the new byte in place of the old byte */
  t9 = t9 | t12;

g7918:
  if (_trace) printf("g7918:\n");
  t11 = t9;

g7883:
  if (_trace) printf("g7883:\n");
  t3 = *(u64 *)&(processor->stackcachebasevma);
  t2 = t1 + ivory;
  t12 = *(s32 *)&processor->scovlimit;
  t5 = (t2 * 4);
  t4 = LDQ_U(t2);
  /* Stack cache offset */
  t3 = t1 - t3;
  /* In range? */
  t12 = ((u64)t3 < (u64)t12) ? 1 : 0;
  t3 = (arg5 & 0xff) << ((t2&7)*8);
  t4 = t4 & ~(0xffL << (t2&7)*8);

g7920:
  if (_trace) printf("g7920:\n");
  t4 = t4 | t3;
  STQ_U(t2, t4);
  *(u32 *)t5 = t11;
  /* J. if in cache */
  if (t12 != 0)
    goto g7919;
  goto NEXTINSTRUCTION;
  goto NEXTINSTRUCTION;

g7882:
  if (_trace) printf("g7882:\n");
  arg5 = t1;
  arg2 = 25;
  goto illegaloperand;

fastaset1iop:
  if (_trace) printf("fastaset1iop:\n");
  arg5 = 0;
  arg2 = 32;
  goto illegaloperand;

fastaset1bounds:
  if (_trace) printf("fastaset1bounds:\n");
  arg5 = 0;
  arg2 = 13;
  goto illegaloperand;

g7919:
  if (_trace) printf("g7919:\n");
  t3 = *(u64 *)&(processor->stackcachebasevma);

g7921:
  if (_trace) printf("g7921:\n");
  t2 = *(u64 *)&(processor->stackcachedata);
  /* Stack cache offset */
  t3 = t1 - t3;
  /* reconstruct SCA */
  t2 = (t3 * 8) + t2;
  /* Store in stack */
  *(u32 *)t2 = t11;
  /* write the stack cache */
  *(u32 *)(t2 + 4) = arg5;
  goto NEXTINSTRUCTION;

g7907:
  if (_trace) printf("g7907:\n");
  t3 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t2 = (t2 * 8) + t3;
  t9 = *(s32 *)t2;
  /* Read from stack cache */
  arg5 = *(s32 *)(t2 + 4);
  goto g7906;

g7909:
  if (_trace) printf("g7909:\n");
  if ((t4 & 1) == 0)
    goto g7908;
  /* Do the indirect thing */
  t1 = (u32)t9;
  goto g7905;

g7908:
  if (_trace) printf("g7908:\n");
  /* Load the memory action table for cycle */
  t5 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t4 = arg5 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t4 = (t4 * 4) + t5;
  /* Get the memory action */
  t5 = *(s32 *)t4;

g7913:
  if (_trace) printf("g7913:\n");
  t4 = t5 & MemoryActionTransform;
  if (t4 == 0)
    goto g7912;
  arg5 = arg5 & ~63L;
  arg5 = arg5 | Type_ExternalValueCellPointer;
  goto g7916;
#ifndef MINIMA

g7912:
#endif
#ifdef MINIMA

g7912:
  if (_trace) printf("g7912:\n");
  t4 = t5 & MemoryActionBinding;
  t3 = *(u64 *)&(processor->dbcmask);
  if (t4 == 0)
    goto g7911;
  t2 = t1 << 1;
  t4 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t2 = t2 & t3;
  t3 = 1;
  t3 = t3 << (ivorymemorydata & 63);
  t2 = (s32)t2 + (s32)t4;
  /* Clear sign-extension */
  t2 = (u32)t2;
  t3 = (t2 * 4) + t3;
  /* Fetch the key */
  t2 = *(s32 *)t3;
  /* Fetch value */
  t9 = *(s32 *)(t3 + 4);
  /* Compare */
  t4 = (s32)t1 - (s32)t2;
  /* Trap on miss */
  if (t4 != 0)
    goto g7915;
  /* Extract the pointer, and indirect */
  t1 = (u32)t9;
  goto g7905;

g7915:
  if (_trace) printf("g7915:\n");
  goto dbcachemisstrap;
#endif

g7911:
  /* Perform memory action */
  arg1 = t5;
  arg2 = 0;
  goto performmemoryaction;

g7903:
  if (_trace) printf("g7903:\n");
  t5 = *(u64 *)&(processor->stackcachebasevma);

g7922:
  if (_trace) printf("g7922:\n");
  t4 = *(u64 *)&(processor->stackcachedata);
  /* Stack cache offset */
  t5 = t1 - t5;
  /* reconstruct SCA */
  t4 = (t5 * 8) + t4;
  /* Store in stack */
  *(u32 *)t4 = t11;
  /* write the stack cache */
  *(u32 *)(t4 + 4) = t2;
  goto NEXTINSTRUCTION;

g7894:
  if (_trace) printf("g7894:\n");
  t5 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t4 = (t4 * 8) + t5;
  t3 = *(s32 *)t4;
  /* Read from stack cache */
  t2 = *(s32 *)(t4 + 4);
  goto g7893;

g7896:
  if (_trace) printf("g7896:\n");
  if ((t12 & 1) == 0)
    goto g7895;
  /* Do the indirect thing */
  t1 = (u32)t3;
  goto g7892;

g7895:
  if (_trace) printf("g7895:\n");
  /* Load the memory action table for cycle */
  arg3 = *(u64 *)&(processor->datawrite);
  /* TagType. */
  /* Discard the CDR code */
  t12 = t2 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = t1;
  /* Adjust for a longword load */
  t12 = (t12 * 4) + arg3;
  /* Get the memory action */
  arg3 = *(s32 *)t12;
#ifndef MINIMA

g7899:
#endif
#ifdef MINIMA

g7899:
  if (_trace) printf("g7899:\n");
  t12 = arg3 & MemoryActionBinding;
  t5 = *(u64 *)&(processor->dbcmask);
  if (t12 == 0)
    goto g7898;
  t4 = t1 << 1;
  t12 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t4 = t4 & t5;
  t5 = 1;
  t5 = t5 << (ivorymemorydata & 63);
  t4 = (s32)t4 + (s32)t12;
  /* Clear sign-extension */
  t4 = (u32)t4;
  t5 = (t4 * 4) + t5;
  /* Fetch the key */
  t4 = *(s32 *)t5;
  /* Fetch value */
  t3 = *(s32 *)(t5 + 4);
  /* Compare */
  t12 = (s32)t1 - (s32)t4;
  /* Trap on miss */
  if (t12 != 0)
    goto g7901;
  /* Extract the pointer, and indirect */
  t1 = (u32)t3;
  goto g7892;

g7901:
  if (_trace) printf("g7901:\n");
  goto dbcachemisstrap;
#endif

g7898:
  /* Perform memory action */
  arg1 = arg3;
  arg2 = 1;
  goto performmemoryaction;
#ifdef TRACING
#endif

DoFastAset1IM:
  goto doistageerror;

/* end DoFastAset1 */
  /* End of Halfword operand from stack instruction - DoFastAset1 */
  /* Array leaders. */
/* start DoArrayLeader */

  /* Halfword operand from stack instruction - DoArrayLeader */
  /* arg2 has the preloaded 8 bit operand. */

doarrayleader:
  if (_trace) printf("doarrayleader:\n");
#ifdef TRACING
#endif

DoArrayLeaderSP:
  if (_trace) printf("DoArrayLeaderSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdoarrayleader;
#endif

DoArrayLeaderLP:
  if (_trace) printf("DoArrayLeaderLP:\n");
#ifdef TRACING
  goto headdoarrayleader;
#endif

DoArrayLeaderFP:
  if (_trace) printf("DoArrayLeaderFP:\n");

headdoarrayleader:
  if (_trace) printf("headdoarrayleader:\n");
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindoarrayleader:
  if (_trace) printf("begindoarrayleader:\n");
  /* arg1 has the operand, not sign extended if immediate. */
  /* arg3=arraytag, arg4=arraydata */
  arg4 = *(s32 *)iSP;
  /* arg3=arraytag, arg4=arraydata */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  /* index data */
  arg2 = (u32)arg1;
  /* index tag */
  arg1 = arg1 >> 32;
  t1 = arg1 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto arrayleaderiop;

arrayleadermerge:
  if (_trace) printf("arrayleadermerge:\n");
  t1 = arg3 - Type_Array;
  /* Strip CDR code, low bits */
  t1 = t1 & 62;
  if (t1 != 0)
    goto arrayleaderexception;
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  /* Memory Read Internal */

g7923:
  t3 = arg4 + ivory;
  arg5 = (t3 * 4);
  arg6 = LDQ_U(t3);
  /* Stack cache offset */
  t1 = arg4 - t11;
  t4 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t1 < (u64)t12) ? 1 : 0;
  arg5 = *(s32 *)arg5;
  arg6 = (u8)(arg6 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7925;

g7924:
  t3 = zero + 64;
  t4 = t4 >> (arg6 & 63);
  t3 = t3 >> (arg6 & 63);
  if (t4 & 1)
    goto g7927;

g7932:
  /* TagType. */
  t1 = arg6 & 63;
  t1 = t1 - Type_HeaderI;
  if (t1 != 0)
    goto arrayleaderiop;
  t8 = arg5 >> (Array_LeaderLengthFieldPos & 63);
  t8 = t8 & Array_LeaderLengthFieldMask;
  t1 = ((u64)arg2 < (u64)t8) ? 1 : 0;
  if (t1 == 0)
    goto arrayleaderbounds;
  arg2 = arg4 - arg2;
  arg2 = arg2 - 1;
  /* Memory Read Internal */

g7933:
  t3 = arg2 + ivory;
  arg5 = (t3 * 4);
  arg6 = LDQ_U(t3);
  /* Stack cache offset */
  t1 = arg2 - t11;
  t4 = *(u64 *)&(processor->dataread_mask);
  /* In range? */
  t2 = ((u64)t1 < (u64)t12) ? 1 : 0;
  arg5 = *(s32 *)arg5;
  arg6 = (u8)(arg6 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7935;

g7934:
  t3 = zero + 240;
  t4 = t4 >> (arg6 & 63);
  t3 = t3 >> (arg6 & 63);
  if (t4 & 1)
    goto g7937;

g7944:
  /* set CDR-NEXT */
  t1 = arg6 & 63;
  *(u32 *)(iSP + 8) = arg5;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t1;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

arrayleaderexception:
  if (_trace) printf("arrayleaderexception:\n");
  arg1 = Type_Fixnum;
  /* SetTag. */
  t1 = arg1 << 32;
  t1 = arg2 | t1;
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 10;
  goto arrayexception;

arrayleaderiop:
  if (_trace) printf("arrayleaderiop:\n");
  arg5 = 0;
  arg2 = 10;
  goto illegaloperand;

arrayleaderbounds:
  if (_trace) printf("arrayleaderbounds:\n");
  arg5 = 0;
  arg2 = 74;
  goto illegaloperand;
#ifdef TRACING
  goto DoArrayLeaderIM;
#endif

DoArrayLeaderIM:
  if (_trace) printf("DoArrayLeaderIM:\n");
  /* arg3=arraytag, arg4=arraydata */
  arg4 = *(s32 *)iSP;
  /* arg3=arraytag, arg4=arraydata */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  goto arrayleadermerge;

g7935:
  if (_trace) printf("g7935:\n");
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t1 = (t1 * 8) + t2;
  arg5 = *(s32 *)t1;
  /* Read from stack cache */
  arg6 = *(s32 *)(t1 + 4);
  goto g7934;

g7937:
  if (_trace) printf("g7937:\n");
  if ((t3 & 1) == 0)
    goto g7936;
  /* Do the indirect thing */
  arg2 = (u32)arg5;
  goto g7933;

g7936:
  if (_trace) printf("g7936:\n");
  /* Load the memory action table for cycle */
  t4 = *(u64 *)&(processor->dataread);
  /* TagType. */
  /* Discard the CDR code */
  t3 = arg6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg2;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t4;
  /* Get the memory action */
  t4 = *(s32 *)t3;

g7941:
  if (_trace) printf("g7941:\n");
  t3 = t4 & MemoryActionTransform;
  if (t3 == 0)
    goto g7940;
  arg6 = arg6 & ~63L;
  arg6 = arg6 | Type_ExternalValueCellPointer;
  goto g7944;
#ifndef MINIMA

g7940:
#endif
#ifdef MINIMA

g7940:
  if (_trace) printf("g7940:\n");
  t3 = t4 & MemoryActionBinding;
  t2 = *(u64 *)&(processor->dbcmask);
  if (t3 == 0)
    goto g7939;
  t1 = arg2 << 1;
  t3 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t1 = t1 & t2;
  t2 = 1;
  t2 = t2 << (ivorymemorydata & 63);
  t1 = (s32)t1 + (s32)t3;
  /* Clear sign-extension */
  t1 = (u32)t1;
  t2 = (t1 * 4) + t2;
  /* Fetch the key */
  t1 = *(s32 *)t2;
  /* Fetch value */
  arg5 = *(s32 *)(t2 + 4);
  /* Compare */
  t3 = (s32)arg2 - (s32)t1;
  /* Trap on miss */
  if (t3 != 0)
    goto g7943;
  /* Extract the pointer, and indirect */
  arg2 = (u32)arg5;
  goto g7933;

g7943:
  if (_trace) printf("g7943:\n");
  goto dbcachemisstrap;
#endif

g7939:
  /* Perform memory action */
  arg1 = t4;
  arg2 = 0;
  goto performmemoryaction;

g7925:
  if (_trace) printf("g7925:\n");
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t1 = (t1 * 8) + t2;
  arg5 = *(s32 *)t1;
  /* Read from stack cache */
  arg6 = *(s32 *)(t1 + 4);
  goto g7924;

g7927:
  if (_trace) printf("g7927:\n");
  if ((t3 & 1) == 0)
    goto g7926;
  /* Do the indirect thing */
  arg4 = (u32)arg5;
  goto g7923;

g7926:
  if (_trace) printf("g7926:\n");
  /* Load the memory action table for cycle */
  t4 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = arg6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg4;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t4;
  /* Get the memory action */
  t4 = *(s32 *)t3;

g7929:
  /* Perform memory action */
  arg1 = t4;
  arg2 = 6;
  goto performmemoryaction;

/* end DoArrayLeader */
  /* End of Halfword operand from stack instruction - DoArrayLeader */
/* start DoStoreArrayLeader */

  /* Halfword operand from stack instruction - DoStoreArrayLeader */
  /* arg2 has the preloaded 8 bit operand. */

dostorearrayleader:
  if (_trace) printf("dostorearrayleader:\n");
#ifdef TRACING
#endif

DoStoreArrayLeaderSP:
  if (_trace) printf("DoStoreArrayLeaderSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdostorearrayleader;
#endif

DoStoreArrayLeaderLP:
  if (_trace) printf("DoStoreArrayLeaderLP:\n");
#ifdef TRACING
  goto headdostorearrayleader;
#endif

DoStoreArrayLeaderFP:
  if (_trace) printf("DoStoreArrayLeaderFP:\n");

headdostorearrayleader:
  if (_trace) printf("headdostorearrayleader:\n");
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindostorearrayleader:
  if (_trace) printf("begindostorearrayleader:\n");
  /* arg1 has the operand, not sign extended if immediate. */
  /* arg3=arraytag, arg4=arraydata */
  arg4 = *(s32 *)iSP;
  /* arg3=arraytag, arg4=arraydata */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  /* t6=valuetag, t7=valuedata */
  t7 = *(s32 *)iSP;
  /* t6=valuetag, t7=valuedata */
  t6 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t7 = (u32)t7;
  /* index data */
  arg2 = (u32)arg1;
  /* index tag */
  arg1 = arg1 >> 32;
  t1 = arg1 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto storearrayleaderiop;

storearrayleadermerge:
  if (_trace) printf("storearrayleadermerge:\n");
  t1 = arg3 - Type_Array;
  /* Strip CDR code, low bits */
  t1 = t1 & 62;
  if (t1 != 0)
    goto storearrayleaderexception;
  t11 = *(u64 *)&(processor->stackcachebasevma);
  /* Size of the stack cache (words) */
  t12 = *(s32 *)&processor->scovlimit;
  /* Memory Read Internal */

g7945:
  t3 = arg4 + ivory;
  arg5 = (t3 * 4);
  arg6 = LDQ_U(t3);
  /* Stack cache offset */
  t1 = arg4 - t11;
  t4 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t1 < (u64)t12) ? 1 : 0;
  arg5 = *(s32 *)arg5;
  arg6 = (u8)(arg6 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7947;

g7946:
  t3 = zero + 64;
  t4 = t4 >> (arg6 & 63);
  t3 = t3 >> (arg6 & 63);
  if (t4 & 1)
    goto g7949;

g7954:
  /* TagType. */
  t1 = arg6 & 63;
  t1 = t1 - Type_HeaderI;
  if (t1 != 0)
    goto storearrayleaderiop;
  t2 = arg5 >> (Array_LeaderLengthFieldPos & 63);
  t2 = t2 & Array_LeaderLengthFieldMask;
  t1 = ((u64)arg2 < (u64)t2) ? 1 : 0;
  if (t1 == 0)
    goto storearrayleaderbounds;
  arg2 = arg4 - arg2;
  arg2 = arg2 - 1;
  /* Memory Read Internal */

g7955:
  t5 = arg2 + ivory;
  t2 = (t5 * 4);
  t1 = LDQ_U(t5);
  /* Stack cache offset */
  t3 = arg2 - t11;
  t8 = *(u64 *)&(processor->datawrite_mask);
  /* In range? */
  t4 = ((u64)t3 < (u64)t12) ? 1 : 0;
  t2 = *(s32 *)t2;
  t1 = (u8)(t1 >> ((t5&7)*8));
  if (t4 != 0)
    goto g7957;

g7956:
  t5 = zero + 240;
  t8 = t8 >> (t1 & 63);
  t5 = t5 >> (t1 & 63);
  if (t8 & 1)
    goto g7959;

g7965:
  /* Merge cdr-code */
  t2 = t6 & 63;
  t1 = t1 & 192;
  t1 = t1 | t2;
  t3 = arg2 + ivory;
  t2 = (t3 * 4);
  t5 = LDQ_U(t3);
  /* Stack cache offset */
  t4 = arg2 - t11;
  /* In range? */
  t8 = ((u64)t4 < (u64)t12) ? 1 : 0;
  t4 = (t1 & 0xff) << ((t3&7)*8);
  t5 = t5 & ~(0xffL << (t3&7)*8);

g7967:
  if (_trace) printf("g7967:\n");
  t5 = t5 | t4;
  STQ_U(t3, t5);
  *(u32 *)t2 = t7;
  /* J. if in cache */
  if (t8 != 0)
    goto g7966;
  goto NEXTINSTRUCTION;
  goto NEXTINSTRUCTION;

storearrayleaderexception:
  if (_trace) printf("storearrayleaderexception:\n");
  arg1 = Type_Fixnum;
  /* SetTag. */
  t1 = arg1 << 32;
  t1 = arg2 | t1;
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 3;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 11;
  goto arrayexception;

storearrayleaderiop:
  if (_trace) printf("storearrayleaderiop:\n");
  arg5 = 0;
  arg2 = 11;
  goto illegaloperand;

storearrayleaderbounds:
  if (_trace) printf("storearrayleaderbounds:\n");
  arg5 = 0;
  arg2 = 74;
  goto illegaloperand;
#ifdef TRACING
  goto DoStoreArrayLeaderIM;
#endif

DoStoreArrayLeaderIM:
  if (_trace) printf("DoStoreArrayLeaderIM:\n");
  /* arg3=arraytag, arg4=arraydata */
  arg4 = *(s32 *)iSP;
  /* arg3=arraytag, arg4=arraydata */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  /* t6=valuetag, t7=valuedata */
  t7 = *(s32 *)iSP;
  /* t6=valuetag, t7=valuedata */
  t6 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  t7 = (u32)t7;
  goto storearrayleadermerge;

g7966:
  if (_trace) printf("g7966:\n");
  t3 = *(u64 *)&(processor->stackcachedata);
  /* Stack cache offset */
  t4 = arg2 - t11;
  /* reconstruct SCA */
  t3 = (t4 * 8) + t3;
  /* Store in stack */
  *(u32 *)t3 = t7;
  /* write the stack cache */
  *(u32 *)(t3 + 4) = t1;
  goto NEXTINSTRUCTION;

g7957:
  if (_trace) printf("g7957:\n");
  t4 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t3 = (t3 * 8) + t4;
  t2 = *(s32 *)t3;
  /* Read from stack cache */
  t1 = *(s32 *)(t3 + 4);
  goto g7956;

g7959:
  if (_trace) printf("g7959:\n");
  if ((t5 & 1) == 0)
    goto g7958;
  /* Do the indirect thing */
  arg2 = (u32)t2;
  goto g7955;

g7958:
  if (_trace) printf("g7958:\n");
  /* Load the memory action table for cycle */
  t8 = *(u64 *)&(processor->datawrite);
  /* TagType. */
  /* Discard the CDR code */
  t5 = t1 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg2;
  /* Adjust for a longword load */
  t5 = (t5 * 4) + t8;
  /* Get the memory action */
  t8 = *(s32 *)t5;
#ifndef MINIMA

g7962:
#endif
#ifdef MINIMA

g7962:
  if (_trace) printf("g7962:\n");
  t5 = t8 & MemoryActionBinding;
  t4 = *(u64 *)&(processor->dbcmask);
  if (t5 == 0)
    goto g7961;
  t3 = arg2 << 1;
  t5 = *(u64 *)&(processor->dbcbase);
  /* Hash index */
  t3 = t3 & t4;
  t4 = 1;
  t4 = t4 << (ivorymemorydata & 63);
  t3 = (s32)t3 + (s32)t5;
  /* Clear sign-extension */
  t3 = (u32)t3;
  t4 = (t3 * 4) + t4;
  /* Fetch the key */
  t3 = *(s32 *)t4;
  /* Fetch value */
  t2 = *(s32 *)(t4 + 4);
  /* Compare */
  t5 = (s32)arg2 - (s32)t3;
  /* Trap on miss */
  if (t5 != 0)
    goto g7964;
  /* Extract the pointer, and indirect */
  arg2 = (u32)t2;
  goto g7955;

g7964:
  if (_trace) printf("g7964:\n");
  goto dbcachemisstrap;
#endif

g7961:
  /* Perform memory action */
  arg1 = t8;
  arg2 = 1;
  goto performmemoryaction;

g7947:
  if (_trace) printf("g7947:\n");
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t1 = (t1 * 8) + t2;
  arg5 = *(s32 *)t1;
  /* Read from stack cache */
  arg6 = *(s32 *)(t1 + 4);
  goto g7946;

g7949:
  if (_trace) printf("g7949:\n");
  if ((t3 & 1) == 0)
    goto g7948;
  /* Do the indirect thing */
  arg4 = (u32)arg5;
  goto g7945;

g7948:
  if (_trace) printf("g7948:\n");
  /* Load the memory action table for cycle */
  t4 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = arg6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg4;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t4;
  /* Get the memory action */
  t4 = *(s32 *)t3;

g7951:
  /* Perform memory action */
  arg1 = t4;
  arg2 = 6;
  goto performmemoryaction;

/* end DoStoreArrayLeader */
  /* End of Halfword operand from stack instruction - DoStoreArrayLeader */
/* start DoAlocLeader */

  /* Halfword operand from stack instruction - DoAlocLeader */
  /* arg2 has the preloaded 8 bit operand. */

doalocleader:
  if (_trace) printf("doalocleader:\n");
#ifdef TRACING
#endif

DoAlocLeaderSP:
  if (_trace) printf("DoAlocLeaderSP:\n");
  /* Assume SP mode */
  arg1 = arg5;
  /* SP-pop mode */
  if (arg2 == 0)
    arg1 = iSP;
  /* Adjust SP if SP-pop mode */
  if (arg2 == 0)
    iSP = arg4;
#ifdef TRACING
  goto headdoalocleader;
#endif

DoAlocLeaderLP:
  if (_trace) printf("DoAlocLeaderLP:\n");
#ifdef TRACING
  goto headdoalocleader;
#endif

DoAlocLeaderFP:
  if (_trace) printf("DoAlocLeaderFP:\n");

headdoalocleader:
  if (_trace) printf("headdoalocleader:\n");
  /* Compute operand address */
  arg1 = (arg2 * 8) + arg1;
  /* Get the operand */
  arg1 = *(u64 *)arg1;

begindoalocleader:
  if (_trace) printf("begindoalocleader:\n");
  /* arg1 has the operand, not sign extended if immediate. */
  /* arg3=arraytag, arg4=arraydata */
  arg4 = *(s32 *)iSP;
  /* arg3=arraytag, arg4=arraydata */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  /* index data */
  arg2 = (u32)arg1;
  /* index tag */
  arg1 = arg1 >> 32;
  t1 = arg1 - Type_Fixnum;
  /* Strip CDR code */
  t1 = t1 & 63;
  if (t1 != 0)
    goto alocleaderiop;

alocleadermerge:
  if (_trace) printf("alocleadermerge:\n");
  t1 = arg3 - Type_Array;
  /* Strip CDR code, low bits */
  t1 = t1 & 62;
  if (t1 != 0)
    goto alocleaderexception;
  /* Memory Read Internal */

g7968:
  /* Base of stack cache */
  t1 = *(u64 *)&(processor->stackcachebasevma);
  t3 = arg4 + ivory;
  t2 = *(s32 *)&processor->scovlimit;
  arg5 = (t3 * 4);
  arg6 = LDQ_U(t3);
  /* Stack cache offset */
  t1 = arg4 - t1;
  t4 = *(u64 *)&(processor->header_mask);
  /* In range? */
  t2 = ((u64)t1 < (u64)t2) ? 1 : 0;
  arg5 = *(s32 *)arg5;
  arg6 = (u8)(arg6 >> ((t3&7)*8));
  if (t2 != 0)
    goto g7970;

g7969:
  t3 = zero + 64;
  t4 = t4 >> (arg6 & 63);
  t3 = t3 >> (arg6 & 63);
  if (t4 & 1)
    goto g7972;

g7977:
  /* TagType. */
  t1 = arg6 & 63;
  t1 = t1 - Type_HeaderI;
  if (t1 != 0)
    goto alocleaderiop;
  t9 = arg5 >> (Array_LeaderLengthFieldPos & 63);
  t9 = t9 & Array_LeaderLengthFieldMask;
  t1 = ((u64)arg2 < (u64)t9) ? 1 : 0;
  if (t1 == 0)
    goto alocleaderbounds;
  arg2 = arg4 - arg2;
  arg2 = arg2 - 1;
  t1 = Type_Locative;
  *(u32 *)(iSP + 8) = arg2;
  /* write the stack cache */
  *(u32 *)(iSP + 12) = t1;
  iSP = iSP + 8;
  goto NEXTINSTRUCTION;

alocleaderexception:
  if (_trace) printf("alocleaderexception:\n");
  arg1 = Type_Fixnum;
  /* SetTag. */
  t1 = arg1 << 32;
  t1 = arg2 | t1;
  /* arg6 = tag to dispatch on */
  arg6 = arg3;
  /* arg3 = stackp */
  arg3 = 0;
  /* arg1 = instruction arity */
  arg1 = 2;
  /* arg4 = arithmeticp */
  arg4 = 0;
  arg5 = 0;
  arg2 = 10;
  goto arrayexception;

alocleaderiop:
  if (_trace) printf("alocleaderiop:\n");
  arg5 = 0;
  arg2 = 10;
  goto illegaloperand;

alocleaderbounds:
  if (_trace) printf("alocleaderbounds:\n");
  arg5 = 0;
  arg2 = 74;
  goto illegaloperand;
#ifdef TRACING
  goto DoAlocLeaderIM;
#endif

DoAlocLeaderIM:
  if (_trace) printf("DoAlocLeaderIM:\n");
  /* arg3=arraytag, arg4=arraydata */
  arg4 = *(s32 *)iSP;
  /* arg3=arraytag, arg4=arraydata */
  arg3 = *(s32 *)(iSP + 4);
  /* Pop Stack. */
  iSP = iSP - 8;
  arg4 = (u32)arg4;
  goto alocleadermerge;

g7970:
  if (_trace) printf("g7970:\n");
  t2 = *(u64 *)&(processor->stackcachedata);
  /* reconstruct SCA */
  t1 = (t1 * 8) + t2;
  arg5 = *(s32 *)t1;
  /* Read from stack cache */
  arg6 = *(s32 *)(t1 + 4);
  goto g7969;

g7972:
  if (_trace) printf("g7972:\n");
  if ((t3 & 1) == 0)
    goto g7971;
  /* Do the indirect thing */
  arg4 = (u32)arg5;
  goto g7968;

g7971:
  if (_trace) printf("g7971:\n");
  /* Load the memory action table for cycle */
  t4 = *(u64 *)&(processor->header);
  /* TagType. */
  /* Discard the CDR code */
  t3 = arg6 & 63;
  /* stash the VMA for the (likely) trap */
  *(u64 *)&processor->vma = arg4;
  /* Adjust for a longword load */
  t3 = (t3 * 4) + t4;
  /* Get the memory action */
  t4 = *(s32 *)t3;

g7974:
  /* Perform memory action */
  arg1 = t4;
  arg2 = 6;
  goto performmemoryaction;

/* end DoAlocLeader */
  /* End of Halfword operand from stack instruction - DoAlocLeader */
  /* Fin. */



/* End of file automatically generated from ../alpha-emulator/ifunarra.as */
