;;; -*- Mode: LISP; Package: ALPHA-AXP-INTERNALS; Base: 10; Syntax: Common-Lisp; -*-
;;;
;;;  WARNING!!  DO NOT MODIFY THIS FILE!
;;;  It was automatically generated from vlm:alpha-emulator;aistat.sid.  Any changes made to it will be lost.

#+Alpha-AXP-Emulator
(in-package "ALPHA-AXP-INTERNALS")

#+PowerPC-Emulator
(in-package "POWERPC-INTERNALS")


;;; Structure PROCESSORSTATE
(defconstant processorstate$q-transpare3 -1440)
(defconstant processorstate$q-transpare2 -1432)
(defconstant processorstate$q-transpare1 -1424)
(defconstant processorstate$q-carcdrsubroutine -1416)
(defconstant processorstate$q-cdrsubroutine -1408)
(defconstant processorstate$q-carsubroutine -1400)
(defconstant processorstate$q-linkage -1392)
(defconstant processorstate$q-resumeema -1384)
(defconstant processorstate$p-statistics -1376)
(defconstant processorstate$p-trace-hook -1368)
(defconstant processorstate$q-instruction-count -1360)
(defconstant processorstate$q-long-pad0 -1352)
(defconstant processorstate$q-asrr9 -1344)
(defconstant processorstate$q-asrr10 -1336)
(defconstant processorstate$q-asrr11 -1328)
(defconstant processorstate$q-asrr12 -1320)
(defconstant processorstate$q-asrr13 -1312)
(defconstant processorstate$q-asrr14 -1304)
(defconstant processorstate$q-asrr15 -1296)
(defconstant processorstate$q-long-pad1 -1288)
(defconstant processorstate$q-asrr26 -1280)
(defconstant processorstate$q-asrr27 -1272)
(defconstant processorstate$q-asrr29 -1264)
(defconstant processorstate$q-asrr30 -1256)
(defconstant processorstate$q-asrf2 -1248)
(defconstant processorstate$q-asrf3 -1240)
(defconstant processorstate$q-asrf4 -1232)
(defconstant processorstate$q-asrf5 -1224)
(defconstant processorstate$q-asrf6 -1216)
(defconstant processorstate$q-asrf7 -1208)
(defconstant processorstate$q-asrf8 -1200)
(defconstant processorstate$q-asrf9 -1192)
(defconstant processorstate$p-meterdatabuff -1184)
(defconstant processorstate$l-meterpos -1176)
(defconstant processorstate$l-metermax -1172)
(defconstant processorstate$l-meterfreq -1168)
(defconstant processorstate$l-metermask -1164)
(defconstant processorstate$l-metervalue -1160)
(defconstant processorstate$l-metercount -1156)
(defconstant processorstate$q-choiceptr -1152)
(defconstant processorstate$q-sstkchoiceptr -1144)
(defconstant processorstate$q-dbcbase -1136)
(defconstant processorstate$q-dbcmask -1128)
(defconstant processorstate$p-coprocessorreadhook -1120)
(defconstant processorstate$p-coprocessorwritehook -1112)
(defconstant processorstate$p-flushcaches-hook -1104)
(defconstant processorstate$p-i-stage-error-hook -1096)
(defconstant processorstate$q-sfp1 -1088)
(defconstant processorstate$q-fp0 -1080)
(defconstant processorstate$q-fp1 -1072)
(defconstant processorstate$q-floating-exception -1064)
(defconstant processorstate$q-aluandrotatecontrol -1056)
(defconstant processorstate$q-rotatelatch -1048)
(defconstant processorstate$q-aluborrow -1040)
(defconstant processorstate$q-aluoverflow -1032)
(defconstant processorstate$q-alulessthan -1024)
(defconstant processorstate$q-aluop -1016)
(defconstant processorstate$q-byterotate -1008)
(defconstant processorstate$q-bytesize -1000)
(defconstant processorstate$q-bindingstacklimit -992)
(defconstant processorstate$q-bindingstackpointer -984)
(defconstant processorstate$q-catchblock -976)
(defconstant processorstate$q-extraandcatch -968)
(defconstant processorstate$q-msclockcache -960)
(defconstant processorstate$q-mscmultiplier -952)
(defconstant processorstate$q-previousrcpp -944)
(defconstant processorstate$p-rlink -936)
(defconstant processorstate$l-interruptreg -928)
(defconstant processorstate$l-zoneoldspace -924)
(defconstant processorstate$l-ephemeraloldspace -920)
(defconstant processorstate$l-int-pad0 -916)
(defconstant processorstate$q-eqnoteql -912)
(defconstant processorstate$l-lclength -904)
(defconstant processorstate$l-sclength -900)
(defconstant processorstate$q-lcarea -896)
(defconstant processorstate$q-lcaddress -888)
(defconstant processorstate$q-scarea -880)
(defconstant processorstate$q-scaddress -872)
(defconstant processorstate$q-restartsp -864)
(defconstant processorstate$q-stop-interpreter -856)
(defconstant processorstate$q-immediate-arg -848)
(defconstant processorstate$q-continuationcp -840)
(defconstant processorstate$q-continuation -832)
(defconstant processorstate$q-control -824)
(defconstant processorstate$q-niladdress -816)
(defconstant processorstate$q-taddress -808)
(defconstant processorstate$q-bar0 -800)
(defconstant processorstate$q-bar1 -792)
(defconstant processorstate$q-bar2 -784)
(defconstant processorstate$q-bar3 -776)
(defconstant processorstate$q-epc -768)
(defconstant processorstate$q-fp -760)
(defconstant processorstate$q-lp -752)
(defconstant processorstate$q-sp -744)
(defconstant processorstate$p-cp -736)
(defconstant processorstate$q-fccrmask -728)
(defconstant processorstate$l-cslimit -720)
(defconstant processorstate$l-csextralimit -716)
(defconstant processorstate$p-trapmeterdata -712)
(defconstant processorstate$q-fepmodetrapvecaddress -704)
(defconstant processorstate$q-trapvecbase -696)
(defconstant processorstate$q-tvi -688)
(defconstant processorstate$q-fccrtrapmask -680)
(defconstant processorstate$p-ptrtype -672)
(defconstant processorstate$p-vmattributetable -664)
(defconstant processorstate$q-vma -656)
(defconstant processorstate$q-mostnegativefixnum -648)
(defconstant processorstate$p-icachebase -640)
(defconstant processorstate$p-endicache -632)
(defconstant processorstate$q-fullworddispatch -624)
(defconstant processorstate$q-halfworddispatch -616)
(defconstant processorstate$q-areventcount -608)
(defconstant processorstate$q-stackcachesize -600)
(defconstant processorstate$q-stackcachetopvma -592)
(defconstant processorstate$q-cdrcodemask -584)
(defconstant processorstate$p-stackcachedata -576)
(defconstant processorstate$q-stackcachebasevma -568)
(defconstant processorstate$l-scovlimit -560)
(defconstant processorstate$l-scovdumpcount -556)
(defconstant processorstate$q-mostpositivefixnum -552)
(defconstant processorstate$q-internalregisterread1 -544)
(defconstant processorstate$q-internalregisterread2 -536)
(defconstant processorstate$q-internalregisterwrite1 -528)
(defconstant processorstate$q-internalregisterwrite2 -520)
(defconstant processorstate$q-dataread-mask -512)
(defconstant processorstate$p-dataread -504)
(defconstant processorstate$q-datawrite-mask -496)
(defconstant processorstate$p-datawrite -488)
(defconstant processorstate$q-bindread-mask -480)
(defconstant processorstate$p-bindread -472)
(defconstant processorstate$q-bindwrite-mask -464)
(defconstant processorstate$p-bindwrite -456)
(defconstant processorstate$q-bindreadnomonitor-mask -448)
(defconstant processorstate$p-bindreadnomonitor -440)
(defconstant processorstate$q-bindwritenomonitor-mask -432)
(defconstant processorstate$p-bindwritenomonitor -424)
(defconstant processorstate$q-header-mask -416)
(defconstant processorstate$p-header -408)
(defconstant processorstate$q-structureoffset-mask -400)
(defconstant processorstate$p-structureoffset -392)
(defconstant processorstate$q-scavenge-mask -384)
(defconstant processorstate$p-scavenge -376)
(defconstant processorstate$q-cdr-mask -368)
(defconstant processorstate$p-cdr -360)
(defconstant processorstate$q-gccopy-mask -352)
(defconstant processorstate$p-gccopy -344)
(defconstant processorstate$q-raw-mask -336)
(defconstant processorstate$p-raw -328)
(defconstant processorstate$q-rawtranslate-mask -320)
(defconstant processorstate$p-rawtranslate -312)
(defconstant processorstate$l-please-stop -304)
(defconstant processorstate$l-please-trap -300)
(defconstant processorstate$q-runningp -296)
(defconstant processorstate$q-ac0array -288)
(defconstant processorstate$q-ac0arword -280)
(defconstant processorstate$q-ac0locat -272)
(defconstant processorstate$q-ac0length -264)
(defconstant processorstate$q-ac1array -256)
(defconstant processorstate$q-ac1arword -248)
(defconstant processorstate$q-ac1locat -240)
(defconstant processorstate$q-ac1length -232)
(defconstant processorstate$q-ac2array -224)
(defconstant processorstate$q-ac2arword -216)
(defconstant processorstate$q-ac2locat -208)
(defconstant processorstate$q-ac2length -200)
(defconstant processorstate$q-ac3array -192)
(defconstant processorstate$q-ac3arword -184)
(defconstant processorstate$q-ac3locat -176)
(defconstant processorstate$q-ac3length -168)
(defconstant processorstate$q-ac4array -160)
(defconstant processorstate$q-ac4arword -152)
(defconstant processorstate$q-ac4locat -144)
(defconstant processorstate$q-ac4length -136)
(defconstant processorstate$q-ac5array -128)
(defconstant processorstate$q-ac5arword -120)
(defconstant processorstate$q-ac5locat -112)
(defconstant processorstate$q-ac5length -104)
(defconstant processorstate$q-ac6array -96)
(defconstant processorstate$q-ac6arword -88)
(defconstant processorstate$q-ac6locat -80)
(defconstant processorstate$q-ac6length -72)
(defconstant processorstate$q-ac7array -64)
(defconstant processorstate$q-ac7arword -56)
(defconstant processorstate$q-ac7locat -48)
(defconstant processorstate$q-ac7length -40)
(defconstant processorstate$l-tmcurrenttransaction -32)
(defconstant processorstate$l-tmwritestart -28)
(defconstant processorstate$l-tmwritecurrent -24)
(defconstant processorstate$l-tmwritelimit -20)
(defconstant processorstate$l-tmrecordingreads -16)
(defconstant processorstate$l-tmreadstart -12)
(defconstant processorstate$l-tmreadcurrent -8)
(defconstant processorstate$l-tmreadlimit -4)

(defconstant processorstate$k-size 1440)
(defconstant |PROCESSORSTATESIZE| 1440)


;;; Structure CACHELINE
(defconstant cacheline$q-annotation 0)
(defconstant cacheline$l-nextpcdata 8)
(defconstant cacheline$l-nextpctag 12)
(defconstant cacheline$p-nextcp 16)
(defconstant cacheline$l-instruction 24)
(defconstant cacheline$l-operand 28)
(defconstant cacheline$l-pcdata 32)
(defconstant cacheline$l-pctag 36)
(defconstant cacheline$p-code 40)

(defconstant cacheline$k-size 48)
(defconstant |CACHELINESIZE| 48)

(defparameter |cacheline|$k-|bits| 18)
(defparameter |CacheLineBits| 18)

(defparameter |cacheline|$k-|mask| 262143)
(defparameter |CacheLineMask| 262143)

(defparameter |cacheline|$k-|rshift| 16)
(defparameter |CacheLineRShift| 16)

(defparameter |cacheline|$k-|lshift| 6)
(defparameter |CacheLineLShift| 6)

(defparameter |cacheline|$k-|fillamount| 20)
(defparameter |CacheLineFillAmount| 20)


;;; Structure ARRAYCACHE
(defconstant arraycache$q-array 0)
(defconstant arraycache$q-arword 8)
(defconstant arraycache$q-locat 16)
(defconstant arraycache$q-length 24)

(defparameter |autoarrayreg|$k-|mask| 224)
(defparameter |AutoArrayRegMask| 224)

(defparameter |autoarrayreg|$k-|size| 32)
(defparameter |AutoArrayRegSize| 32)

(defparameter |autoarrayreg|$k-|shift| 0)
(defparameter |AutoArrayRegShift| 0)

(defparameter |msclock|$k-|unitstomsshift| 24)
(defparameter |MSclockUnitsToMSShift| 24)

(defparameter |msclock|$k-|unitspermicrosecond| 16777216)
(defparameter |MSclockUnitsPerMicrosecond| 16777216)

(defparameter |stack|$k-|cachesize| 1792)
(defparameter |StackCacheSize| 1792)

(defparameter |stack|$k-|maxframesize| 128)
(defparameter |StackMaxFrameSize| 128)

(defparameter |stack|$k-|cachemargin| 128)
(defparameter |StackCacheMargin| 128)

(defparameter |stack|$k-|cachedumpquantum| 896)
(defparameter |StackCacheDumpQuantum| 896)

(defconstant |ivorymemory|$k-|data| 35)
(defconstant |IvoryMemoryData| 35)

(defconstant |ivorymemory|$k-|tag| 33)
(defconstant |IvoryMemoryTag| 33)


;;; Structure SAVEDREGISTERS
(defconstant savedregisters$q-r9 0)
(defconstant savedregisters$q-r10 8)
(defconstant savedregisters$q-r11 16)
(defconstant savedregisters$q-r12 24)
(defconstant savedregisters$q-r13 32)
(defconstant savedregisters$q-r14 40)
(defconstant savedregisters$q-r15 48)
(defconstant savedregisters$q-r29 56)
(defconstant savedregisters$q-f2 64)
(defconstant savedregisters$q-f3 72)
(defconstant savedregisters$q-f4 80)
(defconstant savedregisters$q-f5 88)
(defconstant savedregisters$q-f6 96)
(defconstant savedregisters$q-f7 104)
(defconstant savedregisters$q-f8 112)
(defconstant savedregisters$q-f9 120)

(defconstant savedregisters$k-size 128)
(defconstant |SAVEDREGISTERSSIZE| 128)


;;; Structure TRACEDATA
(defconstant tracedata$q-n_entries 0)
(defconstant tracedata$l-recording_p 8)
(defconstant tracedata$l-wrap_p 12)
(defconstant tracedata$q-start_pc 16)
(defconstant tracedata$q-stop_pc 24)
(defconstant tracedata$p-records_start 32)
(defconstant tracedata$p-records_end 40)
(defconstant tracedata$p-current_entry 48)
(defconstant tracedata$p-printer 56)

(defconstant tracedata$k-size 64)
(defconstant |TRACEDATASIZE| 64)


;;; Structure TRACERECORD
(defconstant tracerecord$q-counter 0)
(defconstant tracerecord$q-epc 8)
(defconstant tracerecord$q-tos 16)
(defconstant tracerecord$q-sp 24)
(defconstant tracerecord$p-instruction 32)
(defconstant tracerecord$q-instruction_data 40)
(defconstant tracerecord$l-operand 48)
(defconstant tracerecord$l-trap_p 52)
(defconstant tracerecord$q-trap_data_0 56)
(defconstant tracerecord$q-trap_data_1 64)
(defconstant tracerecord$q-trap_data_2 72)
(defconstant tracerecord$q-trap_data_3 80)
(defconstant tracerecord$l-catch_block_p 88)
(defconstant tracerecord$l-int-pad0 92)
(defconstant tracerecord$q-catch_block_0 96)
(defconstant tracerecord$q-catch_block_1 104)
(defconstant tracerecord$q-catch_block_2 112)
(defconstant tracerecord$q-catch_block_3 120)

(defconstant tracerecord$k-size 128)
(defconstant |TRACERECORDSIZE| 128)

(defparameter |cachemeter|$k-|pwr| 14)
(defparameter |CacheMeterPwr| 14)

(defparameter |cachemeter|$k-|defaultfreq| 1000)
(defparameter |CacheMeterDefaultFreq| 1000)
