/* -*- Mode:C -*- */

/**** Instruction decoding ****/

#include <stddef.h>
#include <stdio.h>

#include "emulator.h"
#include "dispatch.h"
#include "ivory.h"
#include "memory.h"

typedef struct _DecoderPair
{
  int dispatch;
  void (*decode) ();
} DecoderPair;

static const int ReturnInstructionDecoder[3] =
{
  DispatchReturnSingleNIL,
  DispatchReturnSingleT,
  DispatchReturnSingleTOS
};

static const int WordInstructionDecoder[64] =
{
  DispatchPushNull,
  DispatchPushMonitorForward,
  DispatchPushHeaderP,
  DispatchPushHeaderI,
  DispatchPushExternalValueCellPointer,
  DispatchPushOneQForward,
  DispatchPushHeaderForward,
  DispatchPushElementForward,
  DispatchPushFixnum,
  DispatchPushSmallRatio,
  DispatchPushSingleFloat,
  DispatchPushDoubleFloat,
  DispatchPushBignum,
  DispatchPushBigRatio,
  DispatchPushComplex,
  DispatchPushSpareNumber,
  DispatchPushInstance,
  DispatchPushListInstance,
  DispatchPushArrayInstance,
  DispatchPushStringInstance,
  DispatchPushNil,
  DispatchPushList,
  DispatchPushArray,
  DispatchPushString,
  DispatchPushSymbol,
  DispatchPushLocative,
  DispatchPushLexicalClosure,
  DispatchPushDynamicClosure,
  DispatchPushCompiledFunction,
  DispatchPushGenericFunction,
  DispatchPushSparePointer1,
  DispatchPushSparePointer2,
  DispatchPushPhysicalAddress,
  DispatchPushSpareImmediate1,
  DispatchPushBoundLocation,
  DispatchPushCharacter,
  DispatchPushLogicVariable,
  DispatchPushGcForward,
  DispatchPushEvenPc,
  DispatchPushOddPc,
  DispatchCallCompiledEven,
  DispatchCallCompiledOdd,
  DispatchCallIndirect,
  DispatchCallGeneric,
  DispatchCallCompiledEvenPrefetch,
  DispatchCallCompiledOddPrefetch,
  DispatchCallIndirectPrefetch,
  DispatchCallGenericPrefetch,
  DispatchPushPackedInstruction60,
  DispatchPushPackedInstruction61,
  DispatchPushPackedInstruction62,
  DispatchPushPackedInstruction63,
  DispatchPushPackedInstruction64,
  DispatchPushPackedInstruction65,
  DispatchPushPackedInstruction66,
  DispatchPushPackedInstruction67,
  DispatchPushPackedInstruction70,
  DispatchPushPackedInstruction71,
  DispatchPushPackedInstruction72,
  DispatchPushPackedInstruction73,
  DispatchPushPackedInstruction74,
  DispatchPushPackedInstruction75,
  DispatchPushPackedInstruction76,
  DispatchPushPackedInstruction77,
};

static const int PopInstructionDecoder[256] =
{
  DispatchCarPop,
  DispatchCdrPop,
  DispatchEndpPop,
  DispatchSetup1dArrayPop,
  DispatchSetupForce1dArrayPop,
  DispatchBindLocativePop,
  DispatchRestoreBindingStackPop,
  DispatchEphemeralpPop,
  DispatchStartCallPop,
  DispatchJumpPop,
  DispatchTagPop,
  DispatchDereferencePop,
  DispatchLogicTailTestPop,
  DispatchProcBreakpointPop,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchPushLexicalVarPop,
  DispatchPushLexicalVarPop,
  DispatchPushLexicalVarPop,
  DispatchPushLexicalVarPop,
  DispatchPushLexicalVarPop,
  DispatchPushLexicalVarPop,
  DispatchPushLexicalVarPop,
  DispatchPushLexicalVarPop,
  DispatchBlock0WritePop,
  DispatchBlock1WritePop,
  DispatchBlock2WritePop,
  DispatchBlock3WritePop,
  DispatchZeropPop,
  DispatchMinuspPop,
  DispatchPluspPop,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchPushPop,
  DispatchIllegalInstruction,
  DispatchPushAddressSpRelativePop,
  DispatchPushLocalLogicVariablesPop,
  DispatchReturnMultiplePop,
  DispatchReturnKludgePop,
  DispatchIllegalInstruction,
  DispatchUnbindNPop,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchUnaryMinusPop,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchSetToCarPop,
  DispatchSetToCdrPop,
  DispatchSetToCdrPushCarPop,
  DispatchIncrementPop,
  DispatchDecrementPop,
  DispatchPointerIncrementPop,
  DispatchSetCdrCode1Pop,
  DispatchSetCdrCode2Pop,
  DispatchPushAddressPop,
  DispatchSetSpToAddressPop,
  DispatchSetSpToAddressSaveTosPop,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchBlock0ReadAluPop,
  DispatchBlock1ReadAluPop,
  DispatchBlock2ReadAluPop,
  DispatchBlock3ReadAluPop,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchRplacaPop,
  DispatchRplacdPop,
  DispatchMultiplyPop,
  DispatchQuotientPop,
  DispatchCeilingPop,
  DispatchFloorPop,
  DispatchTruncatePop,
  DispatchRoundPop,
  DispatchIllegalInstruction,
  DispatchRationalQuotientPop,
  DispatchMinPop,
  DispatchMaxPop,
  DispatchAluPop,
  DispatchLogandPop,
  DispatchLogxorPop,
  DispatchLogiorPop,
  DispatchRotPop,
  DispatchLshPop,
  DispatchMultiplyDoublePop,
  DispatchLshcBignumStepPop,
  DispatchStackBltPop,
  DispatchRgetfPop,
  DispatchMemberPop,
  DispatchAssocPop,
  DispatchPointerPlusPop,
  DispatchPointerDifferencePop,
  DispatchAshPop,
  DispatchStoreConditionalPop,
  DispatchMemoryWritePop,
  DispatchPStoreContentsPop,
  DispatchBindLocativeToValuePop,
  DispatchUnifyPop,
  DispatchPopLexicalVarPop,
  DispatchPopLexicalVarPop,
  DispatchPopLexicalVarPop,
  DispatchPopLexicalVarPop,
  DispatchPopLexicalVarPop,
  DispatchPopLexicalVarPop,
  DispatchPopLexicalVarPop,
  DispatchPopLexicalVarPop,
  DispatchMovemLexicalVarPop,
  DispatchMovemLexicalVarPop,
  DispatchMovemLexicalVarPop,
  DispatchMovemLexicalVarPop,
  DispatchMovemLexicalVarPop,
  DispatchMovemLexicalVarPop,
  DispatchMovemLexicalVarPop,
  DispatchMovemLexicalVarPop,
  DispatchEqualNumberPop,
  DispatchLesspPop,
  DispatchGreaterpPop,
  DispatchEqlPop,
  DispatchEqualNumberNoPopPop,
  DispatchLesspNoPopPop,
  DispatchGreaterpNoPopPop,
  DispatchEqlNoPopPop,
  DispatchEqPop,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchLogtestPop,
  DispatchEqNoPopPop,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchLogtestNoPopPop,
  DispatchAddPop,
  DispatchSubPop,
  Dispatch32BitPlusPop,
  Dispatch32BitDifferencePop,
  DispatchAddBignumStepPop,
  DispatchSubBignumStepPop,
  DispatchMultiplyBignumStepPop,
  DispatchDivideBignumStepPop,
  DispatchAset1Pop,
  DispatchAllocateListBlockPop,
  DispatchAref1Pop,
  DispatchAloc1Pop,
  DispatchStoreArrayLeaderPop,
  DispatchAllocateStructureBlockPop,
  DispatchArrayLeaderPop,
  DispatchAlocLeaderPop,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchInstanceRefPop,
  DispatchInstanceSetPop,
  DispatchInstanceLocPop,
  DispatchSetTagPop,
  DispatchIllegalInstruction,
  DispatchUnsignedLesspPop,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchUnsignedLesspNoPopPop,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchPopPop,
  DispatchMovemPop,
  DispatchMergeCdrNoPopPop,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchFastAref1Pop,
  DispatchFastAset1Pop,
  DispatchStackBltAddressPop,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
  DispatchIllegalInstruction,
};

static const int IllegalInstructionDecoder = DispatchIllegalInstruction;

static void DecodeNoneFunction (int i, InstructionCacheLine *cp)
{
  cp->operand = 0;
}

static InstructionCacheLine InstructionCacheLookupCPRepresentation =
  { TypeOddPC, -1, TypeOddPC, -1, DispatchInstructionCacheLookup, 0, 0, NULL };

static void Decode8BitUnsignedOperandFunction (int i, InstructionCacheLine *cp)
{
  cp->operand = i & 0377;
}

static void Decode8BitSignedOperandFunction (int i, InstructionCacheLine *cp)
{
  cp->operand = SignExtend8 (i);
}

static void Decode10BitUnsignedOperandFunction (int i, InstructionCacheLine *cp)
{
  cp->operand = i & 01777;
}

static void Decode12BitUnsignedOperandFunction (int i, InstructionCacheLine *cp)
{
  cp->operand = i & 07777;
}

static void DecodeFPOperandFunction (int i, InstructionCacheLine *cp)
{
  cp->operand = (i & 0377);
}

static void DecodeLPOperandFunction (int i, InstructionCacheLine *cp)
{
  cp->operand = (i & 0377);
}

static void DecodeSPOperandFunction (int i, InstructionCacheLine *cp)
{
  int offset = i & 0377;

  if (offset == 0)
    {
      cp->code = PopInstructionDecoder [ldb (8,10,i)];
      cp->operand = 0;
    }
  else
    cp->operand = (offset - 255);
}

static void DecodeBranchOperandFunction (int i, InstructionCacheLine *cp)
{
  cp->operand = SignExtend10 (i);
}

static void DecodeReturnOperandFunction (int i, InstructionCacheLine *cp)
{
  switch (i & 01777)
  {
  case 01000:
    cp->code = ReturnInstructionDecoder [2]; /*TOS*/
    cp->operand = 0;
    break;
  case 01040:
    cp->code = ReturnInstructionDecoder [0]; /*NIL*/
    cp->operand = 0;
    break;
  case 01041:
    cp->code = ReturnInstructionDecoder [1]; /*T*/
    cp->operand = 0;
    break;
  }
}

static void DecodeEntryOperandFunction (int i, InstructionCacheLine *cp)
{
  cp->operand = dpb (ldb (8,18,i), 8, 8, i & 0377);
}

static const DecoderPair PackedInstructionDecoder[1024] =
{
  { DispatchCarFP, DecodeFPOperandFunction },
  { DispatchCarLP, DecodeLPOperandFunction },
  { DispatchCarSP, DecodeSPOperandFunction },
  { DispatchCarImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchCdrFP, DecodeFPOperandFunction },
  { DispatchCdrLP, DecodeLPOperandFunction },
  { DispatchCdrSP, DecodeSPOperandFunction },
  { DispatchCdrImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchEndpFP, DecodeFPOperandFunction },
  { DispatchEndpLP, DecodeLPOperandFunction },
  { DispatchEndpSP, DecodeSPOperandFunction },
  { DispatchEndpImmediate, Decode8BitSignedOperandFunction },
  { DispatchSetup1dArrayFP, DecodeFPOperandFunction },
  { DispatchSetup1dArrayLP, DecodeLPOperandFunction },
  { DispatchSetup1dArraySP, DecodeSPOperandFunction },
  { DispatchSetup1dArrayImmediate, Decode8BitSignedOperandFunction },
  { DispatchSetupForce1dArrayFP, DecodeFPOperandFunction },
  { DispatchSetupForce1dArrayLP, DecodeLPOperandFunction },
  { DispatchSetupForce1dArraySP, DecodeSPOperandFunction },
  { DispatchSetupForce1dArrayImmediate, Decode8BitSignedOperandFunction },
  { DispatchBindLocativeFP, DecodeFPOperandFunction },
  { DispatchBindLocativeLP, DecodeLPOperandFunction },
  { DispatchBindLocativeSP, DecodeSPOperandFunction },
  { DispatchBindLocativeImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchRestoreBindingStackFP, DecodeFPOperandFunction },
  { DispatchRestoreBindingStackLP, DecodeLPOperandFunction },
  { DispatchRestoreBindingStackSP, DecodeSPOperandFunction },
  { DispatchRestoreBindingStackImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchEphemeralpFP, DecodeFPOperandFunction },
  { DispatchEphemeralpLP, DecodeLPOperandFunction },
  { DispatchEphemeralpSP, DecodeSPOperandFunction },
  { DispatchEphemeralpImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchStartCallFP, DecodeFPOperandFunction },
  { DispatchStartCallLP, DecodeLPOperandFunction },
  { DispatchStartCallSP, DecodeSPOperandFunction },
  { DispatchStartCallImmediate, Decode8BitSignedOperandFunction },
  { DispatchJumpFP, DecodeFPOperandFunction },
  { DispatchJumpLP, DecodeLPOperandFunction },
  { DispatchJumpSP, DecodeSPOperandFunction },
  { DispatchJumpImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchTagFP, DecodeFPOperandFunction },
  { DispatchTagLP, DecodeLPOperandFunction },
  { DispatchTagSP, DecodeSPOperandFunction },
  { DispatchTagImmediate, Decode8BitSignedOperandFunction },
  { DispatchDereferenceFP, DecodeFPOperandFunction },
  { DispatchDereferenceLP, DecodeLPOperandFunction },
  { DispatchDereferenceSP, DecodeSPOperandFunction },
  { DispatchDereferenceImmediate, Decode8BitSignedOperandFunction },
  { DispatchLogicTailTestFP, DecodeFPOperandFunction },
  { DispatchLogicTailTestLP, DecodeLPOperandFunction },
  { DispatchLogicTailTestSP, DecodeSPOperandFunction },
  { DispatchLogicTailTestImmediate, Decode8BitSignedOperandFunction },
  { DispatchProcBreakpointFP, DecodeFPOperandFunction },
  { DispatchProcBreakpointLP, DecodeLPOperandFunction },
  { DispatchProcBreakpointSP, DecodeSPOperandFunction },
  { DispatchProcBreakpointImmediate, Decode8BitSignedOperandFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchPushLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPushLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPushLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPushLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchPushLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPushLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPushLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPushLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchPushLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPushLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPushLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPushLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchPushLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPushLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPushLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPushLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchPushLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPushLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPushLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPushLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchPushLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPushLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPushLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPushLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchPushLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPushLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPushLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPushLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchPushLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPushLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPushLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPushLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchBlock0WriteFP, DecodeFPOperandFunction },
  { DispatchBlock0WriteLP, DecodeLPOperandFunction },
  { DispatchBlock0WriteSP, DecodeSPOperandFunction },
  { DispatchBlock0WriteImmediate, Decode8BitSignedOperandFunction },
  { DispatchBlock1WriteFP, DecodeFPOperandFunction },
  { DispatchBlock1WriteLP, DecodeLPOperandFunction },
  { DispatchBlock1WriteSP, DecodeSPOperandFunction },
  { DispatchBlock1WriteImmediate, Decode8BitSignedOperandFunction },
  { DispatchBlock2WriteFP, DecodeFPOperandFunction },
  { DispatchBlock2WriteLP, DecodeLPOperandFunction },
  { DispatchBlock2WriteSP, DecodeSPOperandFunction },
  { DispatchBlock2WriteImmediate, Decode8BitSignedOperandFunction },
  { DispatchBlock3WriteFP, DecodeFPOperandFunction },
  { DispatchBlock3WriteLP, DecodeLPOperandFunction },
  { DispatchBlock3WriteSP, DecodeSPOperandFunction },
  { DispatchBlock3WriteImmediate, Decode8BitSignedOperandFunction },
  { DispatchZeropFP, DecodeFPOperandFunction },
  { DispatchZeropLP, DecodeLPOperandFunction },
  { DispatchZeropSP, DecodeSPOperandFunction },
  { DispatchZeropImmediate, Decode8BitSignedOperandFunction },
  { DispatchMinuspFP, DecodeFPOperandFunction },
  { DispatchMinuspLP, DecodeLPOperandFunction },
  { DispatchMinuspSP, DecodeSPOperandFunction },
  { DispatchMinuspImmediate, Decode8BitSignedOperandFunction },
  { DispatchPluspFP, DecodeFPOperandFunction },
  { DispatchPluspLP, DecodeLPOperandFunction },
  { DispatchPluspSP, DecodeSPOperandFunction },
  { DispatchPluspImmediate, Decode8BitSignedOperandFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMember, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchTypeMemberNoPop, Decode12BitUnsignedOperandFunction },
  { DispatchLocateLocals, DecodeNoneFunction },
  { DispatchLocateLocals, DecodeNoneFunction },
  { DispatchLocateLocals, DecodeNoneFunction },
  { DispatchLocateLocals, DecodeNoneFunction },
  { DispatchCatchClose, DecodeNoneFunction },
  { DispatchCatchClose, DecodeNoneFunction },
  { DispatchCatchClose, DecodeNoneFunction },
  { DispatchCatchClose, DecodeNoneFunction },
  { DispatchGenericDispatch, DecodeNoneFunction },
  { DispatchGenericDispatch, DecodeNoneFunction },
  { DispatchGenericDispatch, DecodeNoneFunction },
  { DispatchGenericDispatch, DecodeNoneFunction },
  { DispatchMessageDispatch, DecodeNoneFunction },
  { DispatchMessageDispatch, DecodeNoneFunction },
  { DispatchMessageDispatch, DecodeNoneFunction },
  { DispatchMessageDispatch, DecodeNoneFunction },
  { DispatchCheckPreemptRequest, DecodeNoneFunction },
  { DispatchCheckPreemptRequest, DecodeNoneFunction },
  { DispatchCheckPreemptRequest, DecodeNoneFunction },
  { DispatchCheckPreemptRequest, DecodeNoneFunction },
  { DispatchPushGlobalLogicVariable, DecodeNoneFunction },
  { DispatchPushGlobalLogicVariable, DecodeNoneFunction },
  { DispatchPushGlobalLogicVariable, DecodeNoneFunction },
  { DispatchPushGlobalLogicVariable, DecodeNoneFunction },
  { DispatchNoOp, DecodeNoneFunction },
  { DispatchNoOp, DecodeNoneFunction },
  { DispatchNoOp, DecodeNoneFunction },
  { DispatchNoOp, DecodeNoneFunction },
  { DispatchHalt, DecodeNoneFunction },
  { DispatchHalt, DecodeNoneFunction },
  { DispatchHalt, DecodeNoneFunction },
  { DispatchHalt, DecodeNoneFunction },
  { DispatchBranchTrue, DecodeBranchOperandFunction },
  { DispatchBranchTrue, DecodeBranchOperandFunction },
  { DispatchBranchTrue, DecodeBranchOperandFunction },
  { DispatchBranchTrue, DecodeBranchOperandFunction },
  { DispatchBranchTrueElseExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueElseExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueElseExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueElseExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueAndExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueAndExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueAndExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueAndExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueNoPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueNoPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueNoPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueNoPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueAndNoPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueAndNoPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueAndNoPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueAndNoPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueElseNoPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueElseNoPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueElseNoPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueElseNoPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueAndNoPopElseNoPopExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueAndNoPopElseNoPopExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueAndNoPopElseNoPopExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchTrueAndNoPopElseNoPopExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalse, DecodeBranchOperandFunction },
  { DispatchBranchFalse, DecodeBranchOperandFunction },
  { DispatchBranchFalse, DecodeBranchOperandFunction },
  { DispatchBranchFalse, DecodeBranchOperandFunction },
  { DispatchBranchFalseElseExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseElseExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseElseExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseElseExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseAndExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseAndExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseAndExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseAndExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseNoPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseNoPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseNoPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseNoPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseAndNoPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseAndNoPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseAndNoPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseAndNoPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseElseNoPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseElseNoPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseElseNoPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseElseNoPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseAndNoPopElseNoPopExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseAndNoPopElseNoPopExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseAndNoPopElseNoPopExtraPop, DecodeBranchOperandFunction },
  { DispatchBranchFalseAndNoPopElseNoPopExtraPop, DecodeBranchOperandFunction },
  { DispatchPushFP, DecodeFPOperandFunction },
  { DispatchPushLP, DecodeLPOperandFunction },
  { DispatchPushSP, DecodeSPOperandFunction },
  { DispatchPushImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchPushNNils, Decode8BitUnsignedOperandFunction },
  { DispatchPushNNils, Decode8BitUnsignedOperandFunction },
  { DispatchPushNNils, Decode8BitUnsignedOperandFunction },
  { DispatchPushNNils, Decode8BitUnsignedOperandFunction },
  { DispatchPushAddressSpRelativeFP, DecodeFPOperandFunction },
  { DispatchPushAddressSpRelativeLP, DecodeLPOperandFunction },
  { DispatchPushAddressSpRelativeSP, DecodeSPOperandFunction },
  { DispatchPushAddressSpRelativeImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchPushLocalLogicVariablesFP, DecodeFPOperandFunction },
  { DispatchPushLocalLogicVariablesLP, DecodeLPOperandFunction },
  { DispatchPushLocalLogicVariablesSP, DecodeSPOperandFunction },
  { DispatchPushLocalLogicVariablesImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchReturnMultipleFP, DecodeFPOperandFunction },
  { DispatchReturnMultipleLP, DecodeLPOperandFunction },
  { DispatchReturnMultipleSP, DecodeSPOperandFunction },
  { DispatchReturnMultipleImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchReturnKludgeFP, DecodeFPOperandFunction },
  { DispatchReturnKludgeLP, DecodeLPOperandFunction },
  { DispatchReturnKludgeSP, DecodeSPOperandFunction },
  { DispatchReturnKludgeImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchTakeValues, Decode8BitUnsignedOperandFunction },
  { DispatchTakeValues, Decode8BitUnsignedOperandFunction },
  { DispatchTakeValues, Decode8BitUnsignedOperandFunction },
  { DispatchTakeValues, Decode8BitUnsignedOperandFunction },
  { DispatchIllegalInstruction, Decode8BitUnsignedOperandFunction },
  { DispatchIllegalInstruction, Decode8BitUnsignedOperandFunction },
  { DispatchIllegalInstruction, Decode8BitUnsignedOperandFunction },
  { DispatchUnbindNImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchPushInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchPushInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchPushInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchPushInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchPushAddressInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchPushAddressInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchPushAddressInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchPushAddressInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchPushInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchPushInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchPushInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchPushInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchPushAddressInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchPushAddressInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchPushAddressInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchPushAddressInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchUnaryMinusFP, DecodeFPOperandFunction },
  { DispatchUnaryMinusLP, DecodeLPOperandFunction },
  { DispatchUnaryMinusSP, DecodeSPOperandFunction },
  { DispatchUnaryMinusImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchReturnSingleTOS, DecodeReturnOperandFunction },
  { DispatchReturnSingleTOS, DecodeReturnOperandFunction },
  { DispatchReturnSingleTOS, DecodeReturnOperandFunction },
  { DispatchReturnSingleTOS, DecodeReturnOperandFunction },
  { DispatchMemoryRead, Decode10BitUnsignedOperandFunction },
  { DispatchMemoryRead, Decode10BitUnsignedOperandFunction },
  { DispatchMemoryRead, Decode10BitUnsignedOperandFunction },
  { DispatchMemoryRead, Decode10BitUnsignedOperandFunction },
  { DispatchMemoryReadAddress, Decode10BitUnsignedOperandFunction },
  { DispatchMemoryReadAddress, Decode10BitUnsignedOperandFunction },
  { DispatchMemoryReadAddress, Decode10BitUnsignedOperandFunction },
  { DispatchMemoryReadAddress, Decode10BitUnsignedOperandFunction },
  { DispatchBlock0Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock0Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock0Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock0Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock1Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock1Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock1Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock1Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock2Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock2Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock2Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock2Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock3Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock3Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock3Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock3Read, Decode10BitUnsignedOperandFunction },
  { DispatchBlock0ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock0ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock0ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock0ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock1ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock1ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock1ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock1ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock2ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock2ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock2ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock2ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock3ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock3ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock3ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock3ReadShift, Decode10BitUnsignedOperandFunction },
  { DispatchBlock0ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchBlock0ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchBlock0ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchBlock0ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchBlock1ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchBlock1ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchBlock1ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchBlock1ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchBlock2ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchBlock2ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchBlock2ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchBlock2ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchBlock3ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchBlock3ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchBlock3ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchBlock3ReadTest, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallN, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallN, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallN, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallN, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallNApply, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallNApply, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallNApply, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallNApply, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallTos, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallTos, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallTos, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallTos, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallTosApply, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallTosApply, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallTosApply, Decode10BitUnsignedOperandFunction },
  { DispatchFinishCallTosApply, Decode10BitUnsignedOperandFunction },
  { DispatchSetToCarFP, DecodeFPOperandFunction },
  { DispatchSetToCarLP, DecodeLPOperandFunction },
  { DispatchSetToCarSP, DecodeSPOperandFunction },
  { DispatchSetToCarImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchSetToCdrFP, DecodeFPOperandFunction },
  { DispatchSetToCdrLP, DecodeLPOperandFunction },
  { DispatchSetToCdrSP, DecodeSPOperandFunction },
  { DispatchSetToCdrImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchSetToCdrPushCarFP, DecodeFPOperandFunction },
  { DispatchSetToCdrPushCarLP, DecodeLPOperandFunction },
  { DispatchSetToCdrPushCarSP, DecodeSPOperandFunction },
  { DispatchSetToCdrPushCarImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchIncrementFP, DecodeFPOperandFunction },
  { DispatchIncrementLP, DecodeLPOperandFunction },
  { DispatchIncrementSP, DecodeSPOperandFunction },
  { DispatchIncrementImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchDecrementFP, DecodeFPOperandFunction },
  { DispatchDecrementLP, DecodeLPOperandFunction },
  { DispatchDecrementSP, DecodeSPOperandFunction },
  { DispatchDecrementImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchPointerIncrementFP, DecodeFPOperandFunction },
  { DispatchPointerIncrementLP, DecodeLPOperandFunction },
  { DispatchPointerIncrementSP, DecodeSPOperandFunction },
  { DispatchPointerIncrementImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchSetCdrCode1FP, DecodeFPOperandFunction },
  { DispatchSetCdrCode1LP, DecodeLPOperandFunction },
  { DispatchSetCdrCode1SP, DecodeSPOperandFunction },
  { DispatchSetCdrCode1Immediate, Decode8BitUnsignedOperandFunction },
  { DispatchSetCdrCode2FP, DecodeFPOperandFunction },
  { DispatchSetCdrCode2LP, DecodeLPOperandFunction },
  { DispatchSetCdrCode2SP, DecodeSPOperandFunction },
  { DispatchSetCdrCode2Immediate, Decode8BitUnsignedOperandFunction },
  { DispatchPushAddressFP, DecodeFPOperandFunction },
  { DispatchPushAddressLP, DecodeLPOperandFunction },
  { DispatchPushAddressSP, DecodeSPOperandFunction },
  { DispatchPushAddressImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchSetSpToAddressFP, DecodeFPOperandFunction },
  { DispatchSetSpToAddressLP, DecodeLPOperandFunction },
  { DispatchSetSpToAddressSP, DecodeSPOperandFunction },
  { DispatchSetSpToAddressImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchSetSpToAddressSaveTosFP, DecodeFPOperandFunction },
  { DispatchSetSpToAddressSaveTosLP, DecodeLPOperandFunction },
  { DispatchSetSpToAddressSaveTosSP, DecodeSPOperandFunction },
  { DispatchSetSpToAddressSaveTosImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchReadInternalRegister, Decode10BitUnsignedOperandFunction },
  { DispatchReadInternalRegister, Decode10BitUnsignedOperandFunction },
  { DispatchReadInternalRegister, Decode10BitUnsignedOperandFunction },
  { DispatchReadInternalRegister, Decode10BitUnsignedOperandFunction },
  { DispatchWriteInternalRegister, Decode10BitUnsignedOperandFunction },
  { DispatchWriteInternalRegister, Decode10BitUnsignedOperandFunction },
  { DispatchWriteInternalRegister, Decode10BitUnsignedOperandFunction },
  { DispatchWriteInternalRegister, Decode10BitUnsignedOperandFunction },
  { DispatchCoprocessorRead, Decode10BitUnsignedOperandFunction },
  { DispatchCoprocessorRead, Decode10BitUnsignedOperandFunction },
  { DispatchCoprocessorRead, Decode10BitUnsignedOperandFunction },
  { DispatchCoprocessorRead, Decode10BitUnsignedOperandFunction },
  { DispatchCoprocessorWrite, Decode10BitUnsignedOperandFunction },
  { DispatchCoprocessorWrite, Decode10BitUnsignedOperandFunction },
  { DispatchCoprocessorWrite, Decode10BitUnsignedOperandFunction },
  { DispatchCoprocessorWrite, Decode10BitUnsignedOperandFunction },
  { DispatchBlock0ReadAluFP, DecodeFPOperandFunction },
  { DispatchBlock0ReadAluLP, DecodeLPOperandFunction },
  { DispatchBlock0ReadAluSP, DecodeSPOperandFunction },
  { DispatchBlock0ReadAluImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchBlock1ReadAluFP, DecodeFPOperandFunction },
  { DispatchBlock1ReadAluLP, DecodeLPOperandFunction },
  { DispatchBlock1ReadAluSP, DecodeSPOperandFunction },
  { DispatchBlock1ReadAluImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchBlock2ReadAluFP, DecodeFPOperandFunction },
  { DispatchBlock2ReadAluLP, DecodeLPOperandFunction },
  { DispatchBlock2ReadAluSP, DecodeSPOperandFunction },
  { DispatchBlock2ReadAluImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchBlock3ReadAluFP, DecodeFPOperandFunction },
  { DispatchBlock3ReadAluLP, DecodeLPOperandFunction },
  { DispatchBlock3ReadAluSP, DecodeSPOperandFunction },
  { DispatchBlock3ReadAluImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchLdb, Decode10BitUnsignedOperandFunction },
  { DispatchLdb, Decode10BitUnsignedOperandFunction },
  { DispatchLdb, Decode10BitUnsignedOperandFunction },
  { DispatchLdb, Decode10BitUnsignedOperandFunction },
  { DispatchCharLdb, Decode10BitUnsignedOperandFunction },
  { DispatchCharLdb, Decode10BitUnsignedOperandFunction },
  { DispatchCharLdb, Decode10BitUnsignedOperandFunction },
  { DispatchCharLdb, Decode10BitUnsignedOperandFunction },
  { DispatchPLdb, Decode10BitUnsignedOperandFunction },
  { DispatchPLdb, Decode10BitUnsignedOperandFunction },
  { DispatchPLdb, Decode10BitUnsignedOperandFunction },
  { DispatchPLdb, Decode10BitUnsignedOperandFunction },
  { DispatchPTagLdb, Decode10BitUnsignedOperandFunction },
  { DispatchPTagLdb, Decode10BitUnsignedOperandFunction },
  { DispatchPTagLdb, Decode10BitUnsignedOperandFunction },
  { DispatchPTagLdb, Decode10BitUnsignedOperandFunction },
  { DispatchBranch, DecodeBranchOperandFunction },
  { DispatchBranch, DecodeBranchOperandFunction },
  { DispatchBranch, DecodeBranchOperandFunction },
  { DispatchBranch, DecodeBranchOperandFunction },
  { DispatchLoopDecrementTos, DecodeBranchOperandFunction },
  { DispatchLoopDecrementTos, DecodeBranchOperandFunction },
  { DispatchLoopDecrementTos, DecodeBranchOperandFunction },
  { DispatchLoopDecrementTos, DecodeBranchOperandFunction },
  { DispatchEntryRestAccepted, DecodeEntryOperandFunction },
  { DispatchEntryRestAccepted, DecodeEntryOperandFunction },
  { DispatchEntryRestAccepted, DecodeEntryOperandFunction },
  { DispatchEntryRestAccepted, DecodeEntryOperandFunction },
  { DispatchEntryRestNotAccepted, DecodeEntryOperandFunction },
  { DispatchEntryRestNotAccepted, DecodeEntryOperandFunction },
  { DispatchEntryRestNotAccepted, DecodeEntryOperandFunction },
  { DispatchEntryRestNotAccepted, DecodeEntryOperandFunction },
  { DispatchRplacaFP, DecodeFPOperandFunction },
  { DispatchRplacaLP, DecodeLPOperandFunction },
  { DispatchRplacaSP, DecodeSPOperandFunction },
  { DispatchRplacaImmediate, Decode8BitSignedOperandFunction },
  { DispatchRplacdFP, DecodeFPOperandFunction },
  { DispatchRplacdLP, DecodeLPOperandFunction },
  { DispatchRplacdSP, DecodeSPOperandFunction },
  { DispatchRplacdImmediate, Decode8BitSignedOperandFunction },
  { DispatchMultiplyFP, DecodeFPOperandFunction },
  { DispatchMultiplyLP, DecodeLPOperandFunction },
  { DispatchMultiplySP, DecodeSPOperandFunction },
  { DispatchMultiplyImmediate, Decode8BitSignedOperandFunction },
  { DispatchQuotientFP, DecodeFPOperandFunction },
  { DispatchQuotientLP, DecodeLPOperandFunction },
  { DispatchQuotientSP, DecodeSPOperandFunction },
  { DispatchQuotientImmediate, Decode8BitSignedOperandFunction },
  { DispatchCeilingFP, DecodeFPOperandFunction },
  { DispatchCeilingLP, DecodeLPOperandFunction },
  { DispatchCeilingSP, DecodeSPOperandFunction },
  { DispatchCeilingImmediate, Decode8BitSignedOperandFunction },
  { DispatchFloorFP, DecodeFPOperandFunction },
  { DispatchFloorLP, DecodeLPOperandFunction },
  { DispatchFloorSP, DecodeSPOperandFunction },
  { DispatchFloorImmediate, Decode8BitSignedOperandFunction },
  { DispatchTruncateFP, DecodeFPOperandFunction },
  { DispatchTruncateLP, DecodeLPOperandFunction },
  { DispatchTruncateSP, DecodeSPOperandFunction },
  { DispatchTruncateImmediate, Decode8BitSignedOperandFunction },
  { DispatchRoundFP, DecodeFPOperandFunction },
  { DispatchRoundLP, DecodeLPOperandFunction },
  { DispatchRoundSP, DecodeSPOperandFunction },
  { DispatchRoundImmediate, Decode8BitSignedOperandFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchRationalQuotientFP, DecodeFPOperandFunction },
  { DispatchRationalQuotientLP, DecodeLPOperandFunction },
  { DispatchRationalQuotientSP, DecodeSPOperandFunction },
  { DispatchRationalQuotientImmediate, Decode8BitSignedOperandFunction },
  { DispatchMinFP, DecodeFPOperandFunction },
  { DispatchMinLP, DecodeLPOperandFunction },
  { DispatchMinSP, DecodeSPOperandFunction },
  { DispatchMinImmediate, Decode8BitSignedOperandFunction },
  { DispatchMaxFP, DecodeFPOperandFunction },
  { DispatchMaxLP, DecodeLPOperandFunction },
  { DispatchMaxSP, DecodeSPOperandFunction },
  { DispatchMaxImmediate, Decode8BitSignedOperandFunction },
  { DispatchAluFP, DecodeFPOperandFunction },
  { DispatchAluLP, DecodeLPOperandFunction },
  { DispatchAluSP, DecodeSPOperandFunction },
  { DispatchAluImmediate, Decode8BitSignedOperandFunction },
  { DispatchLogandFP, DecodeFPOperandFunction },
  { DispatchLogandLP, DecodeLPOperandFunction },
  { DispatchLogandSP, DecodeSPOperandFunction },
  { DispatchLogandImmediate, Decode8BitSignedOperandFunction },
  { DispatchLogxorFP, DecodeFPOperandFunction },
  { DispatchLogxorLP, DecodeLPOperandFunction },
  { DispatchLogxorSP, DecodeSPOperandFunction },
  { DispatchLogxorImmediate, Decode8BitSignedOperandFunction },
  { DispatchLogiorFP, DecodeFPOperandFunction },
  { DispatchLogiorLP, DecodeLPOperandFunction },
  { DispatchLogiorSP, DecodeSPOperandFunction },
  { DispatchLogiorImmediate, Decode8BitSignedOperandFunction },
  { DispatchRotFP, DecodeFPOperandFunction },
  { DispatchRotLP, DecodeLPOperandFunction },
  { DispatchRotSP, DecodeSPOperandFunction },
  { DispatchRotImmediate, Decode8BitSignedOperandFunction },
  { DispatchLshFP, DecodeFPOperandFunction },
  { DispatchLshLP, DecodeLPOperandFunction },
  { DispatchLshSP, DecodeSPOperandFunction },
  { DispatchLshImmediate, Decode8BitSignedOperandFunction },
  { DispatchMultiplyDoubleFP, DecodeFPOperandFunction },
  { DispatchMultiplyDoubleLP, DecodeLPOperandFunction },
  { DispatchMultiplyDoubleSP, DecodeSPOperandFunction },
  { DispatchMultiplyDoubleImmediate, Decode8BitSignedOperandFunction },
  { DispatchLshcBignumStepFP, DecodeFPOperandFunction },
  { DispatchLshcBignumStepLP, DecodeLPOperandFunction },
  { DispatchLshcBignumStepSP, DecodeSPOperandFunction },
  { DispatchLshcBignumStepImmediate, Decode8BitSignedOperandFunction },
  { DispatchStackBltFP, DecodeFPOperandFunction },
  { DispatchStackBltLP, DecodeLPOperandFunction },
  { DispatchStackBltSP, DecodeSPOperandFunction },
  { DispatchStackBltImmediate, Decode8BitSignedOperandFunction },
  { DispatchRgetfFP, DecodeFPOperandFunction },
  { DispatchRgetfLP, DecodeLPOperandFunction },
  { DispatchRgetfSP, DecodeSPOperandFunction },
  { DispatchRgetfImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchMemberFP, DecodeFPOperandFunction },
  { DispatchMemberLP, DecodeLPOperandFunction },
  { DispatchMemberSP, DecodeSPOperandFunction },
  { DispatchMemberImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchAssocFP, DecodeFPOperandFunction },
  { DispatchAssocLP, DecodeLPOperandFunction },
  { DispatchAssocSP, DecodeSPOperandFunction },
  { DispatchAssocImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchPointerPlusFP, DecodeFPOperandFunction },
  { DispatchPointerPlusLP, DecodeLPOperandFunction },
  { DispatchPointerPlusSP, DecodeSPOperandFunction },
  { DispatchPointerPlusImmediate, Decode8BitSignedOperandFunction },
  { DispatchPointerDifferenceFP, DecodeFPOperandFunction },
  { DispatchPointerDifferenceLP, DecodeLPOperandFunction },
  { DispatchPointerDifferenceSP, DecodeSPOperandFunction },
  { DispatchPointerDifferenceImmediate, Decode8BitSignedOperandFunction },
  { DispatchAshFP, DecodeFPOperandFunction },
  { DispatchAshLP, DecodeLPOperandFunction },
  { DispatchAshSP, DecodeSPOperandFunction },
  { DispatchAshImmediate, Decode8BitSignedOperandFunction },
  { DispatchStoreConditionalFP, DecodeFPOperandFunction },
  { DispatchStoreConditionalLP, DecodeLPOperandFunction },
  { DispatchStoreConditionalSP, DecodeSPOperandFunction },
  { DispatchStoreConditionalImmediate, Decode8BitSignedOperandFunction },
  { DispatchMemoryWriteFP, DecodeFPOperandFunction },
  { DispatchMemoryWriteLP, DecodeLPOperandFunction },
  { DispatchMemoryWriteSP, DecodeSPOperandFunction },
  { DispatchMemoryWriteImmediate, Decode8BitSignedOperandFunction },
  { DispatchPStoreContentsFP, DecodeFPOperandFunction },
  { DispatchPStoreContentsLP, DecodeLPOperandFunction },
  { DispatchPStoreContentsSP, DecodeSPOperandFunction },
  { DispatchPStoreContentsImmediate, Decode8BitSignedOperandFunction },
  { DispatchBindLocativeToValueFP, DecodeFPOperandFunction },
  { DispatchBindLocativeToValueLP, DecodeLPOperandFunction },
  { DispatchBindLocativeToValueSP, DecodeSPOperandFunction },
  { DispatchBindLocativeToValueImmediate, Decode8BitSignedOperandFunction },
  { DispatchUnifyFP, DecodeFPOperandFunction },
  { DispatchUnifyLP, DecodeLPOperandFunction },
  { DispatchUnifySP, DecodeSPOperandFunction },
  { DispatchUnifyImmediate, Decode8BitSignedOperandFunction },
  { DispatchPopLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPopLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPopLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPopLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchPopLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPopLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPopLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPopLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchPopLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPopLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPopLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPopLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchPopLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPopLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPopLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPopLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchPopLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPopLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPopLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPopLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchPopLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPopLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPopLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPopLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchPopLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPopLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPopLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPopLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchPopLexicalVarFP, DecodeFPOperandFunction },
  { DispatchPopLexicalVarLP, DecodeLPOperandFunction },
  { DispatchPopLexicalVarSP, DecodeSPOperandFunction },
  { DispatchPopLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchMovemLexicalVarFP, DecodeFPOperandFunction },
  { DispatchMovemLexicalVarLP, DecodeLPOperandFunction },
  { DispatchMovemLexicalVarSP, DecodeSPOperandFunction },
  { DispatchMovemLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchMovemLexicalVarFP, DecodeFPOperandFunction },
  { DispatchMovemLexicalVarLP, DecodeLPOperandFunction },
  { DispatchMovemLexicalVarSP, DecodeSPOperandFunction },
  { DispatchMovemLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchMovemLexicalVarFP, DecodeFPOperandFunction },
  { DispatchMovemLexicalVarLP, DecodeLPOperandFunction },
  { DispatchMovemLexicalVarSP, DecodeSPOperandFunction },
  { DispatchMovemLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchMovemLexicalVarFP, DecodeFPOperandFunction },
  { DispatchMovemLexicalVarLP, DecodeLPOperandFunction },
  { DispatchMovemLexicalVarSP, DecodeSPOperandFunction },
  { DispatchMovemLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchMovemLexicalVarFP, DecodeFPOperandFunction },
  { DispatchMovemLexicalVarLP, DecodeLPOperandFunction },
  { DispatchMovemLexicalVarSP, DecodeSPOperandFunction },
  { DispatchMovemLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchMovemLexicalVarFP, DecodeFPOperandFunction },
  { DispatchMovemLexicalVarLP, DecodeLPOperandFunction },
  { DispatchMovemLexicalVarSP, DecodeSPOperandFunction },
  { DispatchMovemLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchMovemLexicalVarFP, DecodeFPOperandFunction },
  { DispatchMovemLexicalVarLP, DecodeLPOperandFunction },
  { DispatchMovemLexicalVarSP, DecodeSPOperandFunction },
  { DispatchMovemLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchMovemLexicalVarFP, DecodeFPOperandFunction },
  { DispatchMovemLexicalVarLP, DecodeLPOperandFunction },
  { DispatchMovemLexicalVarSP, DecodeSPOperandFunction },
  { DispatchMovemLexicalVarImmediate, Decode8BitSignedOperandFunction },
  { DispatchEqualNumberFP, DecodeFPOperandFunction },
  { DispatchEqualNumberLP, DecodeLPOperandFunction },
  { DispatchEqualNumberSP, DecodeSPOperandFunction },
  { DispatchEqualNumberImmediate, Decode8BitSignedOperandFunction },
  { DispatchLesspFP, DecodeFPOperandFunction },
  { DispatchLesspLP, DecodeLPOperandFunction },
  { DispatchLesspSP, DecodeSPOperandFunction },
  { DispatchLesspImmediate, Decode8BitSignedOperandFunction },
  { DispatchGreaterpFP, DecodeFPOperandFunction },
  { DispatchGreaterpLP, DecodeLPOperandFunction },
  { DispatchGreaterpSP, DecodeSPOperandFunction },
  { DispatchGreaterpImmediate, Decode8BitSignedOperandFunction },
  { DispatchEqlFP, DecodeFPOperandFunction },
  { DispatchEqlLP, DecodeLPOperandFunction },
  { DispatchEqlSP, DecodeSPOperandFunction },
  { DispatchEqlImmediate, Decode8BitSignedOperandFunction },
  { DispatchEqualNumberNoPopFP, DecodeFPOperandFunction },
  { DispatchEqualNumberNoPopLP, DecodeLPOperandFunction },
  { DispatchEqualNumberNoPopSP, DecodeSPOperandFunction },
  { DispatchEqualNumberNoPopImmediate, Decode8BitSignedOperandFunction },
  { DispatchLesspNoPopFP, DecodeFPOperandFunction },
  { DispatchLesspNoPopLP, DecodeLPOperandFunction },
  { DispatchLesspNoPopSP, DecodeSPOperandFunction },
  { DispatchLesspNoPopImmediate, Decode8BitSignedOperandFunction },
  { DispatchGreaterpNoPopFP, DecodeFPOperandFunction },
  { DispatchGreaterpNoPopLP, DecodeLPOperandFunction },
  { DispatchGreaterpNoPopSP, DecodeSPOperandFunction },
  { DispatchGreaterpNoPopImmediate, Decode8BitSignedOperandFunction },
  { DispatchEqlNoPopFP, DecodeFPOperandFunction },
  { DispatchEqlNoPopLP, DecodeLPOperandFunction },
  { DispatchEqlNoPopSP, DecodeSPOperandFunction },
  { DispatchEqlNoPopImmediate, Decode8BitSignedOperandFunction },
  { DispatchEqFP, DecodeFPOperandFunction },
  { DispatchEqLP, DecodeLPOperandFunction },
  { DispatchEqSP, DecodeSPOperandFunction },
  { DispatchEqImmediate, Decode8BitSignedOperandFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchLogtestFP, DecodeFPOperandFunction },
  { DispatchLogtestLP, DecodeLPOperandFunction },
  { DispatchLogtestSP, DecodeSPOperandFunction },
  { DispatchLogtestImmediate, Decode8BitSignedOperandFunction },
  { DispatchEqNoPopFP, DecodeFPOperandFunction },
  { DispatchEqNoPopLP, DecodeLPOperandFunction },
  { DispatchEqNoPopSP, DecodeSPOperandFunction },
  { DispatchEqNoPopImmediate, Decode8BitSignedOperandFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchLogtestNoPopFP, DecodeFPOperandFunction },
  { DispatchLogtestNoPopLP, DecodeLPOperandFunction },
  { DispatchLogtestNoPopSP, DecodeSPOperandFunction },
  { DispatchLogtestNoPopImmediate, Decode8BitSignedOperandFunction },
  { DispatchAddFP, DecodeFPOperandFunction },
  { DispatchAddLP, DecodeLPOperandFunction },
  { DispatchAddSP, DecodeSPOperandFunction },
  { DispatchAddImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchSubFP, DecodeFPOperandFunction },
  { DispatchSubLP, DecodeLPOperandFunction },
  { DispatchSubSP, DecodeSPOperandFunction },
  { DispatchSubImmediate, Decode8BitUnsignedOperandFunction },
  { Dispatch32BitPlusFP, DecodeFPOperandFunction },
  { Dispatch32BitPlusLP, DecodeLPOperandFunction },
  { Dispatch32BitPlusSP, DecodeSPOperandFunction },
  { Dispatch32BitPlusImmediate, Decode8BitUnsignedOperandFunction },
  { Dispatch32BitDifferenceFP, DecodeFPOperandFunction },
  { Dispatch32BitDifferenceLP, DecodeLPOperandFunction },
  { Dispatch32BitDifferenceSP, DecodeSPOperandFunction },
  { Dispatch32BitDifferenceImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchAddBignumStepFP, DecodeFPOperandFunction },
  { DispatchAddBignumStepLP, DecodeLPOperandFunction },
  { DispatchAddBignumStepSP, DecodeSPOperandFunction },
  { DispatchAddBignumStepImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchSubBignumStepFP, DecodeFPOperandFunction },
  { DispatchSubBignumStepLP, DecodeLPOperandFunction },
  { DispatchSubBignumStepSP, DecodeSPOperandFunction },
  { DispatchSubBignumStepImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchMultiplyBignumStepFP, DecodeFPOperandFunction },
  { DispatchMultiplyBignumStepLP, DecodeLPOperandFunction },
  { DispatchMultiplyBignumStepSP, DecodeSPOperandFunction },
  { DispatchMultiplyBignumStepImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchDivideBignumStepFP, DecodeFPOperandFunction },
  { DispatchDivideBignumStepLP, DecodeLPOperandFunction },
  { DispatchDivideBignumStepSP, DecodeSPOperandFunction },
  { DispatchDivideBignumStepImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchAset1FP, DecodeFPOperandFunction },
  { DispatchAset1LP, DecodeLPOperandFunction },
  { DispatchAset1SP, DecodeSPOperandFunction },
  { DispatchAset1Immediate, Decode8BitUnsignedOperandFunction },
  { DispatchAllocateListBlockFP, DecodeFPOperandFunction },
  { DispatchAllocateListBlockLP, DecodeLPOperandFunction },
  { DispatchAllocateListBlockSP, DecodeSPOperandFunction },
  { DispatchAllocateListBlockImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchAref1FP, DecodeFPOperandFunction },
  { DispatchAref1LP, DecodeLPOperandFunction },
  { DispatchAref1SP, DecodeSPOperandFunction },
  { DispatchAref1Immediate, Decode8BitUnsignedOperandFunction },
  { DispatchAloc1FP, DecodeFPOperandFunction },
  { DispatchAloc1LP, DecodeLPOperandFunction },
  { DispatchAloc1SP, DecodeSPOperandFunction },
  { DispatchAloc1Immediate, Decode8BitUnsignedOperandFunction },
  { DispatchStoreArrayLeaderFP, DecodeFPOperandFunction },
  { DispatchStoreArrayLeaderLP, DecodeLPOperandFunction },
  { DispatchStoreArrayLeaderSP, DecodeSPOperandFunction },
  { DispatchStoreArrayLeaderImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchAllocateStructureBlockFP, DecodeFPOperandFunction },
  { DispatchAllocateStructureBlockLP, DecodeLPOperandFunction },
  { DispatchAllocateStructureBlockSP, DecodeSPOperandFunction },
  { DispatchAllocateStructureBlockImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchArrayLeaderFP, DecodeFPOperandFunction },
  { DispatchArrayLeaderLP, DecodeLPOperandFunction },
  { DispatchArrayLeaderSP, DecodeSPOperandFunction },
  { DispatchArrayLeaderImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchAlocLeaderFP, DecodeFPOperandFunction },
  { DispatchAlocLeaderLP, DecodeLPOperandFunction },
  { DispatchAlocLeaderSP, DecodeSPOperandFunction },
  { DispatchAlocLeaderImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchPopInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchPopInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchPopInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchPopInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchMovemInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchMovemInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchMovemInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchMovemInstanceVariable, Decode8BitUnsignedOperandFunction },
  { DispatchPopInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchPopInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchPopInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchPopInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchMovemInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchMovemInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchMovemInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchMovemInstanceVariableOrdered, Decode8BitUnsignedOperandFunction },
  { DispatchInstanceRefFP, DecodeFPOperandFunction },
  { DispatchInstanceRefLP, DecodeLPOperandFunction },
  { DispatchInstanceRefSP, DecodeSPOperandFunction },
  { DispatchInstanceRefImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchInstanceSetFP, DecodeFPOperandFunction },
  { DispatchInstanceSetLP, DecodeLPOperandFunction },
  { DispatchInstanceSetSP, DecodeSPOperandFunction },
  { DispatchInstanceSetImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchInstanceLocFP, DecodeFPOperandFunction },
  { DispatchInstanceLocLP, DecodeLPOperandFunction },
  { DispatchInstanceLocSP, DecodeSPOperandFunction },
  { DispatchInstanceLocImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchSetTagFP, DecodeFPOperandFunction },
  { DispatchSetTagLP, DecodeLPOperandFunction },
  { DispatchSetTagSP, DecodeSPOperandFunction },
  { DispatchSetTagImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchUnsignedLesspFP, DecodeFPOperandFunction },
  { DispatchUnsignedLesspLP, DecodeLPOperandFunction },
  { DispatchUnsignedLesspSP, DecodeSPOperandFunction },
  { DispatchUnsignedLesspImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchUnsignedLesspNoPopFP, DecodeFPOperandFunction },
  { DispatchUnsignedLesspNoPopLP, DecodeLPOperandFunction },
  { DispatchUnsignedLesspNoPopSP, DecodeSPOperandFunction },
  { DispatchUnsignedLesspNoPopImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchPopFP, DecodeFPOperandFunction },
  { DispatchPopLP, DecodeLPOperandFunction },
  { DispatchPopSP, DecodeSPOperandFunction },
  { DispatchPopImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchMovemFP, DecodeFPOperandFunction },
  { DispatchMovemLP, DecodeLPOperandFunction },
  { DispatchMovemSP, DecodeSPOperandFunction },
  { DispatchMovemImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchMergeCdrNoPopFP, DecodeFPOperandFunction },
  { DispatchMergeCdrNoPopLP, DecodeLPOperandFunction },
  { DispatchMergeCdrNoPopSP, DecodeSPOperandFunction },
  { DispatchMergeCdrNoPopImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchFastAref1FP, DecodeFPOperandFunction },
  { DispatchFastAref1LP, DecodeLPOperandFunction },
  { DispatchFastAref1SP, DecodeSPOperandFunction },
  { DispatchFastAref1Immediate, Decode8BitUnsignedOperandFunction },
  { DispatchFastAset1FP, DecodeFPOperandFunction },
  { DispatchFastAset1LP, DecodeLPOperandFunction },
  { DispatchFastAset1SP, DecodeSPOperandFunction },
  { DispatchFastAset1Immediate, Decode8BitUnsignedOperandFunction },
  { DispatchStackBltAddressFP, DecodeFPOperandFunction },
  { DispatchStackBltAddressLP, DecodeLPOperandFunction },
  { DispatchStackBltAddressSP, DecodeSPOperandFunction },
  { DispatchStackBltAddressImmediate, Decode8BitUnsignedOperandFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchDpb, Decode10BitUnsignedOperandFunction },
  { DispatchDpb, Decode10BitUnsignedOperandFunction },
  { DispatchDpb, Decode10BitUnsignedOperandFunction },
  { DispatchDpb, Decode10BitUnsignedOperandFunction },
  { DispatchCharDpb, Decode10BitUnsignedOperandFunction },
  { DispatchCharDpb, Decode10BitUnsignedOperandFunction },
  { DispatchCharDpb, Decode10BitUnsignedOperandFunction },
  { DispatchCharDpb, Decode10BitUnsignedOperandFunction },
  { DispatchPDpb, Decode10BitUnsignedOperandFunction },
  { DispatchPDpb, Decode10BitUnsignedOperandFunction },
  { DispatchPDpb, Decode10BitUnsignedOperandFunction },
  { DispatchPDpb, Decode10BitUnsignedOperandFunction },
  { DispatchPTagDpb, Decode10BitUnsignedOperandFunction },
  { DispatchPTagDpb, Decode10BitUnsignedOperandFunction },
  { DispatchPTagDpb, Decode10BitUnsignedOperandFunction },
  { DispatchPTagDpb, Decode10BitUnsignedOperandFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchIllegalInstruction, DecodeNoneFunction },
  { DispatchLoopIncrementTosLessThan, DecodeBranchOperandFunction },
  { DispatchLoopIncrementTosLessThan, DecodeBranchOperandFunction },
  { DispatchLoopIncrementTosLessThan, DecodeBranchOperandFunction },
  { DispatchLoopIncrementTosLessThan, DecodeBranchOperandFunction },
  { DispatchCatchOpen, Decode8BitUnsignedOperandFunction },
  { DispatchCatchOpen, Decode8BitUnsignedOperandFunction },
  { DispatchCatchOpen, Decode8BitUnsignedOperandFunction },
  { DispatchCatchOpen, Decode8BitUnsignedOperandFunction },
  { DispatchHack, Decode10BitUnsignedOperandFunction },
  { DispatchHack, Decode10BitUnsignedOperandFunction },
  { DispatchHack, Decode10BitUnsignedOperandFunction },
  { DispatchHack, Decode10BitUnsignedOperandFunction },
};

const char *ivory_dispatch_names[] = {
  "CarFP",
  "CarLP",
  "CarSP",
  "CarImmediate",
  "CarPop",
  "CdrFP",
  "CdrLP",
  "CdrSP",
  "CdrImmediate",
  "CdrPop",
  "EndpFP",
  "EndpLP",
  "EndpSP",
  "EndpImmediate",
  "EndpPop",
  "Setup1dArrayFP",
  "Setup1dArrayLP",
  "Setup1dArraySP",
  "Setup1dArrayImmediate",
  "Setup1dArrayPop",
  "SetupForce1dArrayFP",
  "SetupForce1dArrayLP",
  "SetupForce1dArraySP",
  "SetupForce1dArrayImmediate",
  "SetupForce1dArrayPop",
  "BindLocativeFP",
  "BindLocativeLP",
  "BindLocativeSP",
  "BindLocativeImmediate",
  "BindLocativePop",
  "RestoreBindingStackFP",
  "RestoreBindingStackLP",
  "RestoreBindingStackSP",
  "RestoreBindingStackImmediate",
  "RestoreBindingStackPop",
  "EphemeralpFP",
  "EphemeralpLP",
  "EphemeralpSP",
  "EphemeralpImmediate",
  "EphemeralpPop",
  "StartCallFP",
  "StartCallLP",
  "StartCallSP",
  "StartCallImmediate",
  "StartCallPop",
  "JumpFP",
  "JumpLP",
  "JumpSP",
  "JumpImmediate",
  "JumpPop",
  "TagFP",
  "TagLP",
  "TagSP",
  "TagImmediate",
  "TagPop",
  "DereferenceFP",
  "DereferenceLP",
  "DereferenceSP",
  "DereferenceImmediate",
  "DereferencePop",
  "LogicTailTestFP",
  "LogicTailTestLP",
  "LogicTailTestSP",
  "LogicTailTestImmediate",
  "LogicTailTestPop",
  "ProcBreakpointFP",
  "ProcBreakpointLP",
  "ProcBreakpointSP",
  "ProcBreakpointImmediate",
  "ProcBreakpointPop",
  "PushLexicalVarFP",
  "PushLexicalVarLP",
  "PushLexicalVarSP",
  "PushLexicalVarImmediate",
  "PushLexicalVarPop",
  "Block0WriteFP",
  "Block0WriteLP",
  "Block0WriteSP",
  "Block0WriteImmediate",
  "Block0WritePop",
  "Block1WriteFP",
  "Block1WriteLP",
  "Block1WriteSP",
  "Block1WriteImmediate",
  "Block1WritePop",
  "Block2WriteFP",
  "Block2WriteLP",
  "Block2WriteSP",
  "Block2WriteImmediate",
  "Block2WritePop",
  "Block3WriteFP",
  "Block3WriteLP",
  "Block3WriteSP",
  "Block3WriteImmediate",
  "Block3WritePop",
  "ZeropFP",
  "ZeropLP",
  "ZeropSP",
  "ZeropImmediate",
  "ZeropPop",
  "MinuspFP",
  "MinuspLP",
  "MinuspSP",
  "MinuspImmediate",
  "MinuspPop",
  "PluspFP",
  "PluspLP",
  "PluspSP",
  "PluspImmediate",
  "PluspPop",
  "TypeMember",
  "TypeMemberNoPop",
  "LocateLocals",
  "CatchClose",
  "GenericDispatch",
  "MessageDispatch",
  "CheckPreemptRequest",
  "PushGlobalLogicVariable",
  "NoOp",
  "Halt",
  "BranchTrue",
  "BranchTrueElseExtraPop",
  "BranchTrueAndExtraPop",
  "BranchTrueExtraPop",
  "BranchTrueNoPop",
  "BranchTrueAndNoPop",
  "BranchTrueElseNoPop",
  "BranchTrueAndNoPopElseNoPopExtraPop",
  "BranchFalse",
  "BranchFalseElseExtraPop",
  "BranchFalseAndExtraPop",
  "BranchFalseExtraPop",
  "BranchFalseNoPop",
  "BranchFalseAndNoPop",
  "BranchFalseElseNoPop",
  "BranchFalseAndNoPopElseNoPopExtraPop",
  "PushFP",
  "PushLP",
  "PushSP",
  "PushImmediate",
  "PushPop",
  "PushNNils",
  "PushAddressSpRelativeFP",
  "PushAddressSpRelativeLP",
  "PushAddressSpRelativeSP",
  "PushAddressSpRelativeImmediate",
  "PushAddressSpRelativePop",
  "PushLocalLogicVariablesFP",
  "PushLocalLogicVariablesLP",
  "PushLocalLogicVariablesSP",
  "PushLocalLogicVariablesImmediate",
  "PushLocalLogicVariablesPop",
  "ReturnMultipleFP",
  "ReturnMultipleLP",
  "ReturnMultipleSP",
  "ReturnMultipleImmediate",
  "ReturnMultiplePop",
  "ReturnKludgeFP",
  "ReturnKludgeLP",
  "ReturnKludgeSP",
  "ReturnKludgeImmediate",
  "ReturnKludgePop",
  "TakeValues",
  "UnbindNImmediate",
  "UnbindNPop",
  "PushInstanceVariable",
  "PushAddressInstanceVariable",
  "PushInstanceVariableOrdered",
  "PushAddressInstanceVariableOrdered",
  "UnaryMinusFP",
  "UnaryMinusLP",
  "UnaryMinusSP",
  "UnaryMinusImmediate",
  "UnaryMinusPop",
  "ReturnSingleNIL",
  "ReturnSingleT",
  "ReturnSingleTOS",
  "MemoryRead",
  "MemoryReadAddress",
  "Block0Read",
  "Block1Read",
  "Block2Read",
  "Block3Read",
  "Block0ReadShift",
  "Block1ReadShift",
  "Block2ReadShift",
  "Block3ReadShift",
  "Block0ReadTest",
  "Block1ReadTest",
  "Block2ReadTest",
  "Block3ReadTest",
  "FinishCallN",
  "FinishCallNApply",
  "FinishCallTos",
  "FinishCallTosApply",
  "SetToCarFP",
  "SetToCarLP",
  "SetToCarSP",
  "SetToCarImmediate",
  "SetToCarPop",
  "SetToCdrFP",
  "SetToCdrLP",
  "SetToCdrSP",
  "SetToCdrImmediate",
  "SetToCdrPop",
  "SetToCdrPushCarFP",
  "SetToCdrPushCarLP",
  "SetToCdrPushCarSP",
  "SetToCdrPushCarImmediate",
  "SetToCdrPushCarPop",
  "IncrementFP",
  "IncrementLP",
  "IncrementSP",
  "IncrementImmediate",
  "IncrementPop",
  "DecrementFP",
  "DecrementLP",
  "DecrementSP",
  "DecrementImmediate",
  "DecrementPop",
  "PointerIncrementFP",
  "PointerIncrementLP",
  "PointerIncrementSP",
  "PointerIncrementImmediate",
  "PointerIncrementPop",
  "SetCdrCode1FP",
  "SetCdrCode1LP",
  "SetCdrCode1SP",
  "SetCdrCode1Immediate",
  "SetCdrCode1Pop",
  "SetCdrCode2FP",
  "SetCdrCode2LP",
  "SetCdrCode2SP",
  "SetCdrCode2Immediate",
  "SetCdrCode2Pop",
  "PushAddressFP",
  "PushAddressLP",
  "PushAddressSP",
  "PushAddressImmediate",
  "PushAddressPop",
  "SetSpToAddressFP",
  "SetSpToAddressLP",
  "SetSpToAddressSP",
  "SetSpToAddressImmediate",
  "SetSpToAddressPop",
  "SetSpToAddressSaveTosFP",
  "SetSpToAddressSaveTosLP",
  "SetSpToAddressSaveTosSP",
  "SetSpToAddressSaveTosImmediate",
  "SetSpToAddressSaveTosPop",
  "ReadInternalRegister",
  "WriteInternalRegister",
  "CoprocessorRead",
  "CoprocessorWrite",
  "Block0ReadAluFP",
  "Block0ReadAluLP",
  "Block0ReadAluSP",
  "Block0ReadAluImmediate",
  "Block0ReadAluPop",
  "Block1ReadAluFP",
  "Block1ReadAluLP",
  "Block1ReadAluSP",
  "Block1ReadAluImmediate",
  "Block1ReadAluPop",
  "Block2ReadAluFP",
  "Block2ReadAluLP",
  "Block2ReadAluSP",
  "Block2ReadAluImmediate",
  "Block2ReadAluPop",
  "Block3ReadAluFP",
  "Block3ReadAluLP",
  "Block3ReadAluSP",
  "Block3ReadAluImmediate",
  "Block3ReadAluPop",
  "Ldb",
  "CharLdb",
  "PLdb",
  "PTagLdb",
  "Branch",
  "LoopDecrementTos",
  "EntryRestAccepted",
  "EntryRestNotAccepted",
  "RplacaFP",
  "RplacaLP",
  "RplacaSP",
  "RplacaImmediate",
  "RplacaPop",
  "RplacdFP",
  "RplacdLP",
  "RplacdSP",
  "RplacdImmediate",
  "RplacdPop",
  "MultiplyFP",
  "MultiplyLP",
  "MultiplySP",
  "MultiplyImmediate",
  "MultiplyPop",
  "QuotientFP",
  "QuotientLP",
  "QuotientSP",
  "QuotientImmediate",
  "QuotientPop",
  "CeilingFP",
  "CeilingLP",
  "CeilingSP",
  "CeilingImmediate",
  "CeilingPop",
  "FloorFP",
  "FloorLP",
  "FloorSP",
  "FloorImmediate",
  "FloorPop",
  "TruncateFP",
  "TruncateLP",
  "TruncateSP",
  "TruncateImmediate",
  "TruncatePop",
  "RoundFP",
  "RoundLP",
  "RoundSP",
  "RoundImmediate",
  "RoundPop",
  "RationalQuotientFP",
  "RationalQuotientLP",
  "RationalQuotientSP",
  "RationalQuotientImmediate",
  "RationalQuotientPop",
  "MinFP",
  "MinLP",
  "MinSP",
  "MinImmediate",
  "MinPop",
  "MaxFP",
  "MaxLP",
  "MaxSP",
  "MaxImmediate",
  "MaxPop",
  "AluFP",
  "AluLP",
  "AluSP",
  "AluImmediate",
  "AluPop",
  "LogandFP",
  "LogandLP",
  "LogandSP",
  "LogandImmediate",
  "LogandPop",
  "LogxorFP",
  "LogxorLP",
  "LogxorSP",
  "LogxorImmediate",
  "LogxorPop",
  "LogiorFP",
  "LogiorLP",
  "LogiorSP",
  "LogiorImmediate",
  "LogiorPop",
  "RotFP",
  "RotLP",
  "RotSP",
  "RotImmediate",
  "RotPop",
  "LshFP",
  "LshLP",
  "LshSP",
  "LshImmediate",
  "LshPop",
  "MultiplyDoubleFP",
  "MultiplyDoubleLP",
  "MultiplyDoubleSP",
  "MultiplyDoubleImmediate",
  "MultiplyDoublePop",
  "LshcBignumStepFP",
  "LshcBignumStepLP",
  "LshcBignumStepSP",
  "LshcBignumStepImmediate",
  "LshcBignumStepPop",
  "StackBltFP",
  "StackBltLP",
  "StackBltSP",
  "StackBltImmediate",
  "StackBltPop",
  "RgetfFP",
  "RgetfLP",
  "RgetfSP",
  "RgetfImmediate",
  "RgetfPop",
  "MemberFP",
  "MemberLP",
  "MemberSP",
  "MemberImmediate",
  "MemberPop",
  "AssocFP",
  "AssocLP",
  "AssocSP",
  "AssocImmediate",
  "AssocPop",
  "PointerPlusFP",
  "PointerPlusLP",
  "PointerPlusSP",
  "PointerPlusImmediate",
  "PointerPlusPop",
  "PointerDifferenceFP",
  "PointerDifferenceLP",
  "PointerDifferenceSP",
  "PointerDifferenceImmediate",
  "PointerDifferencePop",
  "AshFP",
  "AshLP",
  "AshSP",
  "AshImmediate",
  "AshPop",
  "StoreConditionalFP",
  "StoreConditionalLP",
  "StoreConditionalSP",
  "StoreConditionalImmediate",
  "StoreConditionalPop",
  "MemoryWriteFP",
  "MemoryWriteLP",
  "MemoryWriteSP",
  "MemoryWriteImmediate",
  "MemoryWritePop",
  "PStoreContentsFP",
  "PStoreContentsLP",
  "PStoreContentsSP",
  "PStoreContentsImmediate",
  "PStoreContentsPop",
  "BindLocativeToValueFP",
  "BindLocativeToValueLP",
  "BindLocativeToValueSP",
  "BindLocativeToValueImmediate",
  "BindLocativeToValuePop",
  "UnifyFP",
  "UnifyLP",
  "UnifySP",
  "UnifyImmediate",
  "UnifyPop",
  "PopLexicalVarFP",
  "PopLexicalVarLP",
  "PopLexicalVarSP",
  "PopLexicalVarImmediate",
  "PopLexicalVarPop",
  "MovemLexicalVarFP",
  "MovemLexicalVarLP",
  "MovemLexicalVarSP",
  "MovemLexicalVarImmediate",
  "MovemLexicalVarPop",
  "EqualNumberFP",
  "EqualNumberLP",
  "EqualNumberSP",
  "EqualNumberImmediate",
  "EqualNumberPop",
  "LesspFP",
  "LesspLP",
  "LesspSP",
  "LesspImmediate",
  "LesspPop",
  "GreaterpFP",
  "GreaterpLP",
  "GreaterpSP",
  "GreaterpImmediate",
  "GreaterpPop",
  "EqlFP",
  "EqlLP",
  "EqlSP",
  "EqlImmediate",
  "EqlPop",
  "EqualNumberNoPopFP",
  "EqualNumberNoPopLP",
  "EqualNumberNoPopSP",
  "EqualNumberNoPopImmediate",
  "EqualNumberNoPopPop",
  "LesspNoPopFP",
  "LesspNoPopLP",
  "LesspNoPopSP",
  "LesspNoPopImmediate",
  "LesspNoPopPop",
  "GreaterpNoPopFP",
  "GreaterpNoPopLP",
  "GreaterpNoPopSP",
  "GreaterpNoPopImmediate",
  "GreaterpNoPopPop",
  "EqlNoPopFP",
  "EqlNoPopLP",
  "EqlNoPopSP",
  "EqlNoPopImmediate",
  "EqlNoPopPop",
  "EqFP",
  "EqLP",
  "EqSP",
  "EqImmediate",
  "EqPop",
  "LogtestFP",
  "LogtestLP",
  "LogtestSP",
  "LogtestImmediate",
  "LogtestPop",
  "EqNoPopFP",
  "EqNoPopLP",
  "EqNoPopSP",
  "EqNoPopImmediate",
  "EqNoPopPop",
  "LogtestNoPopFP",
  "LogtestNoPopLP",
  "LogtestNoPopSP",
  "LogtestNoPopImmediate",
  "LogtestNoPopPop",
  "AddFP",
  "AddLP",
  "AddSP",
  "AddImmediate",
  "AddPop",
  "SubFP",
  "SubLP",
  "SubSP",
  "SubImmediate",
  "SubPop",
  "32BitPlusFP",
  "32BitPlusLP",
  "32BitPlusSP",
  "32BitPlusImmediate",
  "32BitPlusPop",
  "32BitDifferenceFP",
  "32BitDifferenceLP",
  "32BitDifferenceSP",
  "32BitDifferenceImmediate",
  "32BitDifferencePop",
  "AddBignumStepFP",
  "AddBignumStepLP",
  "AddBignumStepSP",
  "AddBignumStepImmediate",
  "AddBignumStepPop",
  "SubBignumStepFP",
  "SubBignumStepLP",
  "SubBignumStepSP",
  "SubBignumStepImmediate",
  "SubBignumStepPop",
  "MultiplyBignumStepFP",
  "MultiplyBignumStepLP",
  "MultiplyBignumStepSP",
  "MultiplyBignumStepImmediate",
  "MultiplyBignumStepPop",
  "DivideBignumStepFP",
  "DivideBignumStepLP",
  "DivideBignumStepSP",
  "DivideBignumStepImmediate",
  "DivideBignumStepPop",
  "Aset1FP",
  "Aset1LP",
  "Aset1SP",
  "Aset1Immediate",
  "Aset1Pop",
  "AllocateListBlockFP",
  "AllocateListBlockLP",
  "AllocateListBlockSP",
  "AllocateListBlockImmediate",
  "AllocateListBlockPop",
  "Aref1FP",
  "Aref1LP",
  "Aref1SP",
  "Aref1Immediate",
  "Aref1Pop",
  "Aloc1FP",
  "Aloc1LP",
  "Aloc1SP",
  "Aloc1Immediate",
  "Aloc1Pop",
  "StoreArrayLeaderFP",
  "StoreArrayLeaderLP",
  "StoreArrayLeaderSP",
  "StoreArrayLeaderImmediate",
  "StoreArrayLeaderPop",
  "AllocateStructureBlockFP",
  "AllocateStructureBlockLP",
  "AllocateStructureBlockSP",
  "AllocateStructureBlockImmediate",
  "AllocateStructureBlockPop",
  "ArrayLeaderFP",
  "ArrayLeaderLP",
  "ArrayLeaderSP",
  "ArrayLeaderImmediate",
  "ArrayLeaderPop",
  "AlocLeaderFP",
  "AlocLeaderLP",
  "AlocLeaderSP",
  "AlocLeaderImmediate",
  "AlocLeaderPop",
  "PopInstanceVariable",
  "MovemInstanceVariable",
  "PopInstanceVariableOrdered",
  "MovemInstanceVariableOrdered",
  "InstanceRefFP",
  "InstanceRefLP",
  "InstanceRefSP",
  "InstanceRefImmediate",
  "InstanceRefPop",
  "InstanceSetFP",
  "InstanceSetLP",
  "InstanceSetSP",
  "InstanceSetImmediate",
  "InstanceSetPop",
  "InstanceLocFP",
  "InstanceLocLP",
  "InstanceLocSP",
  "InstanceLocImmediate",
  "InstanceLocPop",
  "SetTagFP",
  "SetTagLP",
  "SetTagSP",
  "SetTagImmediate",
  "SetTagPop",
  "UnsignedLesspFP",
  "UnsignedLesspLP",
  "UnsignedLesspSP",
  "UnsignedLesspImmediate",
  "UnsignedLesspPop",
  "UnsignedLesspNoPopFP",
  "UnsignedLesspNoPopLP",
  "UnsignedLesspNoPopSP",
  "UnsignedLesspNoPopImmediate",
  "UnsignedLesspNoPopPop",
  "PopFP",
  "PopLP",
  "PopSP",
  "PopImmediate",
  "PopPop",
  "MovemFP",
  "MovemLP",
  "MovemSP",
  "MovemImmediate",
  "MovemPop",
  "MergeCdrNoPopFP",
  "MergeCdrNoPopLP",
  "MergeCdrNoPopSP",
  "MergeCdrNoPopImmediate",
  "MergeCdrNoPopPop",
  "FastAref1FP",
  "FastAref1LP",
  "FastAref1SP",
  "FastAref1Immediate",
  "FastAref1Pop",
  "FastAset1FP",
  "FastAset1LP",
  "FastAset1SP",
  "FastAset1Immediate",
  "FastAset1Pop",
  "StackBltAddressFP",
  "StackBltAddressLP",
  "StackBltAddressSP",
  "StackBltAddressImmediate",
  "StackBltAddressPop",
  "Dpb",
  "CharDpb",
  "PDpb",
  "PTagDpb",
  "LoopIncrementTosLessThan",
  "CatchOpen",
  "Hack",
  "PushNull",
  "PushMonitorForward",
  "PushHeaderP",
  "PushHeaderI",
  "PushExternalValueCellPointer",
  "PushOneQForward",
  "PushHeaderForward",
  "PushElementForward",
  "PushFixnum",
  "PushSmallRatio",
  "PushSingleFloat",
  "PushDoubleFloat",
  "PushBignum",
  "PushBigRatio",
  "PushComplex",
  "PushSpareNumber",
  "PushInstance",
  "PushListInstance",
  "PushArrayInstance",
  "PushStringInstance",
  "PushNil",
  "PushList",
  "PushArray",
  "PushString",
  "PushSymbol",
  "PushLocative",
  "PushLexicalClosure",
  "PushDynamicClosure",
  "PushCompiledFunction",
  "PushGenericFunction",
  "PushSparePointer1",
  "PushSparePointer2",
  "PushPhysicalAddress",
  "PushSpareImmediate1",
  "PushBoundLocation",
  "PushCharacter",
  "PushLogicVariable",
  "PushGcForward",
  "PushEvenPc",
  "PushOddPc",
  "CallCompiledEven",
  "CallCompiledOdd",
  "CallIndirect",
  "CallGeneric",
  "CallCompiledEvenPrefetch",
  "CallCompiledOddPrefetch",
  "CallIndirectPrefetch",
  "CallGenericPrefetch",
  "PushPackedInstruction60",
  "PushPackedInstruction61",
  "PushPackedInstruction62",
  "PushPackedInstruction63",
  "PushPackedInstruction64",
  "PushPackedInstruction65",
  "PushPackedInstruction66",
  "PushPackedInstruction67",
  "PushPackedInstruction70",
  "PushPackedInstruction71",
  "PushPackedInstruction72",
  "PushPackedInstruction73",
  "PushPackedInstruction74",
  "PushPackedInstruction75",
  "PushPackedInstruction76",
  "PushPackedInstruction77",
  "InstructionCacheLookup",
  "IllegalInstruction"
};

int InstructionCacheMiss (void)
{
  Integer block_vma;
  InstructionCacheLine *block_cp;
  LispObj *block_instruction;
  
  block_vma = (processor->pc.DATA.u & ~((InstructionCacheLineSize >> 1) - 1));
  block_cp = processor->InstructionCache + ((block_vma << 1) & (InstructionCacheSize - 1));
  
  {
    Integer bound_vma = block_vma + (InstructionCacheLineSize>>1);
    Integer vma;
    InstructionCacheLine *even_cp, *odd_cp;
    LispObj instruction_block[(InstructionCacheLineSize>>1)];
    LispObj *instruction = &instruction_block[0];
    Tag tag;
    Integer data;
    
    VirtualMemoryReadBlock(block_vma, instruction_block, (InstructionCacheLineSize>>1));
    
    for (vma = block_vma, even_cp = block_cp, odd_cp = block_cp + 1;
    vma < bound_vma;
    vma++, instruction++, even_cp += 2, odd_cp += 2)
      {
	tag = instruction->TAG;
	data = instruction->DATA.u;
	even_cp->pc.DATA.u = vma;
	odd_cp->pc.DATA.u = vma;
	switch (TagCdr(tag))
	{
	  case 0:
	    even_cp->next_pc.TAG = TypeOddPC;
	    even_cp->next_pc.DATA.u = vma;
	    even_cp->next_cp = odd_cp;
	    odd_cp->next_pc.TAG = TypeEvenPC;
	    odd_cp->next_pc.DATA.u = vma + 1;
	    odd_cp->next_cp = even_cp + 2;
	    goto DecodePackedWord;
	    
	  case 3:
	    even_cp->next_pc.TAG = TypeEvenPC;
	    even_cp->next_pc.DATA.u = vma + 1;
	    even_cp->next_cp = even_cp + 2;
	    odd_cp->next_pc.TAG = TypeEvenPC;
	    odd_cp->next_pc.DATA.u = vma + 2;
	    odd_cp->next_cp = even_cp + 4;
	    break;
	    
	  case 2:
	    even_cp->next_pc.TAG = TypeOddPC;
	    even_cp->next_pc.DATA.u = vma - 1;
	    even_cp->next_cp = odd_cp - 2;
	    odd_cp->next_pc.TAG = TypeEvenPC;
	    odd_cp->next_pc.DATA.u = vma;
	    odd_cp->next_cp = &InstructionCacheLookupCPRepresentation;
	    break;
	    
	  case 1:
	    even_cp->code = IllegalInstructionDecoder;
	    even_cp->operand = 0;
	    even_cp->instruction = 0;
	    odd_cp->code = IllegalInstructionDecoder;
	    odd_cp->operand = 0;
	    odd_cp->instruction = 0;
	    goto SkipDecode;
	}
	
	if (!PackedInstructionP (tag))
	  {
	    even_cp->code = WordInstructionDecoder [TagType(tag)];
	    even_cp->operand = data;
	    even_cp->instruction = 0;
	    odd_cp->code = IllegalInstructionDecoder;
	    odd_cp->operand = 0;
	    odd_cp->instruction = 0;
	  }
	else
	  {
	    DecodePackedWord:
	    { Integer instruction;
	      register const DecoderPair *p;
	      
	      instruction = data & 0777777;
	      even_cp->instruction = instruction;
	      p = PackedInstructionDecoder + (instruction >> 8);
	      even_cp->code = (int) (p->dispatch);
	      (p->decode) (data, even_cp);
	      
	      instruction = ((tag & 017) << 14) | ldb(14,18,data);
	      odd_cp->instruction = instruction;
	      p = PackedInstructionDecoder + (instruction >> 8);
	      odd_cp->code = (int) (p->dispatch);
	      (p->decode) (instruction, odd_cp);
	    }
	  }
	SkipDecode: {}
      }
    /* Because of instruction sequencing, some of the cache pointer assignments we
    made may actually point out of this cache line.  Go back and look at the possibly
    errant pointers, and force a cache lookup if necessary. */
    if (block_cp->next_pc.DATA.u < block_vma) 
      block_cp->next_cp = &InstructionCacheLookupCPRepresentation;
    even_cp = block_cp + InstructionCacheLineSize - 4;
    if (even_cp->next_pc.DATA.u >= bound_vma) 
      even_cp->next_cp = &InstructionCacheLookupCPRepresentation;
    if ((++even_cp)->next_pc.DATA.u >= bound_vma) 
      even_cp->next_cp = &InstructionCacheLookupCPRepresentation;
    if ((++even_cp)->next_pc.DATA.u >= bound_vma) 
      even_cp->next_cp = &InstructionCacheLookupCPRepresentation;
    if ((++even_cp)->next_pc.DATA.u >= bound_vma)
      even_cp->next_cp = &InstructionCacheLookupCPRepresentation;
  }
  return (0);
}
